### ISSUE TITLE
how can I translate I want it

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#10]
https://imgdb.in/iiLs
open file
https://imgdb.in/iiLt
OCR
https://imgdb.in/iiLu
pick text [remove]
https://imgdb.in/iiLv
and then...

error how can I do?

**Comment by xulihang** [comment]
You didn't give the error message. The localization may also cause a problem. The translated text should have unique source text.

**Comment by bravehon** [comment]
error: java.lang.IndexOutOfBoundsException: Index: 34, Size: 34
StackTrace: java.lang.IndexOutOfBoundsException: Index: 34, Size: 34
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_BoxesListView_SelectedIndexChanged.resume(main.java:2820)
	at org.xulihang.imagetrans.main._boxeslistview_selectedindexchanged(main.java:2626)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

error: java.lang.IndexOutOfBoundsException: Index: 32, Size: 32
StackTrace: java.lang.IndexOutOfBoundsException: Index: 32, Size: 32
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_BoxesListView_SelectedIndexChanged.resume(main.java:2820)
	at org.xulihang.imagetrans.main._boxeslistview_selectedindexchanged(main.java:2626)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

like this

**Comment by xulihang** [comment]
I need exact steps to replicate this error.

**Comment by bravehon** [comment]
> I need exact steps to replicate this error.

first I apply text detect >> and edit text >> text recognize and text expansion,merge this section has error

**Comment by xulihang** [comment]
You'd better use English UI strings or record this process. It is hard for me to redo what you said.

**Comment by bravehon** [comment]
Text detection > and edit text > text recongnition , expand areas , merge areas

**Comment by xulihang** [comment]
I did the same with custom workflow. I haven't encountered any errors.

![image](https://user-images.githubusercontent.com/5462205/109492111-6e250d00-7ac5-11eb-869b-7d0c4612cf83.png)

Maybe it is related to specific images.

**Comment by bravehon** [comment]
> I did the same with custom workflow. I haven't encountered any errors.
> 
> ![image](https://user-images.githubusercontent.com/5462205/109492111-6e250d00-7ac5-11eb-869b-7d0c4612cf83.png)
> 
> Maybe it is related to specific images.

I send email ! can I check?

**Comment by xulihang** [comment]
1. As you are using Clova to do text detection, there is no need to do text recognition. Text is already extracted.
2. Set a minimum font size if the font is too small. The autoFontSize works for the default font on my Chinese Windows 10 environment. But it may not work for some font. I haven't figured out the reason.
![image](https://user-images.githubusercontent.com/5462205/110777955-b0f09d00-829c-11eb-88f1-aca53199213d.png)
3. The BoxesListView_SelectedIndexChanged error may be related to the performance of the computer. My computer is fast enough so that I haven't met errors.

**Comment by bravehon** [comment]
> 1. As you are using Clova to do text detection, there is no need to do text recognition. Text is already extracted.
> 2. Set a minimum font size if the font is too small. The autoFontSize works for the default font on my Chinese Windows 10 environment. But it may not work for some font. I haven't figured out the reason.
>    ![image](https://user-images.githubusercontent.com/5462205/110777955-b0f09d00-829c-11eb-88f1-aca53199213d.png)
> 3. The BoxesListView_SelectedIndexChanged error may be related to the performance of the computer. My computer is fast enough so that I haven't met errors.

Okay... Thank you for answer!

**Comment by xulihang** [comment]
The issues menthioned here are resolved with https://github.com/xulihang/ImageTrans-docs/issues/6 https://github.com/xulihang/ImageTrans-docs/issues/16
