### ISSUE TITLE
Translation assistant crashes

### ISSUE THREAD

**Issue by ngawangtrinley** [xulihang/ImageTrans-docs#101]
![](https://user-images.githubusercontent.com/17675331/141334729-078caca6-53a2-4018-a21d-63dbc49a7a6c.gif)

error: java.lang.RuntimeException: Object should first be initialized (List).  
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).  
at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)  
at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)  
at org.xulihang.imagetrans.googlewithoutapikeymtplugin$ResumableSub\_translate.resume(googlewithoutapikeymtplugin.java:412)  
at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)  
at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)  
at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)  
at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)  
at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)  
at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)  
at java.security.AccessController.doPrivileged(Native Method)  
at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)  
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)  
at com.sun.glass.ui.win.WinApplication.\_runLoop(Native Method)  
at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)  
at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
It seems that Google does not support Tibetan.

You can use niutrans:

![image](https://user-images.githubusercontent.com/5462205/141393591-3a91934d-17a0-4021-8739-52b35e46ede6.png)

The language code is `ti`:

![image](https://user-images.githubusercontent.com/5462205/141393691-cd18eaa2-2e41-48c2-9d4b-9606dae46ed6.png)
