### ISSUE TITLE
在线翻译报错

### ISSUE THREAD

**Issue by fqawxf** [xulihang/ImageTrans-docs#103]
error: java.lang.ArrayIndexOutOfBoundsException: -1
StackTrace: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main._currentfilename(main.java:3888)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2705)
	at org.xulihang.imagetrans.main._batchtranslation(main.java:2349)
	at org.xulihang.imagetrans.server$ResumableSub_wsh_Translate.resume(server.java:611)
	at org.xulihang.imagetrans.server._wsh_translate(server.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.CallSubNew2(Common.java:442)
	at org.xulihang.imagetrans.websockethandler._ws_textmessage(websockethandler.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
chrome插件的服务器我记得默认是用的腾讯翻译，你改成百度了吗，换个别的引擎再试试吧。支持一次请求翻译所有片段的有百度和彩云小译，百度有时候会报错，应该是原文存在空白片段或者语言对不支持。
