### ISSUE TITLE
I need a help for to fix error

### ISSUE THREAD

**Issue by monoala** [xulihang/ImageTrans-docs#104]
error: java.io.FileNotFoundException: C:\Users\na\AppData\Local\Temp\10 (액세스가 거부되었습니다)
StackTrace: java.io.FileNotFoundException: C:\Users\na\AppData\Local\Temp\10 (�׼����� �źεǾ����ϴ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
 ------------------------------
error cause when I select text area
how can I fix this error?

**Comment by xulihang** [comment]
This issue has been found by the users before: https://github.com/xulihang/ImageTrans-docs/issues/66 https://github.com/xulihang/ImageTrans-docs/issues/88

I think this is an upstream problem which is related to the B4X technology that ImageTrans uses. The exact reason is still unknown. I will try to report this on the B4X forum.

**Comment by xulihang** [comment]
Since I can't reproduce this issue on my side, I haven't figured out the exact reason.

**Comment by xulihang** [comment]
Could you record a video showing how this issue happens?

The issue is related to network request. You can use offline OCRs like WinRT and Tesseract to avoid this error.

**Comment by monoala** [comment]
I resolved the problem. In my case it cause the project file those not
located in imagetrans  folder.

I moved the project file to the folder where 'imagetrans.exe' is located,
then error was no more.

thank you for your kindful answer.

2021년 11월 16일 (화) 오후 11:31, Lihang Xu ***@***.***>님이 작성:
