### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by lastbla** [xulihang/ImageTrans-docs#106]
error: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
StackTrace: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.WriteToStream(B4XViewWrapper.java:819)
	at org.xulihang.imagetrans.utils._saveimgtodiskwithsizecheck(utils.java:2912)
	at org.xulihang.imagetrans.ocr$ResumableSub_baidu.resume(ocr.java:455)
	at org.xulihang.imagetrans.ocr._baidu(ocr.java:411)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2378)
	at org.xulihang.imagetrans.ocr._gettextwithlocation(ocr.java:2235)
	at org.xulihang.imagetrans.main$ResumableSub_autoRecognizeText.resume(main.java:1817)
	at org.xulihang.imagetrans.main._autorecognizetext(main.java:1719)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2638)
	at org.xulihang.imagetrans.main._batchtranslation(main.java:2322)
	at org.xulihang.imagetrans.main._imagescrollpane_action(main.java:7555)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/637285030.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1567581361.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/1645995473.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
The image is too large. Do not use detecting text of the whole image. You can ocr every text areas instead.
