### ISSUE TITLE
Can't translate a thing, error always occur

### ISSUE THREAD

**Issue by zamirace** [xulihang/ImageTrans-docs#113]
error: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
StackTrace: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
	at org.xulihang.imagetrans.sogouocrplugin$ResumableSub_GetText.resume(sogouocrplugin.java:533)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

Follow step from youtube but not helping at all

**Comment by xulihang** [comment]
Sogou is a paid Chinese OCR service and is not enabled by default. You can try other OCR engines like Baidu, Tesseract, WinRT, and Google Drive.

You can learn about this here: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr
