### ISSUE TITLE
Error when trying to batch translate.

### ISSUE THREAD

**Issue by SmartCoin** [xulihang/ImageTrans-docs#116]
error: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
StackTrace: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
	at org.xulihang.imagetrans.googleocrplugin$ResumableSub_GetTextWithLocation.resume(googleocrplugin.java:427)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
You need to fill in your API keys to use Google OCR. Related issue: https://github.com/xulihang/ImageTrans-docs/issues/95
