### ISSUE TITLE
Google Drive OCR Error

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#121]
Hi have added your google drive ocr server and made google account stuff added vision api and made cert file but get error.
Is the Service account credentials file the right file.

This is ImageTrans when i press ocr.

<html><head><meta http-equiv="Content-Type" content="text/html;charset=utf-8"/><title>Error 405 HTTP method POST is not supported by this URL</title></head><body><h2>HTTP ERROR 405</h2><p>Problem accessing /. Reason:<pre>    HTTP method POST is not supported by this URL</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/></body></html>

This in Java.

Dez 27, 2021 7:25:04 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNUNG: unable to change permissions for everybody: D:\mangareader\batch\ImageTrans\tokens
Dez 27, 2021 7:25:04 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNUNG: unable to change permissions for owner: D:\mangareader\batch\ImageTrans\tokens
null
2021-12-27 07:25:04.499:WARN:oejs.HttpChannel:qtp1826771953-34: /ocr
java.lang.NullPointerException
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:248)
        at com.xulihang.googledrive.OCRServlet.doPost(OCRServlet.java:87)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:170)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:369)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Unknown Source)
2021-12-27 07:25:04.499:WARN:oejs.HttpChannel:qtp1826771953-34:
java.lang.IllegalStateException: Error already set
        at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:743)
        at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:514)
        at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:463)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:448)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Unknown Source)
Caused by:
java.lang.NullPointerException
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:248)
        at com.xulihang.googledrive.OCRServlet.doPost(OCRServlet.java:87)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:170)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Don't use the server version. Use the cli version first according to this: https://github.com/xulihang/Google-Drive-OCR-Java

**Comment by hentaitaku** [comment]
When i use by the server version the OAuth client ID credentials then i get "No creds found."
Will the cli work in ImageTrans  when i select google drive and press ocr?

**Comment by xulihang** [comment]
Replace the default server version plugin with the command-line version of plugin: https://github.com/xulihang/ImageTrans-docs/files/7404613/google_drive.zip

**Comment by xulihang** [comment]
The complete guide: https://github.com/xulihang/ImageTrans-docs/issues/91#issuecomment-950313389

**Comment by hentaitaku** [comment]
Thx is working now.
