### ISSUE TITLE
imagetrans throw error some translated page

### ISSUE THREAD

**Issue by monoala** [xulihang/ImageTrans-docs#128]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:171)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1063)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:3501)
	at org.xulihang.imagetrans.utils._textmask(utils.java:3358)
	at org.xulihang.imagetrans.main._gentextmask(main.java:6362)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:13962)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:13867)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:18319)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:17999)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.3) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3850)
	... 27 more

error appeared when I check 'view translated image' what located at the bottom left of the UI

**Comment by xulihang** [comment]
This has been reported before: https://github.com/xulihang/ImageTrans-docs/issues/66#issuecomment-870796182

The user solved this by removing some small text areas.

I can't reproduce this problem. Could you provide a test project?
