### ISSUE TITLE
frozen_graph.pb加载失败

### ISSUE THREAD

**Issue by YUEMINGQING** [xulihang/ImageTrans-docs#142]
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "D:\下载\ImageTrans-windows-x64\ImageTrans\frozen_graph.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "D:\����\ImageTrans-windows-x64\ImageTrans\frozen_graph.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
]
	at org.opencv.dnn.Dnn.readNet_2(Native Method)
	at org.opencv.dnn.Dnn.readNet(Dnn.java:396)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.imageclassifier._initialize(imageclassifier.java:211)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:6850)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:6738)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2744)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
软件路径不要有中文，文字置信度模型会加载失败

**Comment by YUEMINGQING** [comment]
感谢可以使用了，但是像韩漫那种就只翻译目录其他的都不翻译，韩漫地址在这里 Asura Scans - Read Comics
<https://www.asurascans.com/>希望作者大大可以解决下
Lihang Xu ***@***.***> 于2022年1月26日周三 19:50写道：

**Comment by xulihang** [comment]
具体哪个韩漫，我看看

**Comment by xulihang** [comment]
你是怎么翻译的，用的插件吗？插件只能翻译鼠标下方的单张图片。

**Comment by YUEMINGQING** [comment]
okok原来只能翻译鼠标下方的单张图片明白了感谢解答

Lihang Xu ***@***.***> 于2022年1月27日周四 22:14写道：
