### ISSUE TITLE
googlewithoutapi translate all text area error

### ISSUE THREAD

**Issue by perobruh** [xulihang/ImageTrans-docs#156]
This error show up when i tried to "Translate All Text Areas" with googlewithoutapi, it used to work normally but now it didn't show any result and this error show up, pls help me

error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_supportBatchTranslation.resume(mt.java:1597)
	at org.xulihang.imagetrans.mt._supportbatchtranslation(mt.java:1533)
	at org.xulihang.imagetrans.main$ResumableSub_pretranslate.resume(main.java:13855)
	at org.xulihang.imagetrans.main._pretranslate(main.java:13777)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:11572)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:10049)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
googlewithoutapi does not work anymore recently. Since it is not officially supported by google, I may remove this plugin if I can't find a new way around.

**Comment by aravindnc** [comment]
I was able to use googlewithoutapi.. it opens a popup and translate text. I was able to use it easily in a project today. But sometime later today when I tried to do it, the popup is not showing up.

**Comment by xulihang** [comment]
googlewithoutapikey does open a popup. Are you using the web mt which opens an in-app browser and shows the web page of google?

**Comment by aravindnc** [comment]
Yes it does open an in app browser.

**Comment by aravindnc** [comment]
Sorry its the web-mt that's working, not googlewithoutapi.

**Comment by xulihang** [comment]
googlewithoutapikey has been removed.
