### ISSUE TITLE
I'm unable to import translation

### ISSUE THREAD

**Issue by aravindnc** [xulihang/ImageTrans-docs#159]
Getting this error while importing a translated docx file.

error: java.lang.RuntimeException: Method: getText not found in: org.apache.poi.xwpf.usermodel.XWPFSDT
StackTrace: java.lang.RuntimeException: Method: getText not found in: org.apache.poi.xwpf.usermodel.XWPFSDT
	at anywheresoftware.b4j.object.JavaObject$MethodCache.getMethod(JavaObject.java:363)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:120)
	at org.xulihang.imagetrans.poiword._readcells(poiword.java:338)
	at org.xulihang.imagetrans.poiword._readtablewithparagraphs(poiword.java:434)
	at org.xulihang.imagetrans.main._importdocx(main.java:8402)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:11442)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:10650)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Could you send me the project and the docx file? I don't have a problem importing translation from a docx file.

**Comment by aravindnc** [comment]
I've managed to do it manually. So, what I did was export to docx file, then upload it to Google Drive, added translations, export to docx then when I tried to import it - it gives me above error.

**Comment by xulihang** [comment]
Google might altered the table and ImageTrans cannot handle such a situation. You can paste the translation to the docx file mannually and then import it.

**Comment by aravindnc** [comment]
Thanks. I will try that and reopen this issue if needed.
