### ISSUE TITLE
预览时使用精确涂抹文字时报错

### ISSUE THREAD

**Issue by 799190761** [xulihang/ImageTrans-docs#173]
版本windows

报错如下
`error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:200)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1107)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:3606)
	at org.xulihang.imagetrans.utils._textmask(utils.java:3463)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7151)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:15708)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:15613)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:20637)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:20288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3868)
	... 26 more
`

**Comment by 799190761** [comment]
问题已经解决 有个意外生成的识别框，无法在图层上发现，在文本框里删了就行
