### ISSUE TITLE
系统报错

### ISSUE THREAD

**Issue by 799190761** [xulihang/ImageTrans-docs#174]
在一个图片中反复打开掩膜覆盖会导致程序错误，现象为报错加上掩膜变成纯白窗口，其他窗口也无法操作和显示纯白，但是按键这些可以操作，都是无法正常显示只能盲操

这报错都是纯白窗口，盲操复制的。。。
`error: java.lang.IllegalArgumentException: Unrecognized image loader: null
StackTrace: java.lang.IllegalArgumentException: Unrecognized image loader: null
	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
	at javafx.scene.Node.doSnapshot(Node.java:1864)
	at javafx.scene.Node.snapshot(Node.java:1942)
	at anywheresoftware.b4j.objects.NodeWrapper.Snapshot2(NodeWrapper.java:370)
	at org.xulihang.imagetrans.maskeditor._getmask(maskeditor.java:470)
	at org.xulihang.imagetrans.textremover$ResumableSub_RemoveButton_MouseClicked.resume(textremover.java:768)
	at org.xulihang.imagetrans.textremover._removebutton_mouseclicked(textremover.java:723)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by 799190761** [comment]
经过我不严谨的测试发现
这个现象只会出现在图片体积较大和高分辨率图片上？（3500x 9MB）
较低分辨率不会出现？具体操作是首次打开软件使用图像淹膜正常操作，但是再次打开图像淹膜就会一片白，关闭图像淹膜窗口后软件无法正常操作，（感觉是无法显示了，按钮这些都还能用）
分辨率过高导致内存溢出还是什么？有什么办法能调低吗？

**Comment by xulihang** [comment]
反复打开掩膜，在软件里具体是怎么操作的？

我测试上万像素的图像是没问题的，就是我没有用线程，处理时会把界面卡住

**Comment by 799190761** [comment]
就打开 编辑/生成淹膜 这时一切正常
然后再打开一次 编辑/生成淹膜 就弹出来的窗口就纯白了，关闭窗口后 主程序也没反应了，就感觉是gui刷新不了了，但是还能操作。
`error: java.lang.IllegalArgumentException: Unrecognized image loader: null
StackTrace: java.lang.IllegalArgumentException: Unrecognized image loader: null
	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
	at javafx.scene.Node.doSnapshot(Node.java:1864)
	at javafx.scene.Node.snapshot(Node.java:1942)
	at anywheresoftware.b4j.objects.NodeWrapper.Snapshot2(NodeWrapper.java:370)
	at org.xulihang.imagetrans.maskeditor._btnok_mouseclicked(maskeditor.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
!
`
![Screenshot 2022-03-08 124252](https://user-images.githubusercontent.com/62172605/157167728-3e5fe16f-8c75-4a3e-91a6-00c70c91ba8c.png)

**Comment by xulihang** [comment]
发张图片我测试下吧，可以发邮箱

**Comment by 799190761** [comment]
[test.zip](https://github.com/xulihang/ImageTrans-docs/files/8202871/test.zip)

**Comment by xulihang** [comment]
我试下了没问题。报错可能是内存不足了，你下的是64位版还是32位版的？

**Comment by 799190761** [comment]
下的是64位版,内存也有48g 应该不会不够，会不会是因为用的win11的原因....或者缺少某些依赖库还是依赖库是x86的.....

**Comment by 799190761** [comment]
我这边用cmd的方式启动jar...得到了更多的报错 然后没操作一次软件就会这样报错，希望有帮助，如果实在不行我压缩一下文件算了

`java.lang.NullPointerException
        at com.sun.javafx.sg.prism.NGCanvas$RenderBuf.validate(NGCanvas.java:213)
        at com.sun.javafx.sg.prism.NGCanvas.initCanvas(NGCanvas.java:640)
        at com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:603)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.CacheFilter.impl_renderNodeToCache(CacheFilter.java:671)
        at com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:575)
        at com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2358)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2044)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at com.sun.javafx.sg.prism.NGCanvas$RenderBuf.validate(NGCanvas.java:213)
        at com.sun.javafx.sg.prism.NGCanvas.initCanvas(NGCanvas.java:640)
        at com.sun.javafx.sg.prism.NGCanvas.renderForcedContent(NGCanvas.java:624)
        at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
        at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
        at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
        at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
        at com.sun.javafx.sg.prism.NGGroup.renderForcedContent(NGGroup.java:198)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:332)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Unknown Source)`

**Comment by xulihang** [comment]
我没在Windows 11上测过，可能是有关系。可以换一个最新的jre试试，不行的话暂时还是只能压缩图片了。

下载Liberica JRE Full version：https://bell-sw.com/pages/downloads/

**Comment by xulihang** [comment]
还有Java虚拟机的内存默认是有限的，可以设大一点：

```
java -jar -Xmx2048M ImageTrans.jar 
```
