### ISSUE TITLE
OPUS-CAT 的插件

### ISSUE THREAD

**Issue by jacknion** [xulihang/ImageTrans-docs#177]
文档里写着[Fiskmo机器翻译插件](https://github.com/xulihang/BasicCAT/tree/master/plugins/fiskmoMT)调用

这个插件下载放到plugin目录下，没法使用

**Comment by xulihang** [comment]
需要重新编译下。用附件这个吧

[fiskmoMTplugin.zip](https://github.com/xulihang/ImageTrans-docs/files/8239125/fiskmoMTplugin.zip)

**Comment by jacknion** [comment]
仍然不能使用。 提示错误：error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:734)
	at org.xulihang.imagetrans.mt._getmt(mt.java:599)
	at org.xulihang.imagetrans.main$ResumableSub_showMT.resume(main.java:18589)
	at org.xulihang.imagetrans.main._showmt(main.java:18480)
	at org.xulihang.imagetrans.main._operationtabpane_tabchanged(main.java:14663)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)


另外：是用 FiskmoMTEngine 还是 OpusCatMTEngine_v1.1.0.7？

**Comment by xulihang** [comment]
你的FiskmoMT跑起来没有，需要管理员权限。这两个是一样的，就是新版改名叫OPUS-CAT了

**Comment by xulihang** [comment]
新版可能有变化，还是等我测试下再试吧

**Comment by jacknion** [comment]
好的。那个插件编译工具用的是什么？ 我可以自己测试一下

**Comment by xulihang** [comment]
B4J: https://www.b4x.com/b4j.html

需要把package name改成org.xulihang.imagetrans，还要下载[ABPlugin](https://www.b4x.com/android/forum/threads/abplugin-live-plugin-library-for-your-apps.67395/#content)这个库

**Comment by jacknion** [comment]
应该还是插件的错误，

错误提示：java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.ab.abplugin.ABPlugin.RunPlugin(ABPlugin.java:182)
        at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:871)
        at org.xulihang.imagetrans.mt._getmt(mt.java:599)
        at org.xulihang.imagetrans.main$ResumableSub_showMT.resume(main.java:18589)
        at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Object should first be initialized (Map).
        at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
        at anywheresoftware.b4a.objects.collections.Map.GetDefault(Map.java:73)
        at org.xulihang.imagetrans.fiskmomtplugin$ResumableSub_translate.resume(fiskmomtplugin.java:216)
        at org.xulihang.imagetrans.fiskmomtplugin._translate(fiskmomtplugin.java:168)
        at org.xulihang.imagetrans.fiskmomtplugin$ResumableSub_Run.resume(fiskmomtplugin.java:129)
        at org.xulihang.imagetrans.fiskmomtplugin._run(fiskmomtplugin.java:61)

**Comment by xulihang** [comment]
我看了下，是偏好设置里没有opus的设置导致报错。

重新做了个新的opus插件，应该可以用了：

[opusMTplugin.zip](https://github.com/xulihang/ImageTrans-docs/files/8281319/opusMTplugin.zip)

![image](https://user-images.githubusercontent.com/5462205/158735376-1347a59c-fdfc-4ad0-ada7-bd2c28de68ff.png)

**Comment by xulihang** [comment]
opus的汉语模型是多语言的，普通话的代码是cmn，插件已经自动转换了（zh->cmn）

**Comment by jacknion** [comment]
Cool!

Thanks.

**Comment by kongsam3** [comment]
OPUS-CAT  软件怎么调用啊？下了几个模型，然后？？

**Comment by xulihang** [comment]
保持OPUS-CAT运行，然后在ImageTrans里使用就行。
