### ISSUE TITLE
an error occured

### ISSUE THREAD

**Issue by shibith** [xulihang/ImageTrans-docs#2]
error: (NullPointerException) java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.imagetrans.project._import(project.java:285)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:6406)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:5971)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
You have to create a new project first. I haven't disabled the menuitem when there is no opened project.

**Comment by shibith** [comment]
Hi ,

I did that, but still getting the same error.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xulihang** [comment]
I just tested it and it worked. 

1. File->New
2. File->Import pictures (from a folder)

Could you describe your steps in detail?

**Comment by shibith** [comment]
Hi ,

I am able to add picture ,but translation function not working.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xulihang** [comment]
Do you want to use machine translation? You have to setup their API keys enable and these MT engines first.

Among them, mymemory and cloudtranslation are free. You also have to setup the project's language pair.

**Comment by xulihang** [comment]
In addition, switch to Translation assist tab before clicking the text boxes to get translation results.
