### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by Orwellzhou** [xulihang/ImageTrans-docs#203]
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:769: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'cv::Mat::Mat'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:769: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'cv::Mat::Mat'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:127)
	at sun.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.InitializeNewInstance(JavaObject.java:91)
	at org.xulihang.imagetrans.cvmat._initialize(cvmat.java:119)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:1982)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:1888)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:17835)
	at org.xulihang.imagetrans.main._removetext(main.java:17775)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:15942)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Please check if there are boxes outside of the image.

![image](https://user-images.githubusercontent.com/5462205/168508810-f9797b8d-7f4f-42f3-9ca9-5306b0fe7a08.png)


I will fix this problem in the new version.

**Comment by xulihang** [comment]
Fixed in v1.7.0
