### ISSUE TITLE
遇到新的BUG图片读取出错

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#217]
error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.utils._validategeometry(utils.java:4736)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4234)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4148)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4102)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7309)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7249)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16209)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16116)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:21415)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:21059)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.Platform
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

[bandicam 2022-05-31 13-28-42-637.zip](https://github.com/xulihang/ImageTrans-docs/files/8802269/bandicam.2022-05-31.13-28-42-637.zip)
[bandicam 2022-05-31 13-27-10-798.zip](https://github.com/xulihang/ImageTrans-docs/files/8802285/bandicam.2022-05-31.13-27-10-798.zip)

第一个问题是图片读取错误
第二个问题是重新读取文件夹显示无图片
因为视频 那个太暴露了 我就打成压缩包了 还请开发者老哥下载看一下吧纯NSFW
然后这个报错 是 右键刷新时候出现的

**Comment by xulihang** [comment]
选择的文件夹的图片和当前导入的图片没有变化，会提示没有检测到图片。

**Comment by xulihang** [comment]
不同图片的内容一样，这个不清楚原因
