### ISSUE TITLE
Error Translate after OCR

### ISSUE THREAD

**Issue by pierobm72** [xulihang/ImageTrans-docs#221]
```
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:872)
	at org.xulihang.imagetrans.mt._getmt(mt.java:600)
	at org.xulihang.imagetrans.main$ResumableSub_translateOnxBox.resume(main.java:21013)
	at org.xulihang.imagetrans.main._translateonxbox(main.java:20964)
	at org.xulihang.imagetrans.main._quicktranslate(main.java:16622)
	at org.xulihang.imagetrans.main$ResumableSub_OCRButtonClicked.resume(main.java:14955)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```

https://user-images.githubusercontent.com/83485127/172529639-88e5923e-2522-49a4-8b55-b7bf9bc126fd.mp4

**Comment by xulihang** [comment]
You checked Translate after OCR so it will try machine translation after OCR and your setup of machine translation is not correct.

You need to fill in your own API keys to use deepl and google.
