### ISSUE TITLE
选择区域框后点辅助翻译弹出错

### ISSUE THREAD

**Issue by googril** [xulihang/ImageTrans-docs#226]
error: java.lang.ClassCastException: anywheresoftware.b4a.objects.collections.List cannot be cast to java.lang.String
StackTrace: java.lang.ClassCastException: anywheresoftware.b4a.objects.collections.List cannot be cast to java.lang.String
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:878)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
启动的哪些机器翻译？默认能用的有百度、腾讯、云译、deeplfree这些，其它的话不配置api是有可能报错的

**Comment by googril** [comment]
> 启动的哪些机器翻译？默认能用的有百度、腾讯、云译、deeplfree这些，其它的话不配置api是有可能报错的

启动了百度识别+百度翻译 和不行后试试下 ocrspace识别+百度翻译
