### ISSUE TITLE
Removing Custom Api breaks the program

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#23]
I have obtained my own ocrspace and baidu api which works fine. The problem is when I remove the appid and the key the entire program breaks, nothing works anymore. And when I restart the program, even the Dark theme which I have on doesn't work. Whenever I click on anything I get an error like this for example

error: java.util.NoSuchElementException
StackTrace: java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at anywheresoftware.b4a.objects.collections.Map$MyMap.getEntry(Map.java:219)
	at anywheresoftware.b4a.objects.collections.Map$MyMap.getValue(Map.java:199)
	at anywheresoftware.b4a.objects.collections.Map.GetValueAt(Map.java:108)
	at org.xulihang.imagetrans.utils._loaddefaultapikeys(utils.java:1625)
	at org.xulihang.imagetrans.utils._getprefmap(utils.java:1280)
	at org.xulihang.imagetrans.utils._getpref(utils.java:1259)
	at org.xulihang.imagetrans.main$ResumableSub_OCRBox.resume(main.java:11677)
	at org.xulihang.imagetrans.main._ocrbox(main.java:11623)
	at org.xulihang.imagetrans.main$ResumableSub_OCRButton_MouseClicked.resume(main.java:12003)
	at org.xulihang.imagetrans.main._ocrbutton_mouseclicked(main.java:11845)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:93)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:941)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

I fix this issue by having a backup folder of ImageTrans and just replace my current ImageTrans Folder with the backup. It seems that when you remove your custom Api, the program doesn't go back to the default Api that you have set which for some reason breaks everything.

**Comment by xulihang** [comment]
Thanks for the feedback. 
I found this was because after the keys are removed, the data stored in `preferences.conf` is empty. I have fixed this.

**Comment by xulihang** [comment]
Fixed in v1.3.4
