### ISSUE TITLE
百度识别弹错，API申请了，balloon_detection_url填错影响？填aip.baidubce.com没错吧

### ISSUE THREAD

**Issue by googril** [xulihang/ImageTrans-docs#231]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:735)
	at org.xulihang.imagetrans.mt._getmt(mt.java:600)
	at org.xulihang.imagetrans.main$ResumableSub_translateOnxBox.resume(main.java:21013)
	at org.xulihang.imagetrans.main._translateonxbox(main.java:20964)
	at org.xulihang.imagetrans.main._quicktranslate(main.java:16622)
	at org.xulihang.imagetrans.main$ResumableSub_OCRButtonClicked.resume(main.java:14955)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
百度有文字识别和翻译两种api。这里报错的是机器翻译

**Comment by xulihang** [comment]
同https://github.com/xulihang/ImageTrans-docs/issues/228
