### ISSUE TITLE
image isn't visible after importing

### ISSUE THREAD

**Issue by drizzlry** [xulihang/ImageTrans-docs#234]
when i import images, they don't show up.

tried with multiple images/image formats, still doesn't work

tried around a bit and when i pressed on "one-click translation" i'm getting the error code
`error: java.lang.IllegalArgumentException: src cannot be null
StackTrace: java.lang.IllegalArgumentException: src cannot be null
	at org.imgscalr.Scalr.crop(Scalr.java:848)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.Crop(B4XViewWrapper.java:868)
	at org.xulihang.imagetrans.main._croppedbox(main.java:4305)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:7870)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:7681)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2951)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
`

but you can clearly see the program is actually identifying something
![](https://i.imgur.com/nSgoNp3.png)

compared to the image
![](https://i.imgur.com/RAnW411.png)

i hope it's just a simple issue as reinstalling some components haha
best regards :)

**Comment by xulihang** [comment]
Could you send some images so that I can have a test?

**Comment by drizzlry** [comment]
i doubt that it has anything to do with the images and more with something i'm doing wrong haha (i tried about 30 different ones)

if i try to import images from a folder i get this message btw
![](https://i.imgur.com/Enbu6e9.png)

do you think just downloading it again could fix everything?

**Comment by xulihang** [comment]
> do you think just downloading it again could fix everything?

I don't think so, please send me the images and I will record an operation video.

**Comment by drizzlry** [comment]
![07](https://user-images.githubusercontent.com/108278472/176094955-9d7f3174-85c2-4300-8a96-195be1fba07e.png)
![01](https://user-images.githubusercontent.com/108278472/176095000-b73e6fc4-1574-4bd3-ac92-abe6161d7dd9.png)
![88](https://user-images.githubusercontent.com/108278472/176095054-f6501aab-2458-4cf0-9d8c-e6ded6b7b8f0.png)
![43](https://user-images.githubusercontent.com/108278472/176095093-8a1011ef-958b-4286-8836-670b0b3fbd60.png)

tell me if u need more :)

**Comment by xulihang** [comment]
I see. These images are webp images. ImageTrans can process them but cannot display them. You need to convert them to jpg or png.

**Comment by drizzlry** [comment]
ohhhh my bad, thanks a lot!
