### ISSUE TITLE
关于报错导出卡住的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#246]
尊敬的老哥今天在看漫画的时候遇到了这个问题
--------------------------------------------
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:778: error: (-215:Assertion failed) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function 'cv::Mat::Mat'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:778: error: (-215:Assertion failed) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function 'cv::Mat::Mat'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:127)
	at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.InitializeNewInstance(JavaObject.java:91)
	at org.xulihang.imagetrans.cvmat._initialize(cvmat.java:119)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2030)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:1895)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:18163)
	at org.xulihang.imagetrans.main._removetext(main.java:18103)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16206)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
----------------------------------------
![image](https://user-images.githubusercontent.com/30548000/185745639-f6cab06c-512b-4794-9286-e8dd136c345e.png)
这页莫名其妙的 报错只有一预览就报错
然后报错就报错吧 我把这报错的一页 重新开个软件重新开个项目
单独弄就没有再报错了
![image](https://user-images.githubusercontent.com/30548000/185745677-5b97046c-9407-45c7-8049-501c8562fa56.png)

然后在回到第一个软件里继续看其他的页面
全部看完润色完之后 生成成品图的时候
就来到了 本issues 的标题的问题
因为第五页翻译预览就报错 导致 导出成品图的时候一直就卡住不会跳过
就那么地死循环了 然后呢
解决办法就是我手动的一张一张的用宏一键操作一张一张的导出
这本是22页 还好 要是几十页上百页的 遇到这个问题 我手动导出也不说累死
但是也很费时间
所以您看下这个是什么问题造成的
或者出了这个问题的时候导出的时候您看能不能想办法给它优化下？
还是怎么地的处理

**Comment by xulihang** [comment]
可能是旋转的文字区域实际对应的矩形区域超出图片范围了，需要调整下。可以把项目文件和那张图片打包了发过来看看。

**Comment by lhj5426** [comment]
[00082.zip](https://github.com/xulihang/ImageTrans-docs/files/9387322/00082.zip)
保存的那一页和 项目

**Comment by lhj5426** [comment]
我就是删除 后来手动框选的手机里的旋转对话框也是会报错 就卡死这里了

**Comment by xulihang** [comment]
有一个宽度为负，高度为0的区域导致的这个问题。不是很清楚你是怎么创建的这个区域，手动调整的话我是有做限制的。
![image](https://user-images.githubusercontent.com/5462205/185773475-faa66e77-23ee-4f7a-a55b-5b75f89ae862.png)

**Comment by xulihang** [comment]
新版会加入对宽度高度是否为负的判断，为负就不处理这个区域

**Comment by lhj5426** [comment]
> 有一个宽度为负，高度为0的区域导致的这个问题。不是很清楚你是怎么创建的这个区域，手动调整的话我是有做限制的。 ![image](https://user-images.githubusercontent.com/5462205/185773475-faa66e77-23ee-4f7a-a55b-5b75f89ae862.png)

哈哈哈哈 因为手机里的文字部分太小然后创建只调整焦点然后因为太小很多框框重叠可能拖拽旋转的时候就成负数了？

**Comment by xulihang** [comment]
> 新版会加入对宽度高度是否为负的判断，为负就不处理这个区域

更新在1.7.7了

**Comment by lhj5426** [comment]
> > 新版会加入对宽度高度是否为负的判断，为负就不处理这个区域
> 
> 更新在1.7.7了

感谢 收到这就去更新
