### ISSUE TITLE
为什么运行彩云翻译报错啊，已经填写了api

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#248]
error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2563)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
检查下项目设置里的语言对的语言代码是不是正确。

比如日译中是ja_zh。

**Comment by hyominli** [comment]
> 

谢谢解决了。顺便问下怎样才能让翻译的文字竖排啊
