### ISSUE TITLE
Removing non-text area (OCR) error

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#25]
I've been using azure ocr for this and had no problems.
But the other ocr don't work properly, I'll use ocrspace and baidu accurate for an example. This doesn't happen on every picture, so it's not like it's not working at all.

Ocrspace error:

error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.ocr$ResumableSub_ocrspace.resume(ocr.java:3434)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

baidu accurate error

error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2407)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

There were other errors I got as well, but these two errors are the ones I almost always get. It's really a big problem when you use Removing non-text area (OCR) in a batch because if you get this error on page 25/80 then that's it, it will be stuck on that page forever and won't move on to the next pictures.

**Comment by xulihang** [comment]
OCRSpace and Baidu also have usage limits. I would recommend using the new [ImageTrans_OCR](https://github.com/xulihang/ImageTrans_OCR) to do this. This is a 100% offline solution with a high accuracy (works on vertical Japanese as well). Please for a while and I will upload a usable package.

**Comment by xulihang** [comment]
You can also use easyOCR. The steps to use it may be a bit complex.

You have to install it first and start the server with the provided python script: <https://github.com/xulihang/ImageTrans_plugins/tree/master/easyOCR/server>

**Comment by xulihang** [comment]
The offline solutions I mentioned above are not easy to deploy and take much more computing time without a GPU. Training a Japanese detection model is beyond my ability. 

I think currently, the windows 10's built-in OCR engine is the offline engine which combines efficiency, easiness and accuracy the best.

https://user-images.githubusercontent.com/5462205/113002369-48625500-91a4-11eb-8575-4a8e2c95894d.mp4
