### ISSUE TITLE
点击查看翻译就报这个错

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#258]
用的mangaocr和气泡检测，翻译是百度，勾选“精确抹除文字”的话一点查看翻译就报错，不勾的话就可以

error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:156)
	at org.xulihang.imagetrans.utils._appendsmallmask(utils.java:173)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4425)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4263)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4217)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7388)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7328)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16286)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16193)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:21535)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:21179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 47380568 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:413)
	... 29 more

**Comment by xulihang** [comment]
看起来像是图片太大，内存超了。这个图很大吗？

**Comment by yahoozhu** [comment]
图片是1M左右jpg，分辨率2400x3500，还有这个报错

error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 26059248 bytes in function 'cv::OutOfMemoryError'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 26059248 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:413)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:156)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2216)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:1986)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:18252)
	at org.xulihang.imagetrans.main._removetext(main.java:18192)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16295)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
用x64版的，可以用更多内存
