### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by smsmsm2000** [xulihang/ImageTrans-docs#266]
error: java.lang.IllegalArgumentException: Unrecognized image loader: null
StackTrace: java.lang.IllegalArgumentException: Unrecognized image loader: null
	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
	at javafx.scene.Node.doSnapshot(Node.java:1862)
	at javafx.scene.Node.snapshot(Node.java:1940)
	at anywheresoftware.b4j.objects.NodeWrapper.Snapshot2(NodeWrapper.java:370)
	at org.xulihang.imagetrans.maskeditor._setsizewithredraw(maskeditor.java:989)
	at org.xulihang.imagetrans.maskeditor._percentspinner_valuechanged(maskeditor.java:854)
	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

https://user-images.githubusercontent.com/108485001/189170832-6374b4d5-cd59-4f56-9ef9-63cd03c5e41b.mp4

**Comment by xulihang** [comment]
The image's width is too big. For now, ImageTrans only scales images with a large height. I need to add support for images with long width in the new version.

**Comment by xulihang** [comment]
Please try the new version 1.7.8. It should have fixed this problem.
