### ISSUE TITLE
一键翻译图片，百度翻译

### ISSUE THREAD

**Issue by googril** [xulihang/ImageTrans-docs#268]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_batchTranslate.resume(mt.java:490)
	at org.xulihang.imagetrans.mt._batchtranslate(mt.java:425)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2507)
	at org.xulihang.imagetrans.main._batchtranslate(main.java:2393)
	at org.xulihang.imagetrans.main$ResumableSub_pretranslate.resume(main.java:16015)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
百度翻译偶尔报错，一直翻译中

**Comment by xulihang** [comment]
百度翻译的每秒请求次数有限制，可能返回空结果，可以申请个自己的API、加大请求间隔或者换个别的机器翻译。
