### ISSUE TITLE
点击识别出现错误

### ISSUE THREAD

**Issue by MisterQX** [xulihang/ImageTrans-docs#283]
error: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
StackTrace: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at javafx.embed.swing.SwingFXUtils.fromFXImage(SwingFXUtils.java:255)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.Crop(B4XViewWrapper.java:867)
	at org.xulihang.imagetrans.main._croppedboxbasedonimageview(main.java:4385)
	at org.xulihang.imagetrans.main$ResumableSub_OCRBox.resume(main.java:14930)
	at org.xulihang.imagetrans.main._ocrbox(main.java:14893)
	at org.xulihang.imagetrans.main$ResumableSub_OCRButtonClicked.resume(main.java:15070)
	at org.xulihang.imagetrans.main._ocrbuttonclicked(main.java:15002)
	at org.xulihang.imagetrans.main._ocrbutton_mouseclicked(main.java:14996)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)

试过重启没有用

**Comment by MisterQX** [comment]
使用自动OCR所有区域弹出错误
error: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
StackTrace: java.lang.OutOfMemoryError: Java heap space

**Comment by xulihang** [comment]
这个图片很大吗，裁剪图片后OCR报内存不足了。

可以用x64版并用下面的命令启动，把java虚拟机的内存设大一点：

```
jre\bin\java -jar -Xmx2048M ImageTrans.jar 
```

**Comment by MisterQX** [comment]
5M多的图片算是很大吗？

**Comment by MisterQX** [comment]
> 这个图片很大吗，裁剪图片后OCR报内存不足了。
> 
> 可以用x64版并用下面的命令启动，把java虚拟机的内存设大一点：
> 
> ```
> jre\bin\java -jar -Xmx2048M ImageTrans.jar 
> ```
不好意思，我不太懂用x64版本的什么启动这条命令

**Comment by xulihang** [comment]
可以发张图片过来。

64位就是你下载windows-x64那个压缩包。

然后切换到软件目录，双击ImageTrans.bat打开软件，或者自己进入命令行窗口执行上面提到的命令。

**Comment by MisterQX** [comment]
执行之后显示这个
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
