### ISSUE TITLE
进行批处理-自动识别所有图片的文字时出现报错

### ISSUE THREAD

**Issue by MisterQX** [xulihang/ImageTrans-docs#284]
使用批处理-自动识别所有图片的文字时弹出报错
error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2431)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
选的哪个OCR引擎，可能是使用量超过了每天限制或者超过了每秒请求数限制。

每秒请求数过多可以把OCR间隔设大一点。

这个操作最好用离线OCR，或者自己申请在线服务的API 密钥。

**Comment by MisterQX** [comment]
请问团子翻译器的离线ocr可以使用吗

**Comment by xulihang** [comment]
团子应该用的paddleocr，需要自己配置，我没提供直接可用的打包

**Comment by MisterQX** [comment]
请问如何配置呢？
![image](https://user-images.githubusercontent.com/51272049/191680386-00ca998c-066e-42e3-b4ea-dc809c73f978.png)

**Comment by xulihang** [comment]
PaddleOCR配置还是比较麻烦的，你可以用WinRT这个离线OCR先试一下
