### ISSUE TITLE
使用OCR的时候出现错误

### ISSUE THREAD

**Issue by hong65201** [xulihang/ImageTrans-docs#299]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetText.resume(ocr.java:2185)
	at org.xulihang.imagetrans.ocr._gettext(ocr.java:1731)
	at org.xulihang.imagetrans.main$ResumableSub_OCRBox.resume(main.java:15045)
	at org.xulihang.imagetrans.main._ocrbox(main.java:15000)
	at org.xulihang.imagetrans.main$ResumableSub_OCRAllBoxes.resume(main.java:14687)
	at org.xulihang.imagetrans.main._ocrallboxes(main.java:14524)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:13111)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:11518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
用的哪个ocr啊

**Comment by hong65201** [comment]
baidu
研究了半天用不来，请问可以退款吗？
订单号：&nbsp;e8a3015644ffbd7ab95f27698dbd6461




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Oct 3, 2022 09:47 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [xulihang/ImageTrans-docs] 使用OCR的时候出现错误 (Issue #299)





 
用的哪个ocr啊

**Comment by xulihang** [comment]
订单事宜请邮件沟通。
