### ISSUE TITLE
Error code when importing pictures.

### ISSUE THREAD

**Issue by p3lende** [xulihang/ImageTrans-docs#30]
Hey, I bought the program yesterday, and I everything was going smoothly, up until 30 minutes ago that is. I wanted to start a new project, and when I clicked to import pictures from a folder I got a error code.
This is the error code I got: error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.imagetrans.project._getdirpath(project.java:223)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:9834)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:9325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by xulihang** [comment]
I think you haven't opened a project.

**Comment by p3lende** [comment]
Yeah I forgot about that step, my bad. Now I’m getting another problem, whenever I try to open up my pictures, it says they are not being detected, btw my pictures are in .jpeg, which I was able to open up before, but now it isn’t working. This is the code:



Any ideas on how to fix this problem? I also tried it with a pdf but the program was very slow and almost unusable.

**Comment by xulihang** [comment]
JPEG will not be detected as I didn't add this to the supported extensions list. For now, you have to change the jpeg extension to jpg.

**Comment by xulihang** [comment]
The default output dpi of the pdf render may be set too high. It will generate images with high resolution.

**Comment by xulihang** [comment]
Just miss touch the reopen button. By the way, you should create a new issue if it is a new one
