### ISSUE TITLE
Is this due to an API being selected and having no key?

### ISSUE THREAD

**Issue by Aleizter** [xulihang/ImageTrans-docs#311]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.basiccat.httputils2service._submitjob(httputils2service.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
You are using BasicCAT, not ImageTrans. Please post your issue here: https://github.com/xulihang/BasicCAT/issues

**Comment by Aleizter** [comment]
So my shortcut on my taskbar clearly shows a Image Trans Icon, and I'm in Image Trans when this pop-up shows. Usually when doing any batch operations? Are there different versions, cause I thought Image Trans was the one I purchased or donated to?

**Comment by xulihang** [comment]
The error message you've posted is different from the screenshot you just posted. Please open a new issue for this.

**Comment by Aleizter** [comment]
Initially I posted the text that is in the pop up in the center of this pic. Same issue, different presentation. Would if be better to send a screen recording of this issue in action?

**Comment by xulihang** [comment]
The second error message should be related to machine translation. Choose another machine translation as baidu's free usage limit has been reached.
