### ISSUE TITLE
一键翻译报错

### ISSUE THREAD

**Issue by YDHK** [xulihang/ImageTrans-docs#312]
error: java.lang.ArrayIndexOutOfBoundsException: -1
StackTrace: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main._currentfilename(main.java:3803)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2643)
	at org.xulihang.imagetrans.main._batchtranslation(main.java:2287)
	at org.xulihang.imagetrans.main._imagescrollpane_action(main.java:7439)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
用的哪个机器翻译？免费的百度的100万月额度已经超了，自己申请一个API或者换别的机器翻译吧

**Comment by YDHK** [comment]
换了个翻译还是一样的报错

**Comment by xulihang** [comment]
换个翻译，比如tencent应该就不是BatchTranslation批量翻译了

**Comment by xulihang** [comment]
噢，我看了下，不是机器翻译，是获取当前文件名失败了，检查下项目有几个文件吧

**Comment by YDHK** [comment]
哦哦，他有个out文件夹生成了

**Comment by YDHK** [comment]
我删除了新生成的文件，只保留原始图片。 用腾讯翻译，还是一样的报错

**Comment by xulihang** [comment]
我测了下没问题，截个这个区域的图看看。

![image](https://user-images.githubusercontent.com/5462205/198257677-2ea87637-9df8-4042-899c-8e2d81e9ced1.png)

**Comment by YDHK** [comment]
![image](https://user-images.githubusercontent.com/90520245/198354297-31c50577-d6e2-4c0e-85a3-a92d6e4b3144.png)

**Comment by xulihang** [comment]
下面的文件名列表看一下
