### ISSUE TITLE
i got an an error while using ocr

### ISSUE THREAD

**Issue by fakesmile0** [xulihang/ImageTrans-docs#315]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetText.resume(ocr.java:2185)
	at org.xulihang.imagetrans.ocr._gettext(ocr.java:1731)
	at org.xulihang.imagetrans.main$ResumableSub_OCRBox.resume(main.java:15080)
	at org.xulihang.imagetrans.main._ocrbox(main.java:15035)
	at org.xulihang.imagetrans.main$ResumableSub_OCRAllBoxes.resume(main.java:14722)
	at org.xulihang.imagetrans.main._ocrallboxes(main.java:14559)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:13141)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:11548)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by fakesmile0** [comment]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:156)
	at org.xulihang.imagetrans.utils._appendsmallmask(utils.java:173)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4532)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4370)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4324)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7547)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7487)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16461)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16368)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:21849)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:21493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 36864000 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:413)
	... 28 more

**Comment by xulihang** [comment]
Which OCR engine are you using?

**Comment by xulihang** [comment]
The second issue is not related to OCR. Please post a new issue.

**Comment by fakesmile0** [comment]
> Which OCR engine are you using?

I am using tencent ocr

**Comment by xulihang** [comment]
Tencent is a paid service. It is not available by default. You can check out which OCR is usable by default in the docs: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr
