### ISSUE TITLE
Another error while clicking on translated at the bottom

### ISSUE THREAD

**Issue by fakesmile0** [xulihang/ImageTrans-docs#316]
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 36864000 bytes in function 'cv::OutOfMemoryError'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 36864000 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:413)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:156)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2323)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:2016)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:18428)
	at org.xulihang.imagetrans.main._removetext(main.java:18365)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16470)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
A previous related issue: https://github.com/xulihang/ImageTrans-docs/issues/258

It might be related to an incorrect textbox with wrong size.
