### ISSUE TITLE
我使用ocr时出现错误

### ISSUE THREAD

**Issue by 386wai** [xulihang/ImageTrans-docs#319]
error: java.io.FileNotFoundException: C:\Users\386歪\AppData\Local\Temp\13 (拒绝访问。)
StackTrace: java.io.FileNotFoundException: C:\Users\386��\AppData\Local\Temp\13 (�ܾ����ʡ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
偏好设置里设置一下网络请求的临时文件夹。相关issue：https://github.com/xulihang/ImageTrans-docs/issues/218
