### ISSUE TITLE
BiDi issues

### ISSUE THREAD

**Issue by drkhateeb** [xulihang/ImageTrans-docs#326]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:219)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1187)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4574)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4414)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4368)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7565)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7505)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16479)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16386)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:22104)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:21748)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3868)
	... 29 more

**Comment by xulihang** [comment]
The error message is not related to BiDi.

It should be related to an incorrect textbox you created as discussed in this issue: https://github.com/xulihang/ImageTrans-docs/issues/173
