### ISSUE TITLE
Program does not start in Linux

### ISSUE THREAD

**Issue by M-Stenzel** [xulihang/ImageTrans-docs#327]
Hi team,

I cannot run the program, it bails out...

./jdk8u275-full/bin/java -jar ./ImageTrans.jar
Device locale: en
Found 755 strings.
(ArrayList) []
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
        at org.xulihang.imagetrans.main._loadopencv(main.java:10485)
        at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:1368)
        at org.xulihang.imagetrans.main._appstart(main.java:1314)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:769)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java455 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        ... 24 more

Loading jar finished
Initializing plugin abbyycloudOCR
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin easyocrOCR
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin clovaOCR
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin niutransMT
plugins have changed!
(ArrayList) [abbyycloudOCR, deeplfreeMT, easyocrOCR, paddleocrOCR, googleMT, opusMT, googleOCR, colorfulcloudsMT, clovaOCR, google_driveOCR, webMT, cloudtranslationMT, papagoMT, tencentOCR, niutransMT]
loading ocr plugins
main.start (java line: 37)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:769)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
        at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
        at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
        ... 14 more
Caused by: java.lang.NullPointerException
        at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
        at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
        at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
        at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
        at org.xulihang.imagetrans.main._application_error(main.java:1208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 15 more

---
Any ideas?

**Comment by xulihang** [comment]
OpenCV is not loaded. You need to have `libopencv_java455.so` in your library path (like `/usr/lib`).

You can compile your own or try the [precompiled one](https://github.com/xulihang/ImageTrans-docs/releases/download/opencv/Linux_libopencv_java455.zip).
