### ISSUE TITLE
An Error Occurred while uploading

### ISSUE THREAD

**Issue by fraftlle** [xulihang/ImageTrans-docs#33]
This happened when I tried uploading a pdf, but I've gotten similar screens when trying to upload images along with it not recognizing my jpgs

error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.imagetrans.project._getdirpath(project.java:223)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:9926)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:9325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by xulihang** [comment]
You have to create a project first. I will disable the import menu item if no project is opened in the next version.

**Comment by fraftlle** [comment]
Thank you, I figure out how to get images in, but it only uploads 1 image at a time, is there a way to upload batches?

**Comment by xulihang** [comment]
Put images all in a folder

**Comment by fraftlle** [comment]
They are but it only uploads the first one

**Comment by xulihang** [comment]
What's the full names of your images.

If their extension is jpeg, rename it to jpg

**Comment by fraftlle** [comment]
Well since its a full chapter I'm trying to do I have images named 1.jpg to 37.jpg

**Comment by xulihang** [comment]
I see. They are actually imported. You just have to use the next and previous to switch.

**Comment by fraftlle** [comment]
Ohhhh thank you~ I didn't notice those buttons lol
