### ISSUE TITLE
error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 StackTrace: ja

### ISSUE THREAD

**Issue by zhuritian1** [xulihang/ImageTrans-docs#330]
问下这个怎么解决，点一键翻译时遇见的

**Comment by zhuritian1** [comment]
error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2554)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
选的哪个机器翻译，可以换cloudtranslation看看

**Comment by zhuritian1** [comment]
刚刚选的百度，colorfulcloud指的是彩云码
&nbsp;


瑷☆你≌啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 StackTrace: ja (Issue #330)





 
选的哪个机器翻译，可以换cloudtranslation看看

**Comment by xulihang** [comment]
cloudtranslation是云译，colorfulclouds是彩云。云译不用api密钥，限制少。

**Comment by zhuritian1** [comment]
我这个cloudtranslation显示译文是[ERR] u'ja_zh-CN'
&nbsp;


瑷☆你≌啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 StackTrace: ja (Issue #330)





 
cloudtranslation是云译，colorfulclouds是彩云。云译不用api密钥，限制少。

**Comment by xulihang** [comment]
项目设置里把语言改成中文，不要用简体中文

**Comment by zhuritian1** [comment]
文字区域检测方法选哪个会比较好&nbsp; ，默认的启发式码？
&nbsp;


瑷☆你≌啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 StackTrace: ja (Issue #330)





 
项目设置里把语言改成中文，不要用简体中文

**Comment by xulihang** [comment]
日漫可以用百度网盘里提供的气泡检测模型

**Comment by zhuritian1** [comment]
问下我按着教程装好日漫ocr，它怎么启动啊，没看到按钮。
下载manga-ocr.zip，解压至英文路径的目录后运行run.bat，不要关闭弹出的窗口。

如果出现闪退，请按住Shift后右键，点“在此处打开Powershell窗口”，之后在出现的窗口里输入.\run.bat再按回车以运行，便于查看错误。

错误原因可能是需要翻墙或者模型下载错误。这时可以尝试下载网盘里提供的模型缓存文件，解压到你的用户目录的.cache\huggingface\transformers文件夹里（例如C:\Users\用户名\.cache\huggingface\transformers）。但注意这一方法可能会在模型更新后失效。

**Comment by xulihang** [comment]
还需要安装mangaocr的ImageTrans插件。还有这个是你转存的版本吗，最新的说明文件有变化，文件也更小。

**Comment by zhuritian1** [comment]
确实是转存百度网盘的，问下怎么更新ImageTrans，我才1.6.5，之前买的我都忘了是在哪的了&nbsp;


瑷☆你≌啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 StackTrace: ja (Issue #330)





 
还需要安装mangaocr的ImageTrans插件。还有这个是你转存的版本吗，最新的说明文件有变化，文件也更小。

**Comment by zhuritian1** [comment]
找到了，那我是只要把新版文件翻盖旧文件 就行了是吧

**Comment by xulihang** [comment]
覆盖就行了

**Comment by zhuritian1** [comment]
为什么我换成1.8.4 验证器显示我未购买。。
java.net.ConnectException: Failed to connect to
xulihanghai.gicp.net/125.123.217.151:5127

**Comment by xulihang** [comment]
服务器选NE。然后发布距离购买日期超过6个月的新版本是用不了的，可以用旧点的版本或者到这里续买新版：https://mbd.pub/o/bread/mbd-YpmUmJps

**Comment by zhuritian1** [comment]
问下我安装好manga-ocr后 运行run.bat后出现serving on 0.0.0.0:8080 view at http://127.0.0.1:8080。然后最后一步我没看懂：启动ImageTrans，选择manga-ocr进行文字识别。
我没在ImageTrans里找到manga-ocr这个选项 请问它在哪里

**Comment by xulihang** [comment]
需要安装下插件
![image](https://user-images.githubusercontent.com/5462205/205847265-e49b57e4-a464-427e-a49f-686838521da6.png)

**Comment by zhuritian1** [comment]
mangaOCRPlugin.jar和mangaOCRPlugin.xml这两个文件吗？放到ImageTrans 的plugins文件夹中？我放了也没有

**Comment by xulihang** [comment]
重启一下软件

**Comment by zhuritian1** [comment]
还是没有 不会和我的paython是3.10有关系吧

**Comment by zhuritian1** [comment]
弄好了，好像是覆盖文件的缘故

**Comment by zhuritian1** [comment]
为什么我不能设置字体样式
error: java.lang.ArrayIndexOutOfBoundsException: -1
StackTrace: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.typesetting._setlocalstylebutton_mouseclicked(typesetting.java:504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$358(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
这个是设置单个文字区域样式用的，得先选中一个

**Comment by zhuritian1** [comment]
![0)G41Z)MDZJ_8(1T7MRNET](https://user-images.githubusercontent.com/119782624/205898088-db1abeb7-0a51-4ec9-b75a-b62ff72b2f35.png)
不是啊 我连添加字体样式都添加不了

**Comment by xulihang** [comment]
ps字体名称没写，可以随便写一个

**Comment by zhuritian1** [comment]
自然场景文字检测怎么装，没看懂

**Comment by zhuritian1** [comment]
![{ })36Y60EQWRC_XQSBQV@M](https://user-images.githubusercontent.com/119782624/206098860-7477a299-78cc-41d5-8e6b-2d4f9d4f1c2a.png)
问下我这个按合并上下区域怎么没用啊

**Comment by xulihang** [comment]
项目设置里勾选下这个看看：
![image](https://user-images.githubusercontent.com/5462205/206099985-9458dedd-20ae-4727-9e0f-00be34f0827e.png)
