### ISSUE TITLE
This report came up after sitting idle

### ISSUE THREAD

**Issue by randoomdude** [xulihang/ImageTrans-docs#331]
Not sure what it means but everything is working nomrally I think

**Comment by randoomdude** [comment]
error: java.io.FileNotFoundException: C:\Users\Reiwa\Documents\ImageTrans-windows-x64 1.7.2 Jun 3\old\ImageTrans\ImageTrans\Jahver 2.itp (The system cannot find the path specified)
StackTrace: java.io.FileNotFoundException: C:\Users\Reiwa\Documents\ImageTrans-windows-x64 1.7.2 Jun 3\old\ImageTrans\ImageTrans\Jahver 2.itp (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at anywheresoftware.b4a.objects.streams.File.WriteString(File.java:259)
	at org.xulihang.imagetrans.project._save(project.java:700)
	at org.xulihang.imagetrans.autosaver._autosavetimer_tick(autosaver.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
There is an auto saver which saves the project every 10 minutes. Please check if you can save the project correctly.
