### ISSUE TITLE
报告问题

### ISSUE THREAD

**Issue by 258039** [xulihang/ImageTrans-docs#332]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:735)
	at org.xulihang.imagetrans.mt._getmt(mt.java:600)
	at org.xulihang.imagetrans.main$ResumableSub_translateOnxBox.resume(main.java:21793)
	at org.xulihang.imagetrans.main._translateonxbox(main.java:21744)
	at org.xulihang.imagetrans.main._quicktranslate(main.java:16923)
	at org.xulihang.imagetrans.main$ResumableSub_OCRButtonClicked.resume(main.java:15258)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
勾选了“OCR后翻译”之后识别文字，调用机器翻译出错，检查下偏好设置里默认启用的是哪个机器翻译，可以换一个再试试
