### ISSUE TITLE
Error report for translation

### ISSUE THREAD

**Issue by randoomdude** [xulihang/ImageTrans-docs#333]
I think some of the translators aren't working, I just added the manga-ocr

error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.basiccat.httputils2service._submitjob(httputils2service.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/6027132/208164116-64970f2d-8772-4917-b67c-e1b2b08539c9.png)

**Comment by randoomdude** [comment]
Also is there a way to set one of the translators a
![image](https://user-images.githubusercontent.com/6027132/208164989-76e4d4aa-3356-47d8-8a9d-c572a93293b3.png)
s the default in your translator list?

**Comment by xulihang** [comment]
You need to set up your own API key to use DeepL.

The first enabled machine translation is the default one.
