### ISSUE TITLE
生成文字掩膜时出现问题

### ISSUE THREAD

**Issue by 386wai** [xulihang/ImageTrans-docs#336]
error: java.lang.IllegalArgumentException: Unrecognized image loader: null
StackTrace: java.lang.IllegalArgumentException: Unrecognized image loader: null
	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
	at javafx.scene.Node.doSnapshot(Node.java:1864)
	at javafx.scene.Node.snapshot(Node.java:1942)
	at anywheresoftware.b4j.objects.NodeWrapper.Snapshot2(NodeWrapper.java:370)
	at org.xulihang.imagetrans.maskeditor._btnok_mouseclicked(maskeditor.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
相关issue：https://github.com/xulihang/ImageTrans-docs/issues/266

图片有多大？我对大图有缩放的处理，照理都是能够处理的。发个图过来看看

**Comment by 386wai** [comment]
<img width="285" alt="Snipaste_2022-12-21_17-35-51" src="https://user-images.githubusercontent.com/117648749/208872721-641dfb31-ea05-4fd7-8a4d-c5465222237a.png">

**Comment by xulihang** [comment]
可以先用批处理里面的生成所有图片的掩膜的功能，之后编辑单个区域的掩膜，而不是全图

**Comment by 386wai** [comment]
试了一下，编辑时还是会报错

**Comment by xulihang** [comment]
图片发我邮箱看看 admin@basiccat.org

**Comment by 386wai** [comment]
额，似乎又可以了
我先生成了一个无掩膜的掩模图，然后再单个编辑，没有报错🤔
