### ISSUE TITLE
The Server doesn't work

### ISSUE THREAD

**Issue by crownaintanoob** [xulihang/ImageTrans-docs#338]
I've been trying to use the Server, along with the chrome extension, and it hasn't worked at all, keeps showing this error:
![image](https://user-images.githubusercontent.com/70343800/209753241-b1213ecc-3293-48d7-9d25-dfd7849d404a.png)

error: java.lang.IllegalArgumentException: src cannot be null
StackTrace: java.lang.IllegalArgumentException: src cannot be null
	at org.imgscalr.Scalr.crop(Scalr.java:848)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.Crop(B4XViewWrapper.java:868)
	at org.xulihang.imagetrans.main._croppedbox(main.java:4353)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:8126)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:7937)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2990)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xulihang** [comment]
Could you send me the link of the image? It fails to crop the text area. Maybe it is a webp format image which causes the problem.

**Comment by crownaintanoob** [comment]
> Could you send me the link of the image? It fails to crop the text area. Maybe it is a webp format image which causes the problem.

https://s2.baozimh.com/scomic/xianwudizun-erciyuandongman/0/323-wz5e/3.jpg

**Comment by crownaintanoob** [comment]
I think I found the issue, It's probably because I had Dev Tools Console on

**Comment by crownaintanoob** [comment]
The image result doesn't load, it just changes the non translated image, to a blank image: 
![image](https://user-images.githubusercontent.com/70343800/209761460-4d5b25fe-4c65-445a-87f1-b04a0202ad04.png)

this is the blank image's url:
data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9U6KKKAP/2Q==

**Comment by xulihang** [comment]
The image is a webp image which causes all the problem.

![image](https://user-images.githubusercontent.com/5462205/209762015-89f1e27d-b5fa-4400-b3f1-2f1b78bb8dbd.png)

**Comment by crownaintanoob** [comment]
> The image is a webp image which causes all the problem.
> 
> ![image](https://user-images.githubusercontent.com/5462205/209762015-89f1e27d-b5fa-4400-b3f1-2f1b78bb8dbd.png)

oh, is there a fix then ?
I want to use that website if possible.

**Comment by xulihang** [comment]
If the image's link contains webp, ImageTrans will convert it to JPEG. But the website's link is JPEG while the actual format is webp. For the current version of ImageTrans, it cannot handle such a case.

**Comment by crownaintanoob** [comment]
Oh, I'll try to find a different website that works with it, thanks !

**Comment by xulihang** [comment]
I've added a detection of the image's format using the `file` command in version 1.8.5, which should solve the webp with its extension as jpg problem.
