### ISSUE TITLE
Error detecting the text using OCRSpace

### ISSUE THREAD

**Issue by jackneonatom** [xulihang/ImageTrans-docs#348]
error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr$ResumableSub_ocrspace.resume(ocr.java:3441)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
The free quota of baidu translation has been reached, which causes this problem. Try to use another machine translation service like deeplfree, cloudtranslation or mymemory.

**Comment by jackneonatom** [comment]
![0006](https://user-images.githubusercontent.com/122718848/212530532-da3a0fe2-8580-43ae-a2aa-af1bbfb47db4.jpg)

**Comment by xulihang** [comment]
You can use the manga balloon detection along with mangaOCR for such an image.

1. Download the balloon detection, put it under ImageTrans's folder and enable offline balloon detection in Preferences. Link: https://github.com/xulihang/ImageTrans-docs/issues/135#issuecomment-1015273831
2. Download, setup and start mangaOCR following this guide: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR

Then following the video to translate the image in steps:

https://user-images.githubusercontent.com/5462205/212531435-daac45b8-04c1-4e4f-88c0-91086fdce2e0.mp4

**Comment by jackneonatom** [comment]
i am not seeing manga ocr in the drop down list

**Comment by xulihang** [comment]
You have to the step four in the guide.

**Comment by jackneonatom** [comment]
is the part that says optional not really optional?

**Comment by jackneonatom** [comment]
i got everything to work sorry for all the whining, can i use this same method for other manga in the future

**Comment by xulihang** [comment]
It works for other manga as well.

**Comment by jackneonatom** [comment]
is there a way to manually draw the squares when the detection cant pick up the bubbles since when i use the tool on the side the square disappear when i draw them or cause the text in the area to disappear

**Comment by xulihang** [comment]
Do not check the "Translated" box.
