### ISSUE TITLE
java.lang.IndexOutOfBoundsException 自动ocr报错

### ISSUE THREAD

**Issue by RockQ** [xulihang/ImageTrans-docs#352]
error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr$ResumableSub_ocrspace.resume(ocr.java:3441)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by RockQ** [comment]
导入图片文件夹之后，点”自动识别“， 报错信息如下： 
![image](https://user-images.githubusercontent.com/586057/212826497-f0874ab5-76ec-4e3e-852e-861d7baec89f.png)
mac环境

**Comment by xulihang** [comment]
OCRSpace识别全图文字的效果不好，有时有结果有时没结果，可以换一个OCR。

**Comment by RockQ** [comment]
右键”一键翻译当前图片“，也会报这个问题， 用的baidu机翻
![image](https://user-images.githubusercontent.com/586057/212829741-9ecd1621-9394-4054-9de5-853ff33fa2cf.png)

**Comment by RockQ** [comment]
右键”一键翻译当前图片“，也会报这个问题， 用的baidu机翻
![image](https://user-images.githubusercontent.com/586057/212829741-9ecd1621-9394-4054-9de5-853ff33fa2cf.png)

**Comment by xulihang** [comment]
百度翻译每月的免费额度超了，也是要换一个机器翻译，比如cloudtranslation这些免费的
