### ISSUE TITLE
大大，图片过大的话好像没法将翻译后的字嵌入进去，有解决方法吗？

### ISSUE THREAD

**Issue by zjl1938685954** [xulihang/ImageTrans-docs#355]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:156)
	at org.xulihang.imagetrans.utils._appendsmallmask(utils.java:173)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4606)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4444)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4398)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7712)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7652)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16730)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16637)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:22439)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:22083)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 104396916 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:413)
	... 29 more

**Comment by xulihang** [comment]
之前有一个相关issue：https://github.com/xulihang/ImageTrans-docs/issues/258

**Comment by zjl1938685954** [comment]
感谢大大，问题已解决！



---原始邮件---
发件人: "Lihang ***@***.***&gt;
发送时间: 2023年1月29日(周日) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xulihang/ImageTrans-docs] 大大，图片过大的话好像没法将翻译后的字嵌入进去，有解决方法吗？ (Issue #355)




 
之前有一个相关issue：#258
