### ISSUE TITLE
Baidu Batch translation issue

### ISSUE THREAD

**Issue by nginius** [xulihang/ImageTrans-docs#357]
I am having this problem for some reason, i thought baidu was set up already

error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2597)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Are you using your own API key?

There are several reasons:

1. The free quota per month (1 million characters) has been reached.
2. You are requesting too frequently.

**Comment by nginius** [comment]
I think it was because i did not complete the batch translation cuz it was getting stuck at confidence level check, i think it is not compatible after like 100 pages for confidence level check, and also what do you recommend for text area detection instead of heuristic for manga

**Comment by xulihang** [comment]
There is a bug that the confidence checking gets stuck sometimes.

You can use balloon detection for manga.
