### ISSUE TITLE
在进行翻译之后出现的错误报告

### ISSUE THREAD

**Issue by lanyuntai** [xulihang/ImageTrans-docs#359]
![image](https://user-images.githubusercontent.com/76139797/217241376-1f4b55f2-9747-4db7-a9a0-7e99d053b691.png)

error: java.lang.ClassCastException: anywheresoftware.b4a.objects.collections.List cannot be cast to java.lang.String
StackTrace: java.lang.ClassCastException: anywheresoftware.b4a.objects.collections.List cannot be cast to java.lang.String
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:878)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

具体操作为：框选文字进行OCR——点击【辅助翻译】——出现错误报告——再次点击【辅助翻译】——没有出现错误报告，正常出现机翻

**Comment by xulihang** [comment]
开启了哪些机器翻译？可能是请求过频繁，超出了部分机器翻译的每秒请求限制

**Comment by lanyuntai** [comment]
> 开启了哪些机器翻译？可能是请求过频繁，超出部分机器翻译的每秒请求限制制
感谢回复，机翻选项开启了【百度】【腾讯】【mamemory】【cloudtranslation】【google】
那我尝试关闭几个试试看吧，看看是哪个出了问题
