### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by ghjghjbbj** [xulihang/ImageTrans-docs#362]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at anywheresoftware.b4j.object.JavaObject.RunMethodJO(JavaObject.java:139)
	at org.xulihang.imagetrans.cv2._bytestomat2(cv2.java:121)
	at org.xulihang.imagetrans.utils._png2cvmat(utils.java:3093)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7749)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7654)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16739)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16646)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:22450)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:22094)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgcodecs\src\loadsave.cpp:816: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'
]
	at org.opencv.imgcodecs.Imgcodecs.imdecode_0(Native Method)
	at org.opencv.imgcodecs.Imgcodecs.imdecode(Imgcodecs.java:547)
	... 26 more

**Comment by ghjghjbbj** [comment]
之前翻译的时候，前两页都还好，第三页的时候，点击最下端的查看翻译，就跳出上面那串东西，鼠标一直在转圈。重启软件，还是同样的情况

**Comment by ghjghjbbj** [comment]
> 光看错误信息看不出原因，能把项目文件和图片发过来吗

之前翻译的时候，前两页都还好，第三页的时候，点击最下端的查看翻译，就跳出上面那串东西，鼠标一直在转圈。重启软件，还是同样的情况

**Comment by xulihang** [comment]
把图片发我邮箱看看 admin@basiccat.org

**Comment by adogandtina** [comment]
有購買 ImageTrans 但開啟程式 輸入訂單號碼 以及郵箱號碼卻顯示未購買
怎麼解決?
