### ISSUE TITLE
Error when Batch > Batch traslation

### ISSUE THREAD

**Issue by Wosgo** [xulihang/ImageTrans-docs#367]
Hi there!

Tool works really well. It's great!

I think I found a problem when doing Project > Batch > Batch Translation.
It does all the steps: Get text area > OCRing 
But when it's going to start translation, occurs this error:

error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
StackTrace: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2597)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

However, when manually clicking on OCR button (with translate after OCR checked) it does it fine.
![image](https://user-images.githubusercontent.com/126430004/221450670-3c6c52d3-3032-442e-9e46-02f6f8d99be7.png)

The machine in both cases, was same (baidu).

Anyone know how to get it to work?

**Comment by xulihang** [comment]
The free monthly usage limit of baidu machine translation has been reached. You can use another machine translation like cloudtranslation and deeplfree.

**Comment by Wosgo** [comment]
Thanks! Changed to cloudtranslation, and its working fine. ^^
