### ISSUE TITLE
ImageTrans的服务器无法正常启动

### ISSUE THREAD

**Issue by Twice12450** [xulihang/ImageTrans-docs#378]
在启动服务器后点击重新链接，提示的是已断开
![1](https://user-images.githubusercontent.com/127361265/223884570-e572fabf-0ace-42e4-aa45-5eb2edae2dbe.png)
若点击关闭服务器则会报错，提示如下
error: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information
StackTrace: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: no further information
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at anywhersoftware.b4j.objects.WebSocketClientWrapper.SendText(WebSocketClientWrapper.java:123)
	at org.xulihang.imagetrans.websockethandler._sendeventtoserver(websockethandler.java:115)
	at org.xulihang.imagetrans.server._shutdownbutton_mouseclicked(server.java:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:351)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:185)
	at org.eclipse.jetty.io.ManagedSelector.access$1200(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:455)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:325)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	... 1 more

**Comment by xulihang** [comment]
因为没有启动，所以报错了。用的哪个版本？新版的服务器需要用1.9.1及以上版本启动

**Comment by Twice12450** [comment]
> 因为没有启动，所以报错了。用的哪个版本？新版的服务器需要用1.9.1及以上版本启动

你好，是1.9.2

**Comment by xulihang** [comment]
检测下软件目录下的ImageTrans_wsServer.jar文件的大小，应该有4点几兆，看看有没有下载完整

**Comment by xulihang** [comment]
正常启动的话应该可以访问这个地址：http://127.0.0.1:51042/translator

**Comment by Twice12450** [comment]
> 正常启动的话应该可以访问这个地址：http://127.0.0.1:51042/translator

ImageTrans_wsServer.jar文件大小4874KB，启动服务器会提示启动成功，但是一直提示已断开，这个连接也无法打开

**Comment by xulihang** [comment]
用命令行手动启动看看，会输出什么日志。

在软件目录按住shift后右键，选在此打开powsersell，然后执行下面的命令：

```
jre\bin\java -jar .\ImageTrans_wsServer.jar
```

**Comment by Twice12450** [comment]
> jre\bin\java -jar .\ImageTrans_wsServer.jar

jre\bin\java : 无法加载模块“jre”。有关详细信息，请运行“Import-Module jre”。
所在位置 行:1 字符: 1
+ jre\bin\java -jar .\ImageTrans_wsServer.jar
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jre\bin\java:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by xulihang** [comment]
命令不全，用这个再试试

```
.\jre\bin\java -jar .\ImageTrans_wsServer.jar
```

目录下是有jre目录的吧

**Comment by xulihang** [comment]
应该是系统的jre版本是1.8，运行不了最新的服务器。需要改用百度网盘的完整版或者下载这个[jre](https://github.com/bell-sw/Liberica/releases/download/11.0.18%2B10/bellsoft-jre11.0.18+10-windows-amd64-full.zip)，解压文件夹到ImageTrans并命名为jre

**Comment by Twice12450** [comment]
> 应该是系统的jre版本是1.8，运行不了最新的服务器。需要改用百度网盘的完整版或者下载这个[jre](https://github.com/bell-sw/Liberica/releases/download/11.0.18%2B10/bellsoft-jre11.0.18+10-windows-amd64-full.zip)，解压文件夹到ImageTrans并命名为jre

在把JRE文件夹放入软件目录后，软件仍然是启动后重新链接提示已断开，然后powersell内的返回内容是
PS E:\Tools\ImageTrans> .\jre\bin\java -jar .\ImageTrans_wsServer.jar
2023-03-10 22:42:00.627:INFO :oejs.Server:main: jetty-11.0.9; built: 2022-03-30T17:44:47.085Z; git: 243a48a658a183130a8c8de353178d154ca04f04; jvm 11.0.18+10-LTS
2023-03-10 22:42:00.721:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
2023-03-10 22:42:00.735:INFO :oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@5d534f5d{/,file:///E:/Tools/ImageTrans/,AVAILABLE}
2023-03-10 22:42:00.757:INFO :oejs.RequestLogWriter:main: Opened E:\Tools\ImageTrans\logs\b4j-2023_03_10.request.log
2023-03-10 22:42:00.992:INFO :oejs.AbstractConnector:main: Started ServerConnector@add0edd{HTTP/1.1, (http/1.1)}{0.0.0.0:51042}
2023-03-10 22:42:01.016:INFO :oejus.SslContextFactory:main: x509=X509@28cda624(1,h=[local.basiccat.org],a=[],w=[]) for Server@475c9c31[provider=null,keyStore=file:///E:/Tools/ImageTrans/certificate.jks,trustStore=null]
2023-03-10 22:42:01.083:INFO :oejs.AbstractConnector:main: Started ServerConnector@65466a6a{SSL, (ssl, http/1.1)}{0.0.0.0:51043}
2023-03-10 22:42:01.095:INFO :oejs.Server:main: Started Server@77847718{STARTING}[11.0.9,sto=0] @799ms

**Comment by xulihang** [comment]
配置应该是没问题了，把所有打开的都关掉，用imagetrans.bat启动软件后再启动服务器，点重新连接看看

**Comment by Twice12450** [comment]
> 配置应该是没问题了，把所有打开的都关掉，用imagetrans.bat启动软件后再启动服务器，点重新连接看看

重新试了下可以了，但是网页插件提示Bad result. Is ImageTrans running correctly?
这个是使用的网页不支持吗？如何判断网页是否支持？

**Comment by xulihang** [comment]
网址发给我看看

**Comment by Twice12450** [comment]
> 网址发给我看看

https://klmanga.su/

**Comment by xulihang** [comment]
这个网站有cdn保护，不支持
