### ISSUE TITLE
导回TXT的时候报错

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#384]
error: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
StackTrace: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.xulihang.imagetrans.main._importtxt(main.java:9444)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:12681)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:11835)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

https://user-images.githubusercontent.com/30548000/226305959-7648790b-df3c-436a-aa52-8020864cb070.mp4
第一页导入翻译的TXT报错
第二次掠过
第三次是切换到第二页的时候 导入第二页原始文本也报错
好像导入TXT这个功能 就会报错？
导出 原封不动的导入也报错？奇怪呢
我以为是编码问题 原来是 UTF8无签名
我改成UTFB 有签名也报错？

**Comment by lhj5426** [comment]
因为在使用浏览器直接打开TXT
变相的使用GPT来翻译txt

https://user-images.githubusercontent.com/30548000/226307578-b8ce1e7c-7ca6-4b11-b6c6-1d338647ca64.mp4

所以只能用txt格式 其他都不行

**Comment by xulihang** [comment]
文件发过来看一下

**Comment by lhj5426** [comment]
> 文件发过来看一下
视频里报错的TXT文件
[4567.zip](https://github.com/xulihang/ImageTrans-docs/files/11016546/4567.zip)
视频里使用的项目文件
[000123.zip](https://github.com/xulihang/ImageTrans-docs/files/11016551/000123.zip)
要图片文件吗？

**Comment by lhj5426** [comment]
> 怎么每个文件都有个txt。
> 
> 导入和导回只需要一个文件，是所有图片的内容都合并在一起的，就是导出时选择供翻译的文档。
> 
> 可以参考下之前这个用deepl翻译的issue：[#15 (comment)](https://github.com/xulihang/ImageTrans-docs/issues/15#issuecomment-1030087909)

我导出的时候点的这个
![image](https://user-images.githubusercontent.com/30548000/226342615-d3b36122-75aa-4795-9255-c2bdee764576.png)
就是选择文件夹然后一堆TXT 每一页一个TXT
您说导入就一个TXT 我不知道怎么做

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/226345195-3b2f2fb8-2202-41bc-91f0-7e6a26de2df6.png)

![image](https://user-images.githubusercontent.com/30548000/226345413-d2de66b4-45e9-4a66-a5e5-4656a0413aa1.png)

![image](https://user-images.githubusercontent.com/30548000/226345607-b4365ac7-a1ea-4459-a842-b135756a3de2.png)

因为全部导出 这几个我都试过了 觉得 导出所有文本一个 图片一个文本文件 这样文本量不大

用浏览器GPT翻译也比较快
所以我选择了这个方式 

结果 这个方式 居然是 无法倒回的？

是这样吗

**Comment by lhj5426** [comment]
还有导出来的时候希望是有签名的UTF8编码格式
![image](https://user-images.githubusercontent.com/30548000/226346901-a7f8a089-17d0-4257-8aa5-8c8418033d1c.png)
无签名的UTF8 浏览器打开直接乱码
![image](https://user-images.githubusercontent.com/30548000/226346995-11b26e97-a55f-4e70-ae16-3c16b299142b.png)

**Comment by lhj5426** [comment]
其实这么折腾 还不如您 抽空开发下 直接 用CHATGPT翻译插件来的舒服
我这都是全部都是折中的妥协办法 
![image](https://user-images.githubusercontent.com/30548000/226347859-55c2555d-e176-41a4-ae4d-89b3ac4fdc0a.png)

**Comment by xulihang** [comment]
建议的方法是导出成docx文档再导回，见我上面发的issue的链接
