### ISSUE TITLE
Add Yandex Machine Translation

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#386]
https://cloud.yandex.com/en/docs/translate/operations/translate

**Comment by xulihang** [comment]
Unzip the plugin files into ImageTrans' plugins folder to use yandex translate: 

[yandexMT.zip](https://github.com/xulihang/ImageTrans-docs/files/11068917/yandexMT.zip)


Source code: https://github.com/xulihang/ImageTrans_plugins/tree/master/yandexMT

**Comment by xulihang** [comment]
OAuth token and folder ID are required to be set in the preferences.

**Comment by Ilardar** [comment]
I put the files in the plugins folder, restart the program, but it did not appear in the Yandex settings.
v1.9.2
![2023-03-25_17-57-02](https://user-images.githubusercontent.com/23218393/227724999-2a8b4a10-417e-47c3-b225-c1b36480e959.png)

**Comment by Ilardar** [comment]
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.ab.abplugin.ABPlugin.RunInitialize(ABPlugin.java:143)
        at com.ab.abplugin.ABPlugin.access$5(ABPlugin.java:136)
        at com.ab.abplugin.ABPlugin$1.run(ABPlugin.java:119)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void anywheresoftware.b4a.keywords.Common.LogImpl(java.lang.String, java.lang.String, int)'
        at org.xulihang.imagetrans.yandexmtplugin._initialize(yandexmtplugin.java:379)
        ... 13 more
plugins have changed!
(ArrayList) [cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, ExternalInpaint, ExternalMaskGen, google_driveOCR, googleMT, googleOCR, manga-ocrOCR, niutransMT, opusMT, paddleocrOCR, papagoMT, tencentOCR, webMT, WinRTOCR]
```

**Comment by xulihang** [comment]
Are you using the crossplatform version? Try this version which is compiled using an older version of the B4J programming tool: 
[yandexMT.zip](https://github.com/xulihang/ImageTrans-docs/files/11069264/yandexMT.zip)

**Comment by Ilardar** [comment]
No, I'm using the version fome OneDrive, thank you, everything is working now, great news!
