### ISSUE TITLE
进行嵌字的时候突然弹出这个窗口，如何解决？

### ISSUE THREAD

**Issue by zjl1938685954** [xulihang/ImageTrans-docs#394]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:219)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1187)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:4604)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4444)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4398)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:7714)
	at org.xulihang.imagetrans.main._gentextmask(main.java:7654)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:16739)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:16646)
	at org.xulihang.imagetrans.main._precisionmodecheckbox_checkedchange(main.java:16067)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
	at anywheresoftware.b4a.BA$1.run(BA.java:236)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3868)
	... 28 more

**Comment by zjl1938685954** [comment]
就是生成，编辑文字掩膜那里没法工作

**Comment by xulihang** [comment]
检查下有没有尺寸错误的文本框，比如宽度和高度为负数的，可以在右侧的文本框列表里查找

**Comment by zjl1938685954** [comment]
> 检查下有没有尺寸错误的文本框，比如宽度和高度为负数的，可以在右侧的文本框列表里查找

已解决，确实有一个文本框有问题
