### ISSUE TITLE
TXT文本导回报错 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#412]
[final.txt.zip](https://github.com/xulihang/ImageTrans-docs/files/11500521/final.txt.zip)
项目文件 原文 译文 都打包到这个文件里了 是一个1104页的漫画

这是报错内容
error: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
StackTrace: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.xulihang.imagetrans.main._importtxt(main.java:9970)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:13207)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:12339)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

麻烦老哥给看看是因为什么 哪里出现了问题 
买了120刀的账号 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/14c8dc27-6963-4bd6-9f78-c183c7127b38)

跑了10%了 都没搞明白

**Comment by lhj5426** [comment]
现在TXT的格式是
原文 一个TAB分割 译文
太容易报错了
能不能请您考虑下改成 
直接就译文就能导入
不需要再跟着原文 这样太乱了
只要导入导出的TXT行数对应上就能导入
就像一个普通的一行一句话的TXT文本

**Comment by xulihang** [comment]
我看了下是204行没有制表符导致的错误

**Comment by lhj5426** [comment]
> 我看了下是204行没有制表符导致的错误

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bf80fdbf-18d5-4f04-8de4-44594a1203ee)

好像不是？

**Comment by xulihang** [comment]
我考虑新版加一个错误提示，提示是不是行数不匹配，原文不匹配，或者哪行格式不对，没有制表符

**Comment by lhj5426** [comment]
> 我考虑新版加一个错误提示，提示是不是行数不匹配，原文不匹配，或者哪行格式不对，没有制表符

很人性化的提示 感觉会比现在 跟无头苍蝇 找不到出错地方强 只知道错了但是不知道哪错了

不过 感觉还是不要原文原文 只要译文 能好点 不乱

虽然您的本意是 原文 译文对照 对于翻译的工作可能方便一些
但是目前来看 对于导入来说是灾难
特别是用GPT跑完再搞回 译文 TAB 原文
这种格式 行数少还行 这几千行 说真的 有点不太行
或者
或者更通用一点 表格 现在 您开发的 ImageTrans 是支持导出表格的但是导出的表格 。。。
内容太多了 而且无法倒回
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c5b7d19c-ed74-452f-9ad7-269ffcb130fb)
对于用户来说 前边的所有数据都没啥用 真的至少我用了您软件1年半以上 我是真用不到这个数据 我想很多人用不到这个数据
当然也数据也是有用的比如导出PSD 但是导出PSD会生成一个独立的txt所以感觉这个表格导出的数据太多了有点不实用
您看表格一格 一格的 一行原文 一行译文
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1ee3b063-f04e-4b45-a756-bf6b49ed5a3b)

这样也不乱 也好对照 那个可以把导出的表格精简一下吗
  成 第一行原文 第二行 译文 这样导入导出 对照也方便错了也知道哪错了

那些位置什么的 其实没啥大必要  个人拙见 而且 如果从翻译的数据库导出
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8bb99cf0-3f74-46a5-bce4-b3e52ae1ffb1)
然后 导入也方便
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2e8ad164-b506-48b0-9d6e-a4c29385add8)

**Comment by xulihang** [comment]
目前导出的TXT也是可以用excel管理的，可以移除原文列，就是需要注意编码问题

**Comment by lhj5426** [comment]
> 目前导出的TXT也是可以用excel管理的，可以移除原文列，就是需要注意编码问题

导回好像不行吧  表格

**Comment by xulihang** [comment]
excel可以保存为制表符分隔的txt文件，然后可以导回了

**Comment by lhj5426** [comment]
> excel可以保存为制表符分隔的txt文件，然后可以导回了

咦   我去研究研究

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b2a6e3e6-0c89-4357-9f71-5dec76355495)
试了下确实 表格导出TXT 可以导回 确实 只要有提示哪里出问题了就行 是我愚昧了

**Comment by xulihang** [comment]
关于TXT导入错误的提示添加在v1.9.8了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/aaa5d428-c2f3-4fae-8bac-9ec849328409)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/494e0ba7-419e-4347-bc26-c752a7316a36)

牛逼plus  还真是204 我把204整个删掉瞎写就导入了 之前只复制粘贴原文然后 复制粘贴下那个制表符号 导入还是报错
这次直接删掉下次就进去了 太牛逼了
