### ISSUE TITLE
Error when setting lamainpaint as default

### ISSUE THREAD

**Issue by dnr111222** [xulihang/ImageTrans-docs#414]
https://github.com/xulihang/ImageTrans-docs/assets/42793507/4019c748-9b54-41fc-87e1-c181a629c3fd

error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]

StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]
	at org.opencv.core.Core.addWeighted_1(Native Method)
	at org.opencv.core.Core.addWeighted(Core.java:1038)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._addweighted(cv2.java:70)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2487)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Lama inpaint's output resolution has a limit. 

I've fixed this by updating the plugin. Try to use the new plugin: https://github.com/xulihang/ImageTrans-docs/issues/216#issuecomment-1140435018

You can also enable processing by text area to fix this error.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/82d85956-6ab1-4a1b-acea-3e31934cf99c)

**Comment by Flowfo** [comment]
Hello,
I wanted to try lama plugin. I have installed one click windows installer.
All worked well, started the server but when using ImageTrans, I have no result and the server displays "POST/ inpaint http/1.1" 400
![image](https://github.com/xulihang/ImageTrans-docs/assets/48133323/730aa681-ebff-468b-a576-2358e0269826)
Would you know where is the problem?

**Comment by xulihang** [comment]
It seems that you are using Lama-cleaner 1.2.5. You have to download the updated plugins here: https://github.com/xulihang/ImageTrans_plugins/tree/master/LamaInpaint
