### ISSUE TITLE
The application doesn't start

### ISSUE THREAD

**Issue by Okabetv** [xulihang/ImageTrans-docs#416]
I recently purchased a copy of imagetrans, but when I click on the .exe file to start it, nothing happens... can you help me?

**Comment by Okabetv** [comment]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:796)
	at org.xulihang.imagetrans.mt._getmt(mt.java:601)
	at org.xulihang.imagetrans.main$ResumableSub_showMT.resume(main.java:21079)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
