### ISSUE TITLE
这个是什么错误

### ISSUE THREAD

**Issue by xitele2036** [xulihang/ImageTrans-docs#417]
error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.AddAll(List.java:80)
	at org.xulihang.imagetrans.silenttranslatorhelper._loadresultstoproject(silenttranslatorhelper.java:230)
	at org.xulihang.imagetrans.silenttranslatorhelper$ResumableSub_TranslateOne.resume(silenttranslatorhelper.java:541)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
执行什么操作时出现的？

**Comment by 07Nick-kciN21** [comment]
我用百度翻譯也跳這個錯誤

**Comment by gillian966** [comment]
出现的是同样的错误，也是百度翻译

**Comment by xulihang** [comment]
静默翻译助手的这个问题，v2.4.1修复了
