### ISSUE TITLE
请教一下api功能的使用方式

### ISSUE THREAD

**Issue by ywkf** [xulihang/ImageTrans-docs#421]
你好，我的api好像无法起作用
使用ChatGPT“翻译中……”对话框出现几秒后就消失无事发生，使用DeepL会报错：
error: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
StackTrace: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:2715)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
请教一下这个问题怎么解决

**Comment by ywkf** [comment]
openai api 连接超时，但是clash全局模式其他软件是可以连接的啊

**Comment by xulihang** [comment]
clash我没用过，之前的用户用clash是可以的：https://github.com/xulihang/ImageTrans-docs/issues/375#issuecomment-1479681558
