### ISSUE TITLE
改字体颜色报错

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#426]
error: java.lang.RuntimeException: Object should first be initialized (Image).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Image).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at org.xulihang.imagetrans.imgcolorpicker._initialize(imgcolorpicker.java:160)
	at org.xulihang.imagetrans.projectsettings._pickcolorandfillimage(projectsettings.java:1551)
	at org.xulihang.imagetrans.projectsettings._fontcolorcanvas_mouseclicked(projectsettings.java:687)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ClickGenerator.postProcess(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ClickGenerator.access$8200(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
项目和图片发过来看一下

**Comment by sera1991** [comment]
好吧我懂了，只能手动取色不能RGB调色，没图片就会报错。。

**Comment by xulihang** [comment]
需要的话我再加个调色板
