### ISSUE TITLE
manga-ocr打开闪退

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#437]
D:\1.9.7\manga-ocr-python3.9>Python39\python server_manga_ocr.py
2023-06-17 23:43:34.376 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
Traceback (most recent call last):
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\1.9.7\manga-ocr-python3.9\server_manga_ocr.py", line 34, in <module>
    mocr = MangaOcr()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\manga_ocr\ocr.py", line 14, in __init__
    self.feature_extractor = AutoFeatureExtractor.from_pretrained(pretrained_model_name_or_path)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\models\auto\feature_extraction_auto.py", line 163, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\models\auto\configuration_auto.py", line 582, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\configuration_utils.py", line 552, in get_config_dict
    configuration_file = get_configuration_file(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\configuration_utils.py", line 843, in get_configuration_file
    all_files = get_list_of_files(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\file_utils.py", line 2103, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\huggingface_hub\hf_api.py", line 884, in list_repo_files
    info = self.model_info(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\huggingface_hub\hf_api.py", line 867, in model_info
    r = requests.get(path, headers=headers, timeout=timeout)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
KeyboardInterrupt

之前还好好的，今天一打开就闪退了，重新解压了还是一样。。

**Comment by sera1991** [comment]
不知道为什么Python3810版本的有时能用有时闪退的，难道和代理有关吗。那个Python39的倒是一直闪退。


D:\1.9.7\manga-ocr-python3.9>Python39\python server_manga_ocr.py
2023-06-18 00:12:42.787 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
Traceback (most recent call last):
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

**Comment by xulihang** [comment]
有使用我提供的离线模型吗？用本地模型应该可以避免联网的问题。

**Comment by sera1991** [comment]
装了离线模型但python39这个还是闪退。。。

D:\1.9.7\manga-ocr-python3.9>Python39\python server_manga_ocr.py
2023-06-18 12:07:00.309 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
Traceback (most recent call last):
  File "D:\1.9.7\manga-ocr-python3.9\server_manga_ocr.py", line 34, in <module>
    mocr = MangaOcr()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\manga_ocr\ocr.py", line 14, in __init__
    self.feature_extractor = AutoFeatureExtractor.from_pretrained(pretrained_model_name_or_path)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\models\auto\feature_extraction_auto.py", line 163, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\models\auto\configuration_auto.py", line 582, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\configuration_utils.py", line 552, in get_config_dict
    configuration_file = get_configuration_file(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\configuration_utils.py", line 843, in get_configuration_file
    all_files = get_list_of_files(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\transformers\file_utils.py", line 2103, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\huggingface_hub\hf_api.py", line 884, in list_repo_files
    info = self.model_info(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\huggingface_hub\hf_api.py", line 867, in model_info
    r = requests.get(path, headers=headers, timeout=timeout)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\1.9.7\manga-ocr-python3.9\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
^C终止批处理操作吗(Y/N)?

**Comment by xulihang** [comment]
没有应用成功，还是在使用在线的。

3.8的有问题吗

**Comment by sera1991** [comment]
> 没有应用成功，还是在使用在线的。
> 
> 3.8的有问题吗
Python3810的可以，但好像没调用离线缓存。。

D:\1.9.7\manga-ocr>.\Python3810\python.exe .\server_manga_ocr.py
2023-06-18 12:23:45.449 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
2023-06-18 12:24:48.635 | INFO     | manga_ocr.ocr:__init__:22 - Using CPU
2023-06-18 12:24:49.306 | INFO     | manga_ocr.ocr:__init__:29 - OCR ready
Bottle v0.12.19 server starting up (using PasteServer())...
Listening on http://0.0.0.0:7272/
Hit Ctrl-C to quit.

serving on 0.0.0.0:7272 view at http://127.0.0.1:7272

**Comment by sera1991** [comment]
好像可以用了，这是用得离线缓存吗

D:\1.9.7\manga-ocr-python3.9>Python39\python server_manga_ocr.py
2023-06-18 12:34:30.380 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
2023-06-18 12:34:42.506 | INFO     | manga_ocr.ocr:__init__:22 - Using CPU
2023-06-18 12:34:43.462354: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-06-18 12:34:43.462870: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-06-18 12:34:50.778 | INFO     | manga_ocr.ocr:__init__:26 - OCR ready
Bottle v0.12.19 server starting up (using PasteServer())...
Listening on http://0.0.0.0:7272/
Hit Ctrl-C to quit.

serving on 0.0.0.0:7272 view at http://127.0.0.1:7272
.jpg
127.0.0.1 - - [18/Jun/2023:12:36:38 +0800] "POST /ocr HTTP/1.1" 200 33 "-" "okhttp/3.12.12"
.jpg
127.0.0.1 - - [18/Jun/2023:12:36:45 +0800] "POST /ocr HTTP/1.1" 200 18 "-" "okhttp/3.12.12"

——————————————————————————————————
刚用VS code打开py文件显示
Import "manga_ocr" could not be resolved
Import "bottle" could not be resolved
这两个问题，然后我把这两个报给gpt
检查所需库是否已安装：确保在您的Python环境中已安装了"manga_ocr"和"bottle"库。您可以使用以下命令使用pip安装它们：
pip install manga_ocr bottle
然后就好了。。

**Comment by xulihang** [comment]
你给本地Python装的和我打包的Python是两个Python环境，手动安装mangaocr和bottle不影响我打包的环境。

照[这里](https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR)的说明下载两个zip包解压后，运行结果是这样的：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/d12210b7-fda5-466b-9d90-cde831dae8a6)

**Comment by sera1991** [comment]
3810和39都能正常运行了
不过39会显示这个
```
2023-06-18 13:17:12.207 | INFO     | manga_ocr.ocr:__init__:22 - Using CPU
2023-06-18 13:17:13.038886: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-06-18 13:17:13.039004: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```
而3810就不会...似乎是和GPU有什么关系
话说39比3810大了三倍，是更新了什么重要的东西吗。github给的是3810云盘里是39。

**Comment by xulihang** [comment]
没有什么差别，是我打包3.9的时候多打包了些不必要的包
