### ISSUE TITLE
error: java.lang.ClassCastException

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#442]
error: java.lang.ClassCastException: class java.lang.String cannot be cast to class anywheresoftware.b4a.objects.collections.List (java.lang.String is in module java.base of loader 'bootstrap'; anywheresoftware.b4a.objects.collections.List is in unnamed module of loader 'app')
StackTrace: java.lang.ClassCastException: class java.lang.String cannot be cast to class anywheresoftware.b4a.objects.collections.List (java.lang.String is in module java.base of loader 'bootstrap'; anywheresoftware.b4a.objects.collections.List is in unnamed module of loader 'app')
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2890)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
不知道这个应该怎么处理，下载的是网盘里面的

**Comment by xulihang** [comment]
全图文字识别没有结果，可以换一个OCR或者改用它识别单个文字区域
