### ISSUE TITLE
无法使用gpt翻译

### ISSUE THREAD

**Issue by sssandclannad** [xulihang/ImageTrans-docs#450]
我这边开着全局代理和使用proxifier进行代理都无法连接到GPT服务器
进行GPT翻译时的错误代码如下
javax.net.ssl.SSLPeerUnverifiedException: Hostname api.openai.com not verified:
    certificate: sha256/n8udAlk2iybTF/N9UErsbxZH41DN0g4eWowCReAu7GQ=
    DN: CN=t.co, O="Twitter, Inc.", L=San Francisco, ST=California, C=US
    subjectAltNames: [t.co, www.t.co]
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:334)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at anywheresoftware.b4h.okhttp.OkHttpClientWrapper.executeWithTimeout(OkHttpClientWrapper.java:173)
        at anywheresoftware.b4h.okhttp.OkHttpClientWrapper.access$0(OkHttpClientWrapper.java:170)
        at anywheresoftware.b4h.okhttp.OkHttpClientWrapper$ExecuteHelper.run(OkHttpClientWrapper.java:218)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
ResponseError. Reason: javax.net.ssl.SSLPeerUnverifiedException: Hostname api.openai.com not verified:
    certificate: sha256/n8udAlk2iybTF/N9UErsbxZH41DN0g4eWowCReAu7GQ=
    DN: CN=t.co, O="Twitter, Inc.", L=San Francisco, ST=California, C=US
    subjectAltNames: [t.co, www.t.co], Response:
pluginMT

代理软件提示是这样的
![image](https://github.com/xulihang/ImageTrans-docs/assets/71596718/af31d1be-5d36-49a7-b09f-a52d5233563b)
有大佬知道怎么解决吗

**Comment by xulihang** [comment]
可能是代理用的证书不是签名的证书，没办法通过验证

**Comment by xulihang** [comment]
用这个插件文件试一下，解压到plugins目录里。我把证书验证关闭了
[ChatGPT_plugins.zip](https://github.com/xulihang/ImageTrans-docs/files/11926061/ChatGPT_plugins.zip)
