### ISSUE TITLE
发生报错

### ISSUE THREAD

**Issue by chencxt** [xulihang/ImageTrans-docs#451]
在最新版的软件中，导入了其他项目中的字体样式，在开启“查看翻译”选项时，发生如下报错：

error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:769: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'cv::Mat::Mat'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:769: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'cv::Mat::Mat'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:127)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.InitializeNewInstance(JavaObject.java:91)
	at org.xulihang.imagetrans.cvmat._initialize(cvmat.java:120)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2392)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:2147)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:19287)
	at org.xulihang.imagetrans.main._removetext(main.java:19224)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:17320)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
用了manga-translator吗？我估计是生成的掩膜和原图的尺寸不匹配导致的，可以把项目里的mask.png结尾的图片都删了再试一下

**Comment by chencxt** [comment]
好了，原来是这样。多谢大大

**Comment by xulihang** [comment]
这个问题在2.0.0修复了
