### ISSUE TITLE
lama-cleaner problems.

### ISSUE THREAD

**Issue by godperkys** [xulihang/ImageTrans-docs#456]
Hey im facing some troubles with the lama-cleaner and im not sure what causes it. 

I either try to use the cleaner with the InPaint feature or TextRemover where both of them are working very badly or not at all. ive tried to use the same thing on the web and the results are way better!

If i use it inside the program with InPaint i face this error and nothing happens or i get very bad results.
![screenshot1](https://github.com/xulihang/ImageTrans-docs/assets/80337080/1e3ee43b-0728-454c-98fe-068bfdcc7d80)

```
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_win
pack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]
	at org.opencv.core.Core.addWeighted_1(Native Method)
	at org.opencv.core.Core.addWeighted(Core.java:1038)
	at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._addweighted(cv2.java:70)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2616)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

If i use it with Text Remover i get results like these (these fat lines you see over "floating text" are a issue in InPaint aswell): 
![Anmerkung 2023-07-04 222226](https://github.com/xulihang/ImageTrans-docs/assets/80337080/d8c586ed-c9b8-4c4c-9ad3-c72320edaa32)

and here are results i get with the web version of it. 
![2 rawkuma com_cleanup](https://github.com/xulihang/ImageTrans-docs/assets/80337080/93056c5d-5f38-47c3-8c5e-04de32f0c839)

I have tried to play with various settings on all the features but nothing really did anything. I saw great results with these plugins on other posts here so it must work somehow.

Thanking for help in advance!

**Comment by xulihang** [comment]
The reason of the difference between the web version and ImageTrans' should be the mask. The image is not very clean. You have to set the dilation kernel size to a larger value. Meanwhile, it is better to enable process by text areas for lama inpaint as its supported resolution is limited.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/06daafee-4779-4702-a958-a4eb2764cc53)

**Comment by xulihang** [comment]
In addition, you have to make sure that the text box contains the entire text.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/01959148-9850-46bc-8fef-a88f5fd09f7b)

**Comment by godperkys** [comment]
> About the error, when did you download the plugin? I've updated the plugin on May 21st to solve this problem: [#216 (comment)](https://github.com/xulihang/ImageTrans-docs/issues/216#issuecomment-1140435018)

After testing a bit it worked fine, but i sometimes run into the error randomly and im not sure why. I do 10 pages and it works fine and then randomly 1 wont work. 

![image](https://github.com/xulihang/ImageTrans-docs/assets/80337080/8efca5da-0f15-4f96-a677-f90fcf16b636)

These are my plugin files. If i dont use these XML and jar files the plugin wont show up so im not sure if they are the problem.

**Comment by xulihang** [comment]
They are an old version. The latest version is updated on 5.21.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/2d3e6e26-a954-4fcc-8830-133914226c6d)

Using the latest version should solve the problem: https://github.com/xulihang/ImageTrans-docs/files/11524718/lama_inpainting_plugin.zip
