### ISSUE TITLE
翻译文本时报错

### ISSUE THREAD

**Issue by 386wai** [xulihang/ImageTrans-docs#480]
error: java.io.FileNotFoundException: C:\Users\386歪\AppData\Local\Temp\14 (拒绝访问。)
StackTrace: java.io.FileNotFoundException: C:\Users\386��\AppData\Local\Temp\14 (�ܾ����ʡ�)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
需要在偏好设置里设一下网络文件临时文件夹，随便一个文件夹就行。

参见：https://github.com/xulihang/ImageTrans-docs/issues/218

**Comment by 386wai** [comment]
了解
