### ISSUE TITLE
Manage original images without text and pure-text images

### ISSUE THREAD

**Issue by ocrhell** [xulihang/ImageTrans-docs#487]
Can I get exact steps on how to use the "-original" suffix for textless images? This is what I'm doing:

- Create project
- Import images with text through software
- Save project
- Copy textless images to same folder with "-original"
- Go to "Manage original images without text and pure-text images"

Are these the correct steps? If so, the software gives me this error.

```
error: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
StackTrace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocate(Unknown Source)
	at javafx.graphics/com.sun.javafx.iio.png.PNGImageLoader2.load(Unknown Source)
	at javafx.graphics/com.sun.javafx.iio.ImageStorage.loadAll(Unknown Source)
	at javafx.graphics/com.sun.javafx.iio.ImageStorage.loadAll(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PrismImageLoader2.loadAll(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PrismImageLoader2.<init>(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.loadImage(Unknown Source)
	at javafx.graphics/javafx.scene.image.Image.loadImage(Unknown Source)
	at javafx.graphics/javafx.scene.image.Image.initialize(Unknown Source)
	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
	at anywheresoftware.b4j.objects.ImageViewWrapper$ImageWrapper.Initialize2(ImageViewWrapper.java:146)
	at anywheresoftware.b4j.objects.ImageViewWrapper$ImageWrapper.Initialize(ImageViewWrapper.java:139)
	at anywheresoftware.b4j.objects.JFX.LoadImage(JFX.java:163)
	at org.xulihang.imagetrans.main._showbackgroundremover(main.java:21976)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:15083)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:12985)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$59/0x00000001000e5040.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$58/0x00000001000e5c40.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication$$Lambda$47/0x00000001000e0c40.run(Unknown Source)
```

Do I also need to import the textless images through the software too? I'm confused.

**Comment by xulihang** [comment]
What do you want to achieve?

You can use the manager to set the original images and create the pure text images, or put the image with the suffix directly.

```
image.jpg
image.jpg-original.jpg
image.jpg-puretext.jpg
image.jpg-mask.png
image.jpg-text-removed.png
```

The original image will be used viewing the translated version instead of the text-removed image.

The pure text image will be used for OCR.

**Comment by xulihang** [comment]
Which step gives the OutOfMemory error? Maybe the image is too large.

**Comment by ocrhell** [comment]
I want to use the textless images as the base for the images with text. So when I check "Translated", I expect to see the translated text appearing over the textless image.

I have put the images this way in the same folder 
```
image.jpg
image.jpg-original.jpg
```
but when I check "Translated", it creates a mask for the image containing text which tells me it is not using the textless image.

Do I need to "Import -> pictures (from folder)" for the textless images as well?

I get the OutOfMemory error on the final step: "Manage original images without text and pure-text images". Strangely though, this happens when running the software through the batch file. It works fine on the application file.
