### ISSUE TITLE
遇到了新的残影bug

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#493]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/67bec65b-c5ca-4f5a-bc7e-2545c8e089dc

如视频所示那样 无论是上一页 还是下一页 翻页 会一直出现残影

怎么触发的 ？

在开启翻译的情况下
疯狂的连续点击上一页 就突然 卡出残影bug 了
我本来是想往上翻几页找到 之前 设置的也外置字体的大小看一下
结果 就着急的疯狂点击上一页 就出现了这个bug
不知道开发者老哥 能不能在你那边复现 并修复

**Comment by xulihang** [comment]
你这个点击这么快我还真没测过，可能是会有图片切换不及时的问题。残影看着是半透明的，你设置透明度了吗。右键刷新后还会有残影吗？需要快速切换的话我可以加一个动画功能，保证图片加载完成后再切换。

**Comment by lhj5426** [comment]
> 你这个点击这么快我还真没测过，可能是会有图片切换不及时的问题。残影看着是半透明的，你设置透明度了吗。右键刷新后还会有残影吗？需要快速切换的话我可以加一个动画功能，保证图片加载完成后再切换。

设置透明度了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/dfcfedb1-a802-4fd1-bd52-2e7f03b55307)
我一般开 75 ~85的透明度来对齐气泡的文字

其实页面文字多的时候 每按一下翻页 有时候译文 出来的会有点延迟
然后 这个延迟+快速翻页 就触发了这个bug 
然后就只能关闭软件重新打开 才能恢复

**Comment by lhj5426** [comment]
触发bug的时候会先有一个报错

error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:778: error: (-215:Assertion failed) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function 'cv::Mat::Mat'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:778: error: (-215:Assertion failed) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function 'cv::Mat::Mat'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:127)
	at jdk.internal.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.InitializeNewInstance(JavaObject.java:91)
	at org.xulihang.imagetrans.cvmat._initialize(cvmat.java:121)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2497)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:2277)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:20383)
	at org.xulihang.imagetrans.main._removetext(main.java:20320)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:18414)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
那个报错应该是生成去文字字图时的错误，哪个文本框的位置不对。先生成一遍去文字图，切换的速度会快一点。

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/35ac10a8-a574-42a3-b558-61b1d3847fe4)
关键是去文字图我大部分是手动生成的
PS 新增了一个 移除工具 虽然AI 用不了了 但是这个移除工具真的很好用 
像现在做的这个漫画
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/725e5df8-8279-4009-a4dd-60302acbd23c)
气泡经常 被破坏的乱七八糟
如果用软件修 因为要修的地方小 所以需要开放大镜 感觉麻烦就直接丢PS里去搞了 
所以没办法 批量生成 哈哈 我是润一张 气泡有问题 就PS里修一张 然后改名 删除拷贝字原名+-original.jpg 丢到原图目录里一张

**Comment by xulihang** [comment]
翻译模式下切换图片，如果去文字图没有生成，会花一定时间去处理，所以不能快速切换。这种情况需要快速切换的话，可以把精确文字抹除的选项关闭。

暂时没有别的解决办法。
