### ISSUE TITLE
Mac版本打不开

### ISSUE THREAD

**Issue by RLLSK** [xulihang/ImageTrans-docs#501]
把最新版2.5.3的arm dmg拖到了app文件夹里，也在显示损坏的时候在终端输入好了代码，但是打开以后没有任何界面出现，图标闪了两下就闪退了。不知道是什么情况。

**Comment by RLLSK** [comment]
会不会是因为我电脑没装java啊

**Comment by xulihang** [comment]
什么型号的mac，cpu和系统是什么？arm版我在m2的mac mini上测是没问题的。不行的话用x64版吧

**Comment by RLLSK** [comment]
M1, Big Sur 11.4

**Comment by xulihang** [comment]
用x64版吧，arm版我在macOS 13.4上编译的，可能旧版本的系统有兼容问题

**Comment by RLLSK** [comment]
绷不住了，好不容易打开了发现自己没存单号，怎么办啊，网页关掉了已经

**Comment by xulihang** [comment]
FastSpring的话在邮件里能找到，面包多的话在付费页面能找到订单号

**Comment by RLLSK** [comment]
<img width="1022" alt="Screen Shot 2023-10-13 at 11 21 40 AM" src="https://github.com/xulihang/ImageTrans-docs/assets/147673224/85c2a9ed-be0b-48dd-a139-1680652f8d72">
不知道为啥点了ocr以后不翻译，是识别不出来吗？

**Comment by xulihang** [comment]
tesseract需要自己安装。日漫推荐用mangaocr，也需要要自己安装，mac要麻烦一点，不像windows我有提供打包好的版本。日漫ocr比较好的直接可用的是google drive, ocrspace和baidu accurate

**Comment by xulihang** [comment]
具体说明文档里有

**Comment by RLLSK** [comment]
我看到了，不好意思。但我是电脑白痴。。请问装完Python以后还需要pip3 install manga-ocr吗，还是直接在终端pip install -r requirements.txt

**Comment by xulihang** [comment]
用macOS自带的Python3是可以的。执行`pip3 install -r requirements.txt`安装依赖，再运行`python3 server_manga_ocr.py`就行了

**Comment by RLLSK** [comment]
我输入了以后是这么回复的：
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/usr/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/__init__.py)
之前Python是根据manga ocr里M1苹果的workaround安装的：https://github.com/kha-white/manga-ocr/issues/16
我也不知道成功没有，只是把代码复制进终端了...
不好意思真是给您添麻烦了。

**Comment by xulihang** [comment]
这是执行什么命令时报错的？我没碰到过

**Comment by RLLSK** [comment]
pip3 install -r requirements.txt

**Comment by xulihang** [comment]
应该是pip的安装有问题，可以参考网上的文章：https://www.bilibili.com/read/cv13360248/

**Comment by xulihang** [comment]
我打包了mac版本的mangaOCR：https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/mangaOCR.dmg
