### ISSUE TITLE
manga-image-translator可以加上cuda吗？

### ISSUE THREAD

**Issue by jsihao2000** [xulihang/ImageTrans-docs#502]
manga-image-translator 可以加上cuda吗，看原版是有这个功能的，会快很多啊，目前其他的选文字方法都不太准确

**Comment by xulihang** [comment]
需要把pytorch换成cuda版本。可以自己安装python环境或者直接用我提供的打包好的版本，把里面的pytorch换成cuda版的。我没有n卡的电脑，没办法测试

**Comment by lhj5426** [comment]
其实我也有这个疑问哈哈
之前 用 manga-ocr 跑cuda 很爽

**Comment by xulihang** [comment]
写了个说明在这里：https://github.com/xulihang/ImageTrans_plugins/blob/master/mangaTranslatorOCR/GPU.md

**Comment by lhj5426** [comment]
> 写了个说明在这里：https://github.com/xulihang/ImageTrans_plugins/blob/master/mangaTranslatorOCR/GPU.md

我和GPT都没看懂
编辑 Python\Scripts\pip.exe and replace e:\python3810\python.exe 到 python.exe。
老哥这个是啥意思啊

**Comment by xulihang** [comment]
乱码不要紧，需要更改的部分不是乱码

**Comment by lhj5426** [comment]
> 乱码不要紧，需要更改的部分不是乱码

我去

> 乱码不要紧，需要更改的部分不是乱码

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fef917c5-5bef-430b-90fa-44957977a35d)
是替换成这样吗
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a70fa63f-2125-4a34-aa94-22647f7a2e65)
打开看到乱码就没敢再动 刚看到您说的重新打开并搜索 确实这里不是乱码 虚惊一场

**Comment by lhj5426** [comment]
好了等会看看结果
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c1c276cf-97a6-41aa-9fa9-e200f53a3d52)

**Comment by lhj5426** [comment]
被各种红字统治了几个小时好像是安装完了 
这现在是gpu了？？
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/132c48d0-3516-4126-b7de-53253232a256)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5367414d-7e40-449f-b805-e9c744504ebe)

**Comment by lhj5426** [comment]
Traceback (most recent call last):
  File "J:\Downloads\75yuan\manga-image-translator\Python\lib\site-packages\bottle.py", line 868, in _handle
    return route.call(**args)
  File "J:\Downloads\75yuan\manga-image-translator\Python\lib\site-packages\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 90, in detect
    mask = t.gen_mask(img_rgb, mask, textlines)
  File "J:\Downloads\75yuan\manga-image-translator\manga_translator.py", line 213, in gen_mask
    final_mask = complete_mask(img_resized_2, mask_ccs, text_lines, cc2textline_assignment)
  File "J:\Downloads\75yuan\manga-image-translator\text_mask_utils.py", line 147, in complete_mask
    cc_region = refine_mask(img_region, cc_region)
  File "J:\Downloads\75yuan\manga-image-translator\text_mask_utils.py", line 100, in refine_mask
    mask_softmax = np.concatenate([cv2.bitwise_not(rawmask)[:, :, None], rawmask], axis=2)
    
    
    有时候会报 这个错误 报这个错误之后页面就文字检测识别就为 空了

**Comment by xulihang** [comment]
哪张图出错的？发张过来我测下吧

**Comment by lhj5426** [comment]
这个模式 的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/59002133-5c83-4217-b495-be206f302735)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/643e7902-a625-4de0-8323-8d1682097142)
 这个 模式下 

 昨天晚上安装完cuda 随便跑了一部 

大部分是NSFW的图 还请老哥您 在一个人的时候查看

[0003.zip](https://github.com/xulihang/ImageTrans-docs/files/13223398/0003.zip)

[0006.zip](https://github.com/xulihang/ImageTrans-docs/files/13223402/0006.zip)

[0008.zip](https://github.com/xulihang/ImageTrans-docs/files/13223403/0008.zip)

[0010.zip](https://github.com/xulihang/ImageTrans-docs/files/13223406/0010.zip)



[0011.zip](https://github.com/xulihang/ImageTrans-docs/files/13223407/0011.zip)

[0015.zip](https://github.com/xulihang/ImageTrans-docs/files/13223408/0015.zip)

[0018.zip](https://github.com/xulihang/ImageTrans-docs/files/13223410/0018.zip)
[0024.zip](https://github.com/xulihang/ImageTrans-docs/files/13223412/0024.zip)

[0026.zip](https://github.com/xulihang/ImageTrans-docs/files/13223415/0026.zip)
[0028.zip](https://github.com/xulihang/ImageTrans-docs/files/13223416/0028.zip)
[0029.zip](https://github.com/xulihang/ImageTrans-docs/files/13223418/0029.zip)

[0031.zip](https://github.com/xulihang/ImageTrans-docs/files/13223419/0031.zip)



这些都会报错

**Comment by xulihang** [comment]
上面这个错误可以下载更新这个文件解决：https://github.com/xulihang/manga-image-translator/raw/main/ocr_utils.py

**Comment by lhj5426** [comment]
确实 好使了

**Comment by xulihang** [comment]
> Traceback (most recent call last): File "J:\Downloads\75yuan\manga-image-translator\Python\lib\site-packages\bottle.py", line 868, in _handle return route.call(**args) File "J:\Downloads\75yuan\manga-image-translator\Python\lib\site-packages\bottle.py", line 1748, in wrapper rv = callback(*a, **ka) File "server.py", line 90, in detect mask = t.gen_mask(img_rgb, mask, textlines) File "J:\Downloads\75yuan\manga-image-translator\manga_translator.py", line 213, in gen_mask final_mask = complete_mask(img_resized_2, mask_ccs, text_lines, cc2textline_assignment) File "J:\Downloads\75yuan\manga-image-translator\text_mask_utils.py", line 147, in complete_mask cc_region = refine_mask(img_region, cc_region) File "J:\Downloads\75yuan\manga-image-translator\text_mask_utils.py", line 100, in refine_mask mask_softmax = np.concatenate([cv2.bitwise_not(rawmask)[:, :, None], rawmask], axis=2)
> 
> ```
> 有时候会报 这个错误 报这个错误之后页面就文字检测识别就为 空了
> ```

 这个掩膜生成的错误可以更新这个文件去解决：https://github.com/xulihang/manga-image-translator/raw/main/text_mask_utils.py

**Comment by lhj5426** [comment]
2个文件全部替换之后2个问题都解决了太感谢了 辛苦了
