### ISSUE TITLE
lang software is change to china is error or somethin else?

### ISSUE THREAD

**Issue by NinjaScoutZ** [xulihang/ImageTrans-docs#531]
error: java.lang.RuntimeException: Object should first be initialized (TableView).
StackTrace: java.lang.RuntimeException: Object should first be initialized (TableView).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4j.objects.TableViewWrapper.getItems(TableViewWrapper.java:218)
	at org.xulihang.imagetrans.main._cleartmandmt(main.java:4746)
	at org.xulihang.imagetrans.main._operationtabpane_tabchanged(main.java:17188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
How did you encounter this error?

What is the language pair of your project?

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/10115315-4769-49ba-868a-98db33ffa185)
