### ISSUE TITLE
mangaTranslatorOCR CTC 模式会报错

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#542]
error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr._processtextmask(ocr.java:4120)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2595)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
想问下这个是啥原因啊（一点也不懂Java）

**Comment by haofan170** [comment]
File "manga-image-translator\manga-image-translator\manga_translator.py", line 214, in run_ocr_ctc
    print(logprob, txt, f'fg: ({fr}, {fg}, {fb})', f'bg: ({br}, {bg}, {bb})')
UnboundLocalError: local variable 'logprob' referenced before assignment
127.0.0.1 - - [23/Dec/2023 22:24:13] "POST /ocr HTTP/1.1" 500 744这个是python的报错

**Comment by xulihang** [comment]
manga translator是用的我更新过的版本吗，就是用update.zip里的文件替换过

**Comment by xulihang** [comment]
可以把图片发过来我测一下

**Comment by haofan170** [comment]
> manga translator是用的我更新过的版本吗，就是用update.zip里的文件替换过

对的 替换了，我试了下所有的图片都会报这个错好像...图片不太健全就不发了吧（x）

**Comment by haofan170** [comment]
呃呃还有就是 为什么我在自定义工作流的时候没办法改翻译引擎呢？
![qg](https://github.com/xulihang/ImageTrans-docs/assets/49093867/96a47eee-8e3f-4064-a51c-616fe8016c6a)

**Comment by haofan170** [comment]
没事了..原来是要点击那个文字

**Comment by xulihang** [comment]
https://github.com/xulihang/manga-image-translator/commit/4914dbe3e359e2fa12d045d2430aca74f8df4e46 修复了 重新用updated.zip里的文件替换下吧

**Comment by haofan170** [comment]
> [xulihang/manga-image-translator@4914dbe](https://github.com/xulihang/manga-image-translator/commit/4914dbe3e359e2fa12d045d2430aca74f8df4e46) 修复了 重新用updated.zip里的文件替换下吧

好的感谢，我等下试试

**Comment by haofan170** [comment]
> [xulihang/manga-image-translator@4914dbe](https://github.com/xulihang/manga-image-translator/commit/4914dbe3e359e2fa12d045d2430aca74f8df4e46) 修复了 重新用updated.zip里的文件替换下吧

可以了！ 感谢大佬~ 另外问问那个新的48模型没考虑支持吗qwq 现在这个还是会有些识别错误就挺烦的

**Comment by xulihang** [comment]
得等我有时间

**Comment by xulihang** [comment]
48px的模型我试着加了下，还挺方便加进去的，已经更新相关说明和文件了

**Comment by haofan170** [comment]
> 48px的模型我试着加了下，还挺方便加进去的，已经更新相关说明和文件了

好捏 感谢
