### ISSUE TITLE
Java class file version

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#55]
When I got the new version of imagetrans and tried to check the offline balloon detection, I've been getting this error

error: java.lang.Exception: java.lang.UnsupportedClassVersionError: org/xulihang/DarkNetDetector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
StackTrace: java.lang.UnsupportedClassVersionError: org/xulihang/DarkNetDetector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.getCorrectClassName(JavaObject.java:274)
	at anywheresoftware.b4j.object.JavaObject.InitializeNewInstance(JavaObject.java:84)
	at org.xulihang.imagetrans.objectdetector._initialize(objectdetector.java:264)
	at org.xulihang.imagetrans.balloondetector._initialize(balloondetector.java:940)
	at org.xulihang.imagetrans.preferences._offlineballoondetectioncheckbox_checkedchange(preferences.java:550)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
I've recompiled the library with Java 8. Files are uploaded.

**Comment by HeLan8** [comment]
Thank you, could I have solved this problem by getting a different Java version or is it something else?

**Comment by xulihang** [comment]
You can use Liberica JDK 11. But I recommend using the updated version.
