### ISSUE TITLE
manga image translator报错

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#555]
error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr._processtextmask(ocr.java:4141)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2616)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
在用 48px ocr的时候报错这个捏

**Comment by haofan170** [comment]
File "H:\MANGA\manga-image-translator\manga-image-translator\manga_translator.py", line 356, in ocr
    cur_ch = textlines[textline_idx].text[0]
IndexError: string index out of range
127.0.0.1 - - [15/Jan/2024 19:26:47] "POST /ocr HTTP/1.1" 500 744 
这是cmd的提醒

**Comment by haofan170** [comment]
我错了==是CTC的模型

**Comment by xulihang** [comment]
有错误的图吗，我重现不了这个问题

**Comment by xulihang** [comment]
可以发到admin@basiccat.org

**Comment by haofan170** [comment]
> 可以发到[admin@basiccat.org](mailto:admin@basiccat.org)

我看看是哪张== 反正后面切48PX就识别好了（）

**Comment by haofan170** [comment]
> 可以发到[admin@basiccat.org](mailto:admin@basiccat.org)

还有就是有个关于排列的问题想问下，很多轻小说之类的是每页好几排从左往右这样子，这种情况下现在的任何一个排序方式似乎都不支持？ eg
![04](https://github.com/xulihang/ImageTrans-docs/assets/49093867/be7edf18-4c6b-4e44-bd55-a3a75415a291)

**Comment by haofan170** [comment]
呃呃还有个BUG,合并的时候没有按照顺序排序：
![EXB](https://github.com/xulihang/ImageTrans-docs/assets/49093867/4c1db137-c38f-484f-bdf3-e64d510ad1c4)
![EXA](https://github.com/xulihang/ImageTrans-docs/assets/49093867/f7990771-6b56-4a0c-9a60-ca9671b945c3)

**Comment by haofan170** [comment]
似乎是在2.8，会直接按照顺序的反方向来排列，不知道为什么？

**Comment by xulihang** [comment]
轻小说的文字是从右往左排列的。需要在项目设置里勾选从右往左阅读，然后排序方式改成横坐标。

这张比较特殊，有上下两部分。可以先用分镜功能框出上下两部分后再排序。

**Comment by haofan170** [comment]
> 轻小说的文字是从右往左排列的。需要在项目设置里勾选从右往左阅读，然后排序方式改成横坐标。
> 
> 这张比较特殊，有上下两部分。可以先用分镜功能框出上下两部分后再排序。

懂了== 可以手动画分镜啊，那这个似乎是新bug的情况..是我哪里没设置好吗（）

**Comment by xulihang** [comment]
这样排序的结果：
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/ba0926e6-0c46-4f8a-b9f5-c56de37c6cff)

点左右合并：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/9b5a6ff1-c340-4cae-96fc-d3d7244f0880)

第一个框里合并的文本：

```
「…やっぱり短すぎないか?コレ」 緑のスカーフを留めながら、ライトグレーの短パンから出る自分の剥きも しの太股を見た少年は、恥かしそうに頬を染めて困惑の表情を浮かべた. 「うん!めっちゃ笑える!遼ちゃん、やっぱり中学校二年生にもなってソレ は無いよね!」 間髪いれずにそう言った、鼻に絆創膏を貼っている少年は、ニヤニヤと笑 って、携帯で遼の股間を撮影する. ただしその少年自身も、さらに短い半ズボンから、日に焼けた太股を晒し ているのだが、小学生の自分は問題ないらしい. 「翔太ぁっ!そういうお前だって、かなり恥かしいぞ?い学生だからって誰 されるレベルじゃないぞ?」 「え〜?やっぱそうかなぁ?」 遼の反撃に、翔太は一転して弱気になって自分の股間を見る.
```

**Comment by xulihang** [comment]
这个是从上往下阅读啊，那不能勾选从右到左阅读。目前对于文字顺序混合，有从上往下或者从右往左这两种情况的图处理得不好，只能选择一种合并顺序。

**Comment by haofan170** [comment]
> 这个是从上往下阅读啊，那不能勾选从右到左阅读。目前对于文字顺序混合，有从上往下或者从右往左这两种情况的图处理得不好，只能选择一种合并顺序。

明白了（） 原来问题在这

**Comment by xulihang** [comment]
48px的识别那张图有问题，我修不好，用别的模型可以的

**Comment by haofan170** [comment]
> 48px识别那张图有问题，我修不好，用别的模型可以的

神奇，我这边CTC也不行，不过用哪个manga translater就可以了...
