### ISSUE TITLE
呃呃..排序的问题还是不太对劲

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#556]
在关闭了设置里的从右往左以后：
![exe](https://github.com/xulihang/ImageTrans-docs/assets/49093867/41872545-cdab-451a-aff7-347620f9a4f0)
分镜正确的情况下合并依旧会混乱
![exf](https://github.com/xulihang/ImageTrans-docs/assets/49093867/6a41a898-fdcc-4cd0-8c77-ec9e837d23bd)
![EXG](https://github.com/xulihang/ImageTrans-docs/assets/49093867/b479f92e-6f52-437e-bb05-d11898cfc187)
就很奇怪== 完全想不通

**Comment by xulihang** [comment]
图片发过来我看下

**Comment by haofan170** [comment]
> 图片发过来我看下



> 图片发过来我看下

已发送，感谢~

**Comment by haofan170** [comment]
> 图片发过来我看下


> 图片发过来我看下

error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr._processtextmask(ocr.java:4141)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2616)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
这个又出现了== 也发过去了（）

**Comment by haofan170** [comment]
> 我用2.8.0排序是对的。
> 
> ```
> 鋸竹学園では夜になると使われていない旧校舎の階段から毎晩おとこのこの泣き声とパンパンという音が聞こえてくるという真相をつきとめようと放課後こっそり居残って旧校舎に忍び込んだハジメくんは妖怪キョコン影男に捕らわれ二度と帰って来ませんでした
> ```

太奇怪了。。。我等下试下2.6的版本看看行不行（）

**Comment by xulihang** [comment]
噢，你是用工具栏合并的啊，这个的确有问题，需要修一下

**Comment by haofan170** [comment]
> 噢，你是用工具栏合并的啊，这个的确有问题，需要修一下

原来是这样。。那我用工作流就可以了？

**Comment by haofan170** [comment]
> 工作流里的可以

好捏~另外一个是OCR会失败的图，无论是48PX/CTC都不行 挺奇怪的

**Comment by xulihang** [comment]
发了一个2.8.1，修复了用工具栏合并的问题

**Comment by haofan170** [comment]
> 发了一个2.8.1，修复了用工具栏合并的问题

好耶~ 不知道这个多空格的问题一起解决了吗（）
刚回去测试2.6是正常的

**Comment by xulihang** [comment]
空格的问题，只要你设置的原文语言是中文和日文，就不会添加空格

**Comment by xulihang** [comment]
这是2.8.1才修的

**Comment by haofan170** [comment]
> 这是2.8.1才修的

SOKKA 好的捏~辛苦大佬一晚上了（）早点休息吧233
