### ISSUE TITLE
Full package not launching [Windows]

### ISSUE THREAD

**Issue by Monov247** [xulihang/ImageTrans-docs#558]
Version 2.8.1

I have downloaded the full package from onedrive and have attempted to install crossplatform version with JRE & OpenCV and neither versions did anything when I ran the .exe/.jar, not even an error window.

**Comment by xulihang** [comment]
If you are using the full package, you don't have to use the cross-platform version. You just need to unzip it and run "ImageTrans.exe".

**Comment by xulihang** [comment]
Please also check your Windows version. Is it a x64 system with the windows version > 7.

**Comment by Monov247** [comment]
Windows version and device specification is as follows, does it being an education version effect anything?


Edition	Windows 10 Education N
Version	22H2
Installed on	‎29/‎12/‎2023
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0


Device name	Glacier
Processor	AMD Ryzen 5 3600 6-Core Processor                 3.59 GHz
Installed RAM	16.0 GB
Device ID	DB9C125D-44F2-4188-9BFA-C7930F27820B
Product ID	00328-50602-49933-AA453
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

**Comment by xulihang** [comment]
The education version should also work. Try to use `ImageTrans.bat` to start the program and see the error output.

You can also use PowerShell to do this:

```ps
./jre/bin/java -jar ImageTrans.jar
```

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/844b986c-6c7f-4fae-9c3b-9921af9befe2)

**Comment by Monov247** [comment]
the .bat closes too quickly for me to capture the whole error. Also a note with the powershell directory you sent, I do not have an "Objects" folder with my install


.bat output:

![image](https://github.com/xulihang/ImageTrans-docs/assets/157201954/9ab3114c-af6f-4a7c-ba61-09d3b79cc2bd)

Powershell output:

```
PS C:\Mega\Stuff\Translator\ImageTrans> ./jre/bin/java -jar ImageTrans.jar
Device locale: en
Found 873 strings.
(ArrayList) []
Loading jar finished
Initializing plugin chatGPTMT
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
Loading jar finished
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
        at org.xulihang.imagetrans.main._loadopencv(main.java:12179)
        at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:1737)
        at org.xulihang.imagetrans.main._appstart(main.java:1682)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: C:\Mega\Stuff\Translator\ImageTrans\opencv_java455.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        ... 24 more

Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin deeplMT
Loading jar finished
Initializing plugin ExternalInpaint
Loading jar finished
Initializing plugin ExternalMaskGen
Loading jar finished
Initializing plugin geminiMT
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin imgbaiduOCR
Loading jar finished
Initializing plugin InsetRectMaskGen
Loading jar finished
Initializing plugin manga-ocrOCR
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin WinRTOCR
Loading jar finished
Initializing plugin yandexMT
main.start (java line: 37)plugins have changed!

(ArrayList) [chatGPTMT, cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, ExternalInpaint, ExternalMaskGen, geminiMT, google_driveOCR, googleMT, googleOCR, imgbaiduOCR, InsetRectMaskGen, manga-ocrOCR, niutransMT, opusMT, paddleocrOCR, papagoMT, tencentOCR, webMT, WinRTOCR, yandexMT]java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
        at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
        at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
        ... 14 more
Caused by: java.lang.NullPointerException
        at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
        at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
        at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
        at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
        at org.xulihang.imagetrans.main._application_error(main.java:1472)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 15 more


loading ocr plugins
run(Map) Not initialized
PS C:\Mega\Stuff\Translator\ImageTrans>
```

**Comment by xulihang** [comment]
Is this the full version? Please check if this file exists: `opencv_java455.dll`

**Comment by Monov247** [comment]
This was the version I downloaded from onedrive

![image](https://github.com/xulihang/ImageTrans-docs/assets/157201954/ea46914c-7d84-473a-96a2-7aeb43da43cd)

**Comment by xulihang** [comment]
I see. OpenCV requires media play while you version (education N) does not have it.

```
Caused by: java.lang.UnsatisfiedLinkError: C:\Mega\Stuff\Translator\ImageTrans\opencv_java455.dll: Can't find dependent libraries
```

Try to install media play on your windows.

I have found one guide: https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-10-11-n-september-2022-78cfeea5-c7d9-4aa8-b38f-ee4df1392009

**Comment by Monov247** [comment]
Perfect, all working now, thank you so much.
