### ISSUE TITLE
I'm getting error from google_drive and google not working at all

### ISSUE THREAD

**Issue by EdShedisson** [xulihang/ImageTrans-docs#571]
error: java.lang.ClassCastException: class java.lang.String cannot be cast to class anywheresoftware.b4a.objects.collections.List (java.lang.String is in module java.base of loader 'bootstrap'; anywheresoftware.b4a.objects.collections.List is in unnamed module of loader 'app')
StackTrace: java.lang.ClassCastException: class java.lang.String cannot be cast to class anywheresoftware.b4a.objects.collections.List (java.lang.String is in module java.base of loader 'bootstrap'; anywheresoftware.b4a.objects.collections.List is in unnamed module of loader 'app')
	at org.xulihang.imagetrans.googleocrplugin$ResumableSub_GetTextWithLocation.resume(googleocrplugin.java:427)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
You have to fill in your api key to use Google. Check out this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

**Comment by xulihang** [comment]
The default Google Drive is working.
