### ISSUE TITLE
Order for text areas on manga and get text area confidence error

### ISSUE THREAD

**Issue by AkiraMajiri** [xulihang/ImageTrans-docs#579]
When doing the Detect text areas (heuristic) function, is it posible to configure so the numeration starts from right to left? I couldnt find the option for that. 
Also, whenever I try to use the text area confidence option, it throws an error:
```
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.imageclassifier._initialize(imageclassifier.java:368)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:9506)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:9394)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:15388)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:13671)
	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "C:\Users\USERNAME\Desktop\ImageTrans\frozen_graph.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
]
	at org.opencv.dnn.Dnn.readNet_2(Native Method)
	at org.opencv.dnn.Dnn.readNet(Dnn.java:396)
	... 22 more
```
and then it stucks on "procesing..."

**Comment by xulihang** [comment]
1. Enable right-to-left reading order in project settings.
   ![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/90e08f48-9034-474d-9b7c-460a73b7e14d)

2. Does your username contain special characters? Try to place it in a simpler path like C:\ImageTrans

**Comment by AkiraMajiri** [comment]
2. Solved after changing the location (my username has an special character, indeed)
1. I get the same result even if I check the right-to-left reading order option. 
![disabled](https://github.com/xulihang/ImageTrans-docs/assets/132158886/805a8c28-5502-4b11-ace0-b5c14aee7184)
![enabled](https://github.com/xulihang/ImageTrans-docs/assets/132158886/357d628f-87f3-4d56-9bf9-ef5d7078f996)

**Comment by xulihang** [comment]
Well, you need to sort it. 

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/3db0e842-5bc1-4c04-bcb1-2ee3143766ef)

The `Detect text areas (heuristic)` function does not sort the areas automatically.
