### ISSUE TITLE
NullPointerException running on Linux

### ISSUE THREAD

**Issue by MitchelValentine** [xulihang/ImageTrans-docs#58]
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at org.xulihang.imagetrans.main.start(main.java:37)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
	at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
	at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	... 14 more
Caused by: java.lang.NullPointerException
	at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
	at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
	at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
	at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
	at org.xulihang.imagetrans.main._application_error(main.java:1044)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	... 15 more
```

**Comment by xulihang** [comment]
Are you running on Linux? Make sure you have installed opencv correctly

**Comment by MitchelValentine** [comment]
I dragged and dropped both `.so` files into the root directory of ImageTrans; same thing.

**Comment by xulihang** [comment]
You may also have to set library path. You can put the so files to /usr/lib
