### ISSUE TITLE
error when exporting in xlsx format

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#582]
error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.exporter._rowtoexport(exporter.java:1961)
	at org.xulihang.imagetrans.exporter._rowstoexport(exporter.java:1918)
	at org.xulihang.imagetrans.exporter._export(exporter.java:205)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:14574)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:13671)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
Could you attach a project file for me to test?

**Comment by xulihang** [comment]
Could you attach a project file for me to test?

**Comment by ztench** [comment]
[9.zip](https://github.com/xulihang/ImageTrans-docs/files/14473252/9.zip)

**Comment by xulihang** [comment]
I need the project file.
