### ISSUE TITLE
有时候编辑掩膜时会报错，然后再也无法正常打开了

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#599]
图像大小2331x3297，项目其他的图片能正常编辑掩膜，有时候碰到某张图编辑掩膜的时会报错，之后这一页进入掩膜就一直报错了，翻译也显示不了

error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:228)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1401)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:5068)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:4856)
	at org.xulihang.imagetrans.utils._textmask(utils.java:4804)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:8859)
	at org.xulihang.imagetrans.main._gentextmask(main.java:8799)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:19257)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:19164)
	at org.xulihang.imagetrans.main$ResumableSub_UpdateTranslated.resume(main.java:26136)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:26098)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:25610)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3868)
	... 30 more

**Comment by xulihang** [comment]
过去的相关issue：https://github.com/xulihang/ImageTrans-docs/issues/282

检查下有没有错误的文本框

**Comment by yahoozhu** [comment]
> 过去的相关issue：#282
> 
> 检查下有没有错误的文本框

明白了，确实有个点状的文本框在角落里
