### ISSUE TITLE
Bulk OCR Error

### ISSUE THREAD

**Issue by boxerjr713** [xulihang/ImageTrans-docs#6]
I have been receiving an error when I attempt to bulk OCR my projects. If I click OCR for individual lines, it works. But when I attempt to bulk OCR several pages of text, it provides an error report and begins listing "null" in the OCR text boxes. This happens while using "baidu_accurate" but it also occurs while using other OCR styles. This has happened repeatedly with different projects and OCR styles selected. Below is the error report I received most recently.

error: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
StackTrace: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_BoxesListView_SelectedIndexChanged.resume(main.java:2812)
	at org.xulihang.imagetrans.main._boxeslistview_selectedindexchanged(main.java:2618)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
baidu_accurate has a usage limit which is 500 times per day while baidu_general's daily limit is 50000 times.
If the usage limit is exceeded, it will give a null result.

The other online OCR engines also have limits like this. Azure has a request limit per second (QPS). I recommend applying for the OCR API keys by yourself since the API keys I include in ImageTrans is shared by all users.

**Comment by xulihang** [comment]
As for the reported BoxesListView_SelectedIndexChanged error, I haven't encountered such errors.

**Comment by boxerjr713** [comment]
Thank you for the prompt response! I wasn't aware of that there were daily limits on the OCR engines. I'll take that into consideration in the future. I'm not sure how to procure my own OCR API keys or how to apply them to my person ImageTrans, but I'll look into it. Hopefully that will resolve my issue since I have a very large amount of files I'd like to process with ImageTrans. Thank you very much!

**Comment by xulihang** [comment]
You can apply for google's ocr by following guides like this: https://easyscreenocr.com/how-to-load-google-api-in-easyscreenocr-for-mac-lifetime-version/. You just need to put the api key in ImageTrans's preference.

If you need to process a large amount of files, you may consider offline OCR solutions like: [easyocr](https://www.jaided.ai/easyocr), [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR).

ImageTrans has a built-in support for them (see [the plugin](https://github.com/xulihang/ImageTrans_plugins/tree/master/easyOCR)) but it might a bit complicated to install and run them locally.

**Comment by lugia19** [comment]
I'm experiencing the same exact error with bulk OCR. I'm using ABBYY finereader 15 (local finecmd) for the OCR.

**Comment by xulihang** [comment]
Which error are you experiencing? The null problem or the BoxesListView_SelectedIndexChanged error. How did this happen?

**Comment by lugia19** [comment]
This is the error:
error: java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
StackTrace: java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_BoxesListView_SelectedIndexChanged.resume(main.java:2960)
	at org.xulihang.imagetrans.main._boxeslistview_selectedindexchanged(main.java:2766)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)


I'm pretty sure I've also figured out why it happens. It only happens when using bulk OCR on a project where bulk OCR has already been used (so source text is already present).

**Comment by xulihang** [comment]
I see. I have fixed this with a check on items size and index. I'll release the new version (files on onedrive are always the latest version) in a few days.

**Comment by xulihang** [comment]
Fixed with version 1.3.3. The new version is released.

**Comment by xulihang** [comment]
Fixed with version 1.3.3. The new version is released.
