### ISSUE TITLE
图片预览 bug

### ISSUE THREAD

**Issue by yougnut** [xulihang/ImageTrans-docs#610]
问题描述：导入图片，画完框、批量翻译结束后，有些页面显示的预览图片与实际页码不符(比如第13页但编辑页面上显示的是第14页的图片)，此时选择导出图片或编辑掩膜会出现以下报错，不知该如何解决，谢谢大佬

1. 比如说这是39页，是正常显示的图片与框选位置
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/5872820b-8c1a-4b82-94c9-87b68c2176ae)
2. 往前到38页却仍旧显示39页的图片，框选位置是正确的，表示在文字检测与OCR时原图仍是38页的原图
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/1e029082-b951-44f1-a7cb-a57811896da2)
3. 此时我为了确认原图在不在选取了编辑掩膜，出现了以下报错
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/c5d53bb0-e8c9-4f2d-b868-24146c550c18)
  error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.utils._validategeometry(utils.java:5729)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:5225)
	at org.xulihang.imagetrans.maskeditor$ResumableSub_loadMask.resume(maskeditor.java:562)
	at org.xulihang.imagetrans.maskeditor._loadmask(maskeditor.java:426)
	at org.xulihang.imagetrans.maskeditor._show(maskeditor.java:1205)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:15200)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:13934)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
4. 关闭报错窗口后可以看到原图仍是38页原图，但显示掩膜正在生成中，不知道是什么步骤出问题了
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/6fa09f9d-c7ca-467f-b36b-a29f80abac56)

**Comment by xulihang** [comment]
我估计是38页哪个文本框宽高和坐标不对，导致掩膜生成失败了，然后查看翻译也没成功。

右键刷新可以重置显示状态。

**Comment by xulihang** [comment]
还是有问题可以把图片和项目发一份过来我看一下

**Comment by yougnut** [comment]
[project.zip](https://github.com/xulihang/ImageTrans-docs/files/14872285/project.zip)
抱歉图档过大只能上传一部分，感谢大佬

**Comment by xulihang** [comment]
项目文件是不是用别的软件编辑过了，存在一个没有坐标的文本框，导致38.jpg加载失败了。


```json
{
                    "probability": 0.9261536598205566,
                    "geometry": {
                        "X": 763,
                        "width": 174,
                        "Y": 103,
                        "height": 274
                    },
                    "text": "はい……ありがとうございました。",
                    "target": "好的……謝謝。"
                },
                {
                    "text": "はい……ありがとうございました。",
                    "target": "好的……謝謝。"
                }
```

**Comment by xulihang** [comment]
要继续用这个项目，只有手动排查，把这些错误的文本框删掉。

**Comment by yougnut** [comment]
没有用过其他软件编辑，现在回想可能是自定译工作流进行到一半时电脑卡顿过于严重所以从工作管理员强制结束进程，可能当时正进行到这个步骤。
把文本框删除后的确恢复正常了，谢谢大佬!
