### ISSUE TITLE
蓝屏了，重启后项目打不开了

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#620]
error: java.lang.RuntimeException: JSON Object expected.
StackTrace: java.lang.RuntimeException: JSON Object expected.
	at anywheresoftware.b4j.objects.collections.JSONParser.NextObject(JSONParser.java:50)
	at org.xulihang.imagetrans.project._readprojectfile(project.java:774)
	at org.xulihang.imagetrans.project._initialize(project.java:642)
	at org.xulihang.imagetrans.main._openproject(main.java:18296)
	at org.xulihang.imagetrans.main._recentprojectmi_action(main.java:20827)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

哭死，快搞完了就剩拟声词了

**Comment by xulihang** [comment]
项目文件有备份的，把扩展名bak的文件重命名一下，扩展名改成itp，再用ImageTrans去打开

**Comment by yahoozhu** [comment]
> 项目文件有备份的，把扩展名bak的文件重命名一下，扩展名改成itp，再用ImageTrans去打开

备份是昨晚刚开始做时候的……

**Comment by yahoozhu** [comment]
> 项目文件有备份的，把扩展名bak的文件重命名一下，扩展名改成itp，再用ImageTrans去打开

 
[0.zip](https://github.com/xulihang/ImageTrans-docs/files/14975206/0.zip)

还有挽救的余地吗？早上搞到现在6 7个小时了 ？

**Comment by xulihang** [comment]
这是个空文件，没有数据了

**Comment by xulihang** [comment]
下次记得手动备份下项目吧
