### ISSUE TITLE
查找替换“．．．”的时候总是报这个错误

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#631]
error: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 5
StackTrace: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.xulihang.imagetrans.utils._splitbyfind(utils.java:4988)
	at org.xulihang.imagetrans.searchandreplacedialog._showresult(searchandreplacedialog.java:883)
	at org.xulihang.imagetrans.searchandreplacedialog._findbutton_click(searchandreplacedialog.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

![2024-04-23_12-06-26](https://github.com/xulihang/ImageTrans-docs/assets/24186777/95c9bd48-f2b0-4701-8650-42a889b60fa2)
![2024-04-23_12-06-44](https://github.com/xulihang/ImageTrans-docs/assets/24186777/e1133740-8ff7-40b4-9e13-7fccc495aa96)

主要是三个点“．．．”这个组合符号，一点查找，一定会报这个错误，另外想问下省略号的识别总是会出错，各种更正都上了，长省略号还是这样，请问有什么办法能搞定吗？

**Comment by xulihang** [comment]
哪里设错了吧，自动更正是可以替换这种省略号的。

可以把项目文件发过来我看下你的设置。

**Comment by yahoozhu** [comment]
[0.zip](https://github.com/xulihang/ImageTrans-docs/files/15071180/0.zip)


> 哪里设错了吧，自动更正是可以替换这种省略号的。
> 
> 可以把项目文件发过来我看下你的设置。

**Comment by xulihang** [comment]
等我定位下是哪个文本片段查找和替换有问题

**Comment by xulihang** [comment]
目前可以先改用正则，使用以下表达式匹配所有`．`的字符

```
．+
```

**Comment by xulihang** [comment]
`04_4.jpg`这张图片也发一下，可以发我邮箱。

**Comment by yahoozhu** [comment]
> `04_4.jpg`这张图片也发一下，可以发我邮箱。

![04_4](https://github.com/xulihang/ImageTrans-docs/assets/24186777/9ed3c742-c474-43cd-8c95-cf20a901b4b2)

这样可以吧，没找着你邮箱

**Comment by xulihang** [comment]
查找与替换有个bug，我已经修了。自动更正我没测出有什么问题

**Comment by lhj5426** [comment]
其实这个省略号 你替换没什么用为什么我这么说呢
你是好好替换了 AI翻完 AI 它也乱写呀
这种我都是在ai翻译完之后 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/f15f9298-0d73-41ee-a87d-e7c1d3b55a11)
用文本工具 批量替换AI翻译结果里的 
你原文是正常的 但是架不住AI也乱点标点 不管是GPT4还claude3 op 这个模型 标点都会乱点 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/f3816c03-9b39-4add-856b-afd809a89127)

**Comment by yahoozhu** [comment]
> 其实这个省略号 你替换没什么用为什么我这么说呢 你是好好替换了 AI翻完 AI 它也乱写呀 这种我都是在ai翻译完之后 ![image](https://private-user-images.githubusercontent.com/30548000/324865059-f15f9298-0d73-41ee-a87d-e7c1d3b55a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODE3NDEsIm5iZiI6MTcxMzg4MTQ0MSwicGF0aCI6Ii8zMDU0ODAwMC8zMjQ4NjUwNTktZjE1ZjkyOTgtMGQ3My00MWVlLWE4N2QtZTdjMWQzYjU1YTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTc2ZWEyMDAyMzc4OGZlNzMxZDY3OWQ1MGUxNWQwZTZiNmY4ZjJiYWYwY2M2NGZkNTk0N2UyYjc1ZDM4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zztd9ErwXTjCSMMVCOZFpyNB8i9If4gPTcp_lGhkBvI) 用文本工具 批量替换AI翻译结果里的 你原文是正常的 但是架不住AI也乱点标点 不管是GPT4还claude3 op 这个模型 标点都会乱点 ![image](https://private-user-images.githubusercontent.com/30548000/324865312-f3816c03-9b39-4add-856b-afd809a89127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODE3NDEsIm5iZiI6MTcxMzg4MTQ0MSwicGF0aCI6Ii8zMDU0ODAwMC8zMjQ4NjUzMTItZjM4MTZjMDMtOWIzOS00YWRkLTg1NmItYWZkODA5YTg5MTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjY1MTU5YjRmYmIwN2Y2YjI4OTlmODdkMWYzZDg2NGMzNjk3NGE3Y2Q5NWZjNzVmYTlhNmU1MTY4ZWMzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ckSMFi9SMtz4ge5B1SvvSGX8eN9Vx-rGFbM00XJ2QW8)

还真是，有的AI会给搞乱，有的却会纠正
不过我估计还有很多人并不是用AI在翻译吧

**Comment by lhj5426** [comment]
以前没有AI 传统翻译的时候还得修各种奇怪的词
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4913e000-0680-4858-a286-6e08c825c620)
不过现在只需要修正 这种 之后交给AI就行了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/efa13c50-3e43-480e-a652-cd7025eabb89)

**Comment by xulihang** [comment]
查找替换的问题，v2.11.1修复了
