### ISSUE TITLE
manga-image-translator 突然无法识别没有文字的图片了？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#650]
rt，在翻译cg之类的情况下，经常会有些没有文字的图片，一般都是识别一轮识别不到就去下张图了，但是现在会一直卡在识别没文字的图片, 啥也没更新就这样了。。。大佬有啥头绪吗（）
 尝试过了manga-image-translator 48PX CTC 都是这个情况，之前翻译同一个图片也不会这样

**Comment by haofan170** [comment]
update:换老版本的软件以后运行会报错：error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.ocr._processtextmask(ocr.java:4141)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2616)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

新版本不报错但是也会卡在同样情况（没文字）的图片，尝试过了32px ctc 48px，都是这样

**Comment by haofan170** [comment]
另外：发现如果关闭使用ocr生成掩膜。则不会有这个问题，我先关闭ocr生成掩膜来使用了（x）

**Comment by xulihang** [comment]
可以下最新的v2.12.2试下，掩膜生成失败不会影响批量OCR的执行

**Comment by haofan170** [comment]
额 好的 我等下看看 但是如果分开来 单独先执行完ocr 再去使用ExternalMaskGen 则可以生成掩膜 真神奇

Lihang Xu ***@***.***>於 2024年5月19日 週日，20:46寫道：

**Comment by haofan170** [comment]
> 可以下最新的v2.12.2试下，掩膜生成失败不会影响批量OCR的执行

好奇怪 2.12.2直接打不开exe 双击了ImageTrans.exe或者ImageTrans.jar直接没反应

**Comment by xulihang** [comment]
我测试是没问题的
