### ISSUE TITLE
ImageTrans Crash on Startup

### ISSUE THREAD

**Issue by ashbir** [xulihang/ImageTrans-docs#652]
The application is crash on the startup. 

I use Fedora 40 Sway and installed the java with https://github.com/bell-sw/Liberica/releases/download/11.0.23%2B12/bellsoft-jdk11.0.23+12-linux-amd64-full.rpm

This the output log from `java -jar ImageTrans.jar`
```bash
Device locale: en
Found 933 strings.
(ArrayList) []
Loading jar finished
Initializing plugin chatGPTMT
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.main._loadopencv(main.java:12714)
	at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:1884)
	at org.xulihang.imagetrans.main._appstart(main.java:1825)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at org.xulihang.imagetrans.main.start(main.java:44)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:456)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:429)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:428)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2678)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1890)
	... 24 more

Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin deeplMT
Loading jar finished
Initializing plugin ExternalInpaint
Loading jar finished
Initializing plugin ExternalMaskGen
Loading jar finished
Initializing plugin geminiMT
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin imgbaiduOCR
Loading jar finished
Initializing plugin InsetRectMaskGen
Loading jar finished
Initializing plugin manga-ocrOCR
Loading jar finished
Initializing plugin mangaTranslatorOCR
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin yandexMT
plugins have changed!
(ArrayList) [chatGPTMT, cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, ExternalInpaint, ExternalMaskGen, geminiMT, google_driveOCR, googleMT, googleOCR, imgbaiduOCR, InsetRectMaskGen, manga-ocrOCR, mangaTranslatorOCR, niutransMT, opusMT, paddleocrOCR, papagoMT, tencentOCR, webMT, yandexMT]
loading ocr plugins
run(Map) Not initialized
main.start (java line: 44)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at org.xulihang.imagetrans.main.start(main.java:44)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:456)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:429)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:428)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
	at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
	at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	... 14 more
Caused by: java.lang.NullPointerException
	at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
	at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
	at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
	at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
	at org.xulihang.imagetrans.main._application_error(main.java:1615)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	... 15 more
```

**Comment by ashbir** [comment]
Fixed by adding the libopencv_java490.so to LD_LIBRARY_PATH
