### ISSUE TITLE
在使用imgagetrans2.12.2时ocrspace简体中文文字提取时遇到的报错

### ISSUE THREAD

**Issue by YOuKn0wHOw** [xulihang/ImageTrans-docs#653]
error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.ocr$ResumableSub_ocrspace.resume(ocr.java:3954)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
OCRSpace在做全图OCR时容易失败，可以改用别的OCR引擎。比如WinRT，是OCRSpace的离线版。

**Comment by YOuKn0wHOw** [comment]
我在用winrt的时候时不时也会出现无效的状态，请问这个需要额外设置什么吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月23日(星期四) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] 在使用imgagetrans2.12.2时ocrspace简体中文文字提取时遇到的报错 (Issue #653)





 
OCRSpace在做全图OCR时容易失败，可以改用别的OCR引擎。比如WinRT，是OCRSpace的离线版。

**Comment by YOuKn0wHOw** [comment]
就比如这张吧，识别出乱码，有时框都不建立，我使用时成功率大概在5成左右






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月23日(星期四) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] 在使用imgagetrans2.12.2时ocrspace简体中文文字提取时遇到的报错 (Issue #653)





 
WinRT失败我没碰到过。可以把图片发过来我试一下

**Comment by xulihang** [comment]
看不到图。WinRT的语言有选对吗？它需要系统自身有安装对应的语言。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/a4a89c78-0ea1-4ff6-89fc-179512646a91)

离线OCR里识别中文比较好的是PaddleOCR，要效果更好的话用百度或者有道这些在线引擎。

**Comment by xulihang** [comment]
可以改用PaddleOCR，照这里的说明运行：https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR

**Comment by YOuKn0wHOw** [comment]
好滴，我试试，多谢解疑




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2024年5月23日(星期四) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] 在使用imgagetrans2.12.2时ocrspace简体中文文字提取时遇到的报错 (Issue #653)














 
可以改用PaddleOCR，照这里的说明运行：https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR
