### ISSUE TITLE
使用时频繁报错

### ISSUE THREAD

**Issue by changbaishanshan** [xulihang/ImageTrans-docs#655]
在使用imagetrans时突然开始频繁报错，仔细想一下的话是自从安装了manga-image-translator之后就开始了，每次进入项目后没多久无论点哪里都会报error，如图所示，请大佬解惑。
![Uploading 批注 2024-05-26 213112.png…]()

**Comment by xulihang** [comment]
图片没传成功。可以把错误日志发一下。

manga-image-translator是独立于软件的，不会影响软件本身

**Comment by changbaishanshan** [comment]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_supportMultipleCandidates.resume(mt.java:1985)
	at org.xulihang.imagetrans.mt._supportmultiplecandidates(mt.java:1948)
	at org.xulihang.imagetrans.main$ResumableSub_showMT.resume(main.java:24626)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
什么操作时出现的？启用了哪些机器翻译？

这个只有在辅助翻译选项页里查看多个机器翻译结果时才会执行。我和其它用户用过没碰到问题

**Comment by changbaishanshan** [comment]
感谢大佬关注，仔细想一下是在设置了Chatgpt翻译器之后，而且我输入了API可是chatgpt翻译始终不起作用，不显示翻译内容

**Comment by xulihang** [comment]
可以看这篇博客了解怎么配置ChatGPT：https://www.basiccat.org/zh/ChatGPT-image-translator/
