### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ZeroSkman** [xulihang/ImageTrans-docs#66]
error: java.io.FileNotFoundException: C:\Users\zero4\AppData\Local\Temp\14 (拒绝访问。)
StackTrace: java.io.FileNotFoundException: C:\Users\zero4\AppData\Local\Temp\14 (�ܾ����ʡ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
做什么操作时发生的错误？把软件解压到一个目录后再执行

**Comment by ZeroSkman** [comment]
自动识别文字后扫描报错的，软件我是单独放在D盘

**Comment by ZeroSkman** [comment]
日漫中有竖排和横排并存，貌似是报错的原因

**Comment by ZeroSkman** [comment]
彩漫自动识别文字就报错了

**Comment by xulihang** [comment]
不要用ocrspace自动识别文字，换百度看看。报错信息和上面发的一样吗，上面发的我没碰到过，不像是OCR时的错误。

**Comment by xulihang** [comment]
用百度的话，它可能定位不了文字，需要先框选区域后再OCR

**Comment by ZeroSkman** [comment]
似乎是的，其他几个也会显示相同的报错

**Comment by ZeroSkman** [comment]
error: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
StackTrace: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
	at org.xulihang.imagetrans.googleocrplugin$ResumableSub_GetText.resume(googleocrplugin.java:374)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
这是谷歌显示的报错

**Comment by xulihang** [comment]
谷歌需要申请API密钥才能用的，因为它是收费的。这里列了默认有哪些OCR引擎可用：https://basiccat-docs.readthedocs.io/zh_CN/latest/gettingstarted.html

**Comment by ZeroSkman** [comment]
好的，我用了微软的他不会报错

**Comment by xulihang** [comment]
微软Azure每分钟的请求数是有限制的，如果你用Windows10的话，系统有自带OCR，和Azure的引擎是一样的，可以无限制地使用，对应的引擎名字叫WinRT。

**Comment by ZeroSkman** [comment]
好的

**Comment by ZeroSkman** [comment]
我把tesseract-ocr目录和ImageTrans放在一起语言包也放好了，为什么选择tesseract还是不能使用，点击后不报错也没有任何反应

**Comment by xulihang** [comment]
你看下语言数据包是不是这样的：
![image](https://user-images.githubusercontent.com/5462205/123723938-0a1d2480-d8be-11eb-90dc-ee192145c404.png)

另外还要设置路径：

![image](https://user-images.githubusercontent.com/5462205/123724069-40f33a80-d8be-11eb-8bb4-dfa451018a35.png)

**Comment by ZeroSkman** [comment]
![image](https://user-images.githubusercontent.com/62535487/123759163-38b4f280-d8f2-11eb-95b2-5499eaa40e9c.png)
设置好了但是文件夹没有jar后缀的文件

**Comment by xulihang** [comment]
那可能就是识别没有结果，你可以先识别一个英文的图看看能不能用

**Comment by xulihang** [comment]
另外还有一个查看错误的方法，就是在命令行打开软件，查看输出：

```
.\jre\bin\java -jar ImageTrans.jar
```

**Comment by ZeroSkman** [comment]
好的

**Comment by ZeroSkman** [comment]
请问有没有能一键打包的功能啊我每次汉化了以后都要一张一张的导出为jpg

**Comment by xulihang** [comment]
这个：项目-批处理-自动导出所有图片的成品图。
记得把显示比例调整到100%。

**Comment by ZeroSkman** [comment]
又出现我新的问题我将文本翻译好了后勾选查看翻译出现一下报错
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:171)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1038)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:3379)
	at org.xulihang.imagetrans.utils._textmask(utils.java:3236)
	at org.xulihang.imagetrans.main._gentextmask(main.java:6219)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:13779)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:13685)
	at org.xulihang.imagetrans.main._updatetranslated(main.java:17994)
	at org.xulihang.imagetrans.main._translationmodecheckbox_checkedchange(main.java:17674)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:5376)
	... 26 more

**Comment by xulihang** [comment]
新的问题麻烦再开一个issue，把能够重现这个问题的项目文件和图片也传一下

**Comment by ZeroSkman** [comment]
已经解决了，问题似乎是我用框选工具框到了几个太小的目标，我将那几个小的框选目标删除后点击查看翻译就正常了
