### ISSUE TITLE
在点击选中框的时候就会报错，感觉像翻译问题，3.0版本

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#667]
error: java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "wfe.senderFilter" is null
StackTrace: java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "wfe.senderFilter" is null
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:957)
	at org.xulihang.imagetrans.mt._getmt(mt.java:851)
	at org.xulihang.imagetrans.main$ResumableSub_appendSingleMTResult.resume(main.java:1535)
	at org.xulihang.imagetrans.main._appendsinglemtresult(main.java:1506)
	at org.xulihang.imagetrans.main$ResumableSub_showMT.resume(main.java:24817)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
启用了哪些机器翻译，是切换到辅助翻译选项卡的情况下，点击文本框报错吗

我试了下没问题

**Comment by xulihang** [comment]
噢，在偏好设置里把默认的cloudtranslation禁用吧，这个有问题

**Comment by hucurve** [comment]
好的，但还有其他问题麻烦解答一下也
