### ISSUE TITLE
点击查看翻译的时候出现以下问题

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#670]
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\imgcodecs\src\loadsave.cpp:1121: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\imgcodecs\src\loadsave.cpp:1121: error: (-215:Assertion failed) !image.empty() in function 'cv::imencode'
]
	at org.opencv.imgcodecs.Imgcodecs.imencode_1(Native Method)
	at org.opencv.imgcodecs.Imgcodecs.imencode(Imgcodecs.java:722)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._imencode(cv2.java:302)
	at org.xulihang.imagetrans.cvmat._mat2bytes(cvmat.java:134)
	at org.xulihang.imagetrans.utils$ResumableSub_GenTextMaskExternal.resume(utils.java:1708)
	at org.xulihang.imagetrans.utils._gentextmaskexternal(utils.java:1656)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMaskExternal.resume(utils.java:5551)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by hucurve** [comment]
我使用的windows完整版的包，环境应该不用配置的吧

**Comment by xulihang** [comment]
这是用哪个掩膜生成工具去生成掩膜的？

**Comment by hucurve** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/ff2c75d8-48de-4edc-9480-3c716a48e490)
我是用的这个因为发现其他的不起作用

**Comment by xulihang** [comment]
我试了下没问题，可以把图片发过来我测试一下

**Comment by hucurve** [comment]
上个版本还是有部分的报错

**Comment by xulihang** [comment]
有影响使用吗，有些输出不影响使用的

**Comment by hucurve** [comment]
输出不掩膜了，也不能预览翻译了。哎早上买了，用了一天都在报错

**Comment by xulihang** [comment]
把图片发给我，我可以演示一下合适的操作

**Comment by hucurve** [comment]
发过去了大哥，辛苦你了

**Comment by hucurve** [comment]
我发现问题了，需要删除部分没有识别到文字的文本框。第三个模型似乎依赖选中的对象，删掉就好了

**Comment by xulihang** [comment]
演示视频和项目已经发过去了
