### ISSUE TITLE
Tesseract不能用

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#675]
error: java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "wfe.senderFilter" is null
StackTrace: java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "wfe.senderFilter" is null
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.ocr$ResumableSub_tesseractInLines.resume(ocr.java:4729)
	at org.xulihang.imagetrans.ocr._tesseractinlines(ocr.java:4628)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetText.resume(ocr.java:1892)
	at org.xulihang.imagetrans.ocr._gettext(ocr.java:1785)
	at org.xulihang.imagetrans.main$ResumableSub_OCRBox.resume(main.java:18328)
	at org.xulihang.imagetrans.main._ocrbox(main.java:18276)
	at org.xulihang.imagetrans.main$ResumableSub_OCRAllBoxes.resume(main.java:17963)
	at org.xulihang.imagetrans.main._ocrallboxes(main.java:17800)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:16316)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:14350)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)
![Uploading image_8.png…]()

**Comment by swswlg** [comment]
![image_8](https://github.com/xulihang/ImageTrans-docs/assets/172276973/9887306b-76d3-41f8-b395-8f0fc22a5ee4)
![image_9](https://github.com/xulihang/ImageTrans-docs/assets/172276973/d5a512b8-d811-41c6-b7ff-0b2f3fa5888c)

**Comment by xulihang** [comment]
照文档操作的吗：https://imagetrans.readthedocs.io/zh-cn/latest/gettingstarted.html#ocr

**Comment by swswlg** [comment]
我就是看了文档也没整明白才来问的啊    1. Tesseract 
需要使用Tesseract进行OCR的话请自行下载安装(地址)，并在ImageTrans里指定Tesseract的路径。 
这里再提供一个Windows的绿色版本:百度网盘(提取码:ktpt)。下载后将tesseract-ocr目录和ImageTrans放在一起。额外的语言包请放在 tesseract-ocr\tessdata 目录下。

**Comment by xulihang** [comment]
简单的方法：

1. 下载安装包安装：https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.4.0.20240606.exe
2. 在偏好设置里指定tesseract.exe的路径

**Comment by swswlg** [comment]
能用了
