### ISSUE TITLE
排序时出错

### ISSUE THREAD

**Issue by 1274248407** [xulihang/ImageTrans-docs#682]
error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.boxessort._flipboxes(boxessort.java:386)
	at org.xulihang.imagetrans.boxessort._flipboxesandpanelsifright2left(boxessort.java:401)
	at org.xulihang.imagetrans.boxessort._sortboxes(boxessort.java:621)
	at org.xulihang.imagetrans.main._sortboxesforall(main.java:25731)
	at org.xulihang.imagetrans.main$ResumableSub_CustomizedWorkFlow.resume(main.java:5726)
	at org.xulihang.imagetrans.main._customizedworkflow(main.java:5393)
	at org.xulihang.imagetrans.main$ResumableSub_ExecuteWorkFlow.resume(main.java:7763)
	at org.xulihang.imagetrans.main._executeworkflow(main.java:7676)
	at org.xulihang.imagetrans.workflowconfig._okaybutton_mouseclicked(workflowconfig.java:300)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@23-ea/javafx.event.Event.fireEvent(Event.java:199)
	at javafx.graphics@23-ea/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
	at javafx.graphics@23-ea/javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
	at javafx.graphics@23-ea/javafx.scene.Scene.processMouseEvent(Scene.java:1893)
	at javafx.graphics@23-ea/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by 1274248407** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/80159393/7ef378c4-e3bb-4123-8889-466f96a8a186)

**Comment by xulihang** [comment]
报错的项目发一份给我，我试一下
