### ISSUE TITLE
I used the option to detect text and ocr areas and got an error.

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#689]
error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocationInner.resume(ocr.java:3078)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
Which OCR are you using and what image are you trying to OCR?

**Comment by truki20** [comment]
Baidu normal and the image was long I don't have the exact measurement

**Comment by xulihang** [comment]
Baidu has a usage limit if we use it to detect text with locations.

You can use other OCRs like paddleOCR or detect the text areas first and then OCR single areas.
