### ISSUE TITLE
Error when batch bubble detection

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#701]
Hi,
Im getting this error:
![Screenshot 2024-06-30 134921](https://github.com/xulihang/ImageTrans-docs/assets/174135705/17bf1cba-1966-454e-82ad-8a6f1e7a80c6)

**Comment by xulihang** [comment]
Please paste the entire message.

**Comment by xulihang** [comment]
It seems that one of the image files does not exist.

**Comment by Swerve1234** [comment]
error: java.io.FileNotFoundException: C:\Users\affib\Pictures\manga ding\Screenshot 2024-04-28 105910.png (Das System kann die angegebene Datei nicht finden)
StackTrace: java.io.FileNotFoundException: C:\Users\affib\Pictures\manga ding\Screenshot 2024-04-28 105910.png (Das System kann die angegebene Datei nicht finden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at anywheresoftware.b4a.objects.streams.File.OpenInput(File.java:218)
	at anywheresoftware.b4j.objects.ImageViewWrapper$ImageWrapper.Initialize(ImageViewWrapper.java:138)
	at anywheresoftware.b4j.objects.JFX.LoadImage(JFX.java:163)
	at org.xulihang.imagetrans.main._getimageforprocessing(main.java:10057)
	at org.xulihang.imagetrans.main$ResumableSub_autoRecognizeBallonForAll.resume(main.java:2524)
	at org.xulihang.imagetrans.main._autorecognizeballonforall(main.java:2376)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:16625)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:14669)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by Swerve1234** [comment]
> It seems that one of the image files does not exist.

that could be
Im creating a new folder

**Comment by xulihang** [comment]
Do not import another folder.

**Comment by Swerve1234** [comment]
I  just did.and its not working, what could I do else?

**Comment by xulihang** [comment]
Just start a new project and only import images from one folder.

**Comment by Swerve1234** [comment]
where can I find a fresh project file

**Comment by xulihang** [comment]
Use ImageTrans to create a new project.

**Comment by xulihang** [comment]
You should not ask these simple questions. I will not answer questions like this in the future.

**Comment by Swerve1234** [comment]
Im sorry I just really didnt find it, its not that I wasnt trying.

**Comment by Swerve1234** [comment]
That fixed it though thank you so much!
