### ISSUE TITLE
关于模型的调用顺序以及调用逻辑

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#704]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/d440b7d2-3188-4bd1-87ef-9b647386cb7c

老哥如视频所示 单独 把 右侧的录出来的
您看 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c52b4b33-8ba9-45f8-9b90-1de8c1c90957)
我在查看模型训练结果到时候 偶然的发现  好像不专门使用一个模型
而是多个离线模型同时使用的？
即便是 一直勾选这 这个选项
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b937cfe4-6cc6-444a-ace3-9ab4ed723337)

然后
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7a7e4863-8a17-4689-aa0a-342a5b7d3f72)
 项目文件和模型都发在同一个目录下
 还是会 同时使用2个模型 来跑
 我想知道这个可以 只专一的使用一个模型么
 因为这样就无法在IT上正确的显示查看 单一模型的训练结果了
 
 假如 训练的模型 对页面上的气泡 或者文字 X 进行识别 没有识别上
 这时候刚好 软件原来的模型 可以识别到 X    这样就会导致
 在查看结果的时候 发现都识别上了  无法判断这一部分的 训练 模型是否学会了

**Comment by xulihang** [comment]
你用的哪个版本？应该不会同时使用多个模型的

**Comment by lhj5426** [comment]
> 你用的哪个版本？应该不会同时使用多个模型的

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/718476c4-bcc0-4561-a9af-a6613caf3cff)
 这个 应该是最新版吧

**Comment by lhj5426** [comment]
> 你用的哪个版本？应该不会同时使用多个模型的

可现在确实是同时使用了多个模型 这个是BUG？

**Comment by xulihang** [comment]
试下3.1.1也有这个问题吗

**Comment by lhj5426** [comment]
啊 刚去了 看了 更新日志原
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/149cb011-fdfa-4ed8-aa14-bf0aeb61981f)
原来还 有个新版 我这个不是最新的我换最新的试试

**Comment by xulihang** [comment]
模型加载逻辑是3.2.0改的。之前每次都会从硬盘重新读取模型，3.2.0为了减少加载耗时，改成用全局变量，在必要时重新加载。照理每次操作只会用一个模型

**Comment by lhj5426** [comment]
> 模型加载逻辑是3.2.0改的。之前每次都会从硬盘重新读取模型，3.2.0为了减少加载耗时，改成用全局变量，在必要时重新加载。照理每次操作只会用一个模型

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1b0dbf6c-330b-4420-a329-179c271f272b)
刚试过 330 也是有这个问题

**Comment by lhj5426** [comment]
我激活了这个显示模型标签的选项之后
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6c4d8740-fa01-46f5-ba96-5945227f1931)
可以看到  那个是用自训练的 那些 是没有标记 既用了 原来的气泡模型

**Comment by xulihang** [comment]
我试了下没这个问题

**Comment by xulihang** [comment]
你用其它项目测试下。看看能不能复现。或者换两个模型再试

能复现的话把操作和项目发我试一下

**Comment by xulihang** [comment]
你用其它项目测试下。看看能不能复现。或者换两个模型再试

能复现的话把操作和项目发我试一下

**Comment by lhj5426** [comment]
> 你用其它项目测试下。看看能不能复现。或者换两个模型再试
> 
> 能复现的话把操作和项目发我试一下

我重新解压了一个纯净的 330 在D盘根目录
然后运行就报错了 这个是什么问题
error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 19
StackTrace: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 19
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at javafx.base@23-ea/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:88)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_recognizeBalloon.resume(main.java:21875)
	at org.xulihang.imagetrans.main._recognizeballoon(main.java:21840)
	at org.xulihang.imagetrans.main$ResumableSub_autoRecognizeBallonForAll.resume(main.java:2531)
	at org.xulihang.imagetrans.main._autorecognizeballonforall(main.java:2381)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:16824)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:14868)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
不清楚，没碰到过

**Comment by xulihang** [comment]
应该是OCR引擎没选中，报错了

**Comment by xulihang** [comment]
之前项目记住的是db-OCR，新解压一份里面没装这个插件

**Comment by lhj5426** [comment]
> 不清楚，没碰到过

好像是项目文件的锅？
新建了一个 项目文件
连。。。。 坐标都正常了。。。
新建的是这样的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/87d679c0-75c4-4c3a-abf4-b8f56a2ae12e)
一直用的是这样的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/22ff1ac5-0836-417c-82a0-f75d0dd44822)

**Comment by lhj5426** [comment]
> 之前项目记住的是db-OCR，新_解压_一份里面没装这个插件

嗯 对 因为是新解压的纯净 的所以 没这个插件
因为 就是想要测试一下   跑识别 就弄了个纯净的

**Comment by lhj5426** [comment]
如果说  没有使用多个模型的话 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/52a2a0cf-e96f-4f37-8a7c-568e6af97a95)
因为 新建了一个项目文件
乱码的 坐标都正常了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/51bc6801-da70-42a5-b5ff-133500aab404)
 可  有的气泡什么都不显示  这个 是 什么情况呢

**Comment by xulihang** [comment]
有的气泡有样式，有的没有是吗。不清楚

**Comment by xulihang** [comment]
有的气泡有样式，有的没有是吗。不清楚

**Comment by lhj5426** [comment]
> 有的气泡有样式，有的没有是吗。不清楚

嗯 是的 有的显示 有的不显示 而且我都把文字 样式和 打标签的的样式 全写上了

**Comment by lhj5426** [comment]
自动识别不显示 但是手动选择 会显示
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/079786d9-781e-4ba0-9bd7-3b1cdb4e5655)
 看来还是我自己的问题？ 抱歉了

**Comment by lhj5426** [comment]
Uploading bandicam 2024-07-01 20-34-52-279.mp4…

就是这样 哈哈

**Comment by lhj5426** [comment]
我这个网络今天有问题
40M 传死我了 
老哥 我把项目文件和示例图片 打包 到OD了
https://alumnialbany-my.sharepoint.com/:u:/g/personal/planetrav_alumni_albany_edu/Edzh4FWxwEFJiA5ImxdSUmcBefrxU79UakhU876UxGl5qA?e=kAoR7n
GITHUB抠门的就给10M 完全无法上传
麻烦请您过目一下  在您那边能不能复现这个问题  谢谢了

**Comment by xulihang** [comment]
我看了下，是配置文件有下面的配置。软件会把图片切分成小的去识别并合并重叠的检测结果。合并过后，我忘记保留样式了，所以不显示。

```json
"ratio":1,
"width_overlap":"0",
"height_overlap":"20"
```


把配置文件改成下面这样，样式和小数点问题就都没有了。

```json
{
	"width":640,
	"height":640,
	"model":"model.onnx"
}
```

**Comment by xulihang** [comment]
我试了下，用下面这个配置识别效果可能要好一点，会用滑动窗口去识别。

就是合并区域后丢失样式的问题需要我修复一下。

```json
{
   "width":640,
   "height":640,
   "ratio":1,
   "model":"model.onnx",
   "slidingWindow":{
      "width":1600,
      "height":1600
   }
}
```

**Comment by lhj5426** [comment]
> 我试了下，用下面这个配置识别效果可能要好一点，会用滑动窗口去识别。
> 
> 就是合并区域后丢失样式的问题需要我修复一下。
> 
> ```json
> {
>    "width":640,
>    "height":640,
>    "ratio":1,
>    "model":"model.onnx",
>    "slidingWindow":{
>       "width":1600,
>       "height":1600
>    }
> }
> ```

嗯嗯 谢谢老哥

**Comment by xulihang** [comment]
> 我试了下，用下面这个配置识别效果可能要好一点，会用滑动窗口去识别。
> 
> 就是合并区域后丢失样式的问题需要我修复一下。
> 
> ```json
> {
>    "width":640,
>    "height":640,
>    "ratio":1,
>    "model":"model.onnx",
>    "slidingWindow":{
>       "width":1600,
>       "height":1600
>    }
> }
> ```

这个问题3.3.1已经修复了。
