### ISSUE TITLE
help translating korean manga to english

### ISSUE THREAD

**Issue by PascalPreibisch** [xulihang/ImageTrans-docs#707]
Im using this software for my first time. I have BasicCat installed, i have the imageTransdownloaded and unzped from my purchase, i installed the newest version of java. Image Trans can be open but if i want to check for textboxes or i want to translate than i get a java error.
Am i missing something?

error: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
StackTrace: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:3272)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
What image do you need to translate?

**Comment by PascalPreibisch** [comment]
i want to translate some manga pages. at the moment from korean to english

**Comment by xulihang** [comment]
Try to follow the docs and this blog: https://www.basiccat.org/how-to-translate-raw-webtoon-in-korean/

I'd recommend using Pororo for OCR.

**Comment by PascalPreibisch** [comment]
where and how can i add pororo?

**Comment by xulihang** [comment]
In the last part of the blog, there is the link to pororo.

**Comment by PascalPreibisch** [comment]
dumb question but do i need to put the models folder somewhere special? (pororo is now in the dropdown) but nothing happens by klicking on ocr

**Comment by xulihang** [comment]
Follow the guide to put it under `C:\` and double click run.bat to start pororo first.

**Comment by PascalPreibisch** [comment]
run.bat is i think the ImageTrans.bat am i right? when its not in the plugin in pororo self and the models are not bat files

**Comment by PascalPreibisch** [comment]
ah  ok any idea how it auto translate it? at the moment i need to go to translation assist and pick there what i think sounds the best but thats a lot of work on more than one image

**Comment by xulihang** [comment]
Edit -> Translate all text areas is for one image.
Project -> Batch -> Pretranslate is for all images.

Project -> Batch Translate and Project -> Custom Workflow is for all the images with all the operations needed.

**Comment by PascalPreibisch** [comment]
translate all text areas for one image. i cant select there pororo. do i miss there something? in the normal view top left is OCR, currentlanguage, and ocr mode (i guess) and there is pororo located but not in the translate all...

**Comment by xulihang** [comment]
Translate all text areas is only machine translation which does not uses pororo.

**Comment by PascalPreibisch** [comment]
what would be than there the best solution (for korean/japanese/chinese) at the moment is it baidu and 1000 ms interval. but when i press machine translation nothing happens

**Comment by xulihang** [comment]
Here is a demo video:

https://github.com/user-attachments/assets/f646a96d-f655-4ff3-b487-0234ecee240f

I am using a balloon detection model from here: https://github.com/xulihang/balloon-dataset

**Comment by PascalPreibisch** [comment]
ah ok i got it i have a lil bug with the translated checkbox left bottom corner. ii need to toggle it on off and than it translates without error. dont know why but that was i think the whole problem :D

**Comment by PascalPreibisch** [comment]
thanks alot you was a great help :)

**Comment by PascalPreibisch** [comment]
uhm sorry if i bother you :D i want to try out the google or chat gpt translation but i just get errors. only baidu and tencent works and the translation is horrible. do i need to activate an api key or are there other steps? when yes how do i have to do it?

**Comment by xulihang** [comment]
You can chrck out the tutorial blogs: https://www.basiccat.org/tagged/#imagetrans
