### ISSUE TITLE
点击自动识别文字的时候Java报错，实在不知道怎么调试

### ISSUE THREAD

**Issue by bullyqi** [xulihang/ImageTrans-docs#709]
error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at javafx.base@23-ea/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:88)
	at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
	at org.xulihang.imagetrans.main._currentfilename(main.java:5442)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:15857)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:14781)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics@23-ea/com.sun.javafx.application.Plat

**Comment by xulihang** [comment]
看错误是没有图片
