### ISSUE TITLE
出现了一个报错.

### ISSUE THREAD

**Issue by zerona2018** [xulihang/ImageTrans-docs#713]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._dilate(cv2.java:228)
	at org.xulihang.imagetrans.utils._gentextmask(utils.java:1632)
	at org.xulihang.imagetrans.utils._textmask2(utils.java:5299)
	at org.xulihang.imagetrans.utils$ResumableSub_TextMask.resume(utils.java:5087)
	at org.xulihang.imagetrans.utils._textmask(utils.java:5035)
	at org.xulihang.imagetrans.main$ResumableSub_GenTextMask.resume(main.java:9079)
	at org.xulihang.imagetrans.main._gentextmask(main.java:8998)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:19560)
	at org.xulihang.imagetrans.main._previewoneimage(main.java:19467)
	at org.xulihang.imagetrans.main$ResumableSub_switchImage.resume(main.java:24737)
	at org.xulihang.imagetrans.main._switchimage(main.java:24669)
	at org.xulihang.imagetrans.main._refresh(main.java:20939)
	at org.xulihang.imagetrans.main._imagescrollpane_action(main.java:10711)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\imgproc\src\morph.dispatch.cpp:1022: error: (-215:Assertion failed) !src.empty() in function 'cv::dilate'
]
	at org.opencv.imgproc.Imgproc.dilate_4(Native Method)
	at org.opencv.imgproc.Imgproc.dilate(Imgproc.java:3927)
	... 30 more

请问是什么问题吗?

**Comment by xulihang** [comment]
之前相关的issue：https://github.com/xulihang/ImageTrans-docs/issues/282

查看下有没有错误的文本框

**Comment by zerona2018** [comment]
我可能是用了全图自动选.后来我手动一个一个自己画框就没事了.
