### ISSUE TITLE
[error] export text area into picture

### ISSUE THREAD

**Issue by apt42541** [xulihang/ImageTrans-docs#715]
it error like this?

error: java.lang.IllegalArgumentException: width [0] and height [0] must be > 0
StackTrace: java.lang.IllegalArgumentException: width [0] and height [0] must be > 0
	at org.imgscalr.Scalr.createOptimalImage(Scalr.java:2037)
	at org.imgscalr.Scalr.crop(Scalr.java:873)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.Crop(B4XViewWrapper.java:868)
	at org.xulihang.imagetrans.exporter._exportboxestoimagesforocr(exporter.java:856)
	at org.xulihang.imagetrans.exporter._exportboxestoimages(exporter.java:719)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:17148)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:15048)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
There are some invalid boxes whose width or height is < 0. Remove them and then try again.
