### ISSUE TITLE
3.4.0 排序报错

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#716]
error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.boxessort._flipboxes(boxessort.java:386)
	at org.xulihang.imagetrans.boxessort._flipboxesandpanelsifright2left(boxessort.java:401)
	at org.xulihang.imagetrans.boxessort._sortboxes(boxessort.java:628)
	at org.xulihang.imagetrans.main._sortboxesforall(main.java:27072)
	at org.xulihang.imagetrans.main$ResumableSub_CustomizedWorkFlow.resume(main.java:6010)
	at org.xulihang.imagetrans.main._customizedworkflow(main.java:5652)
	at org.xulihang.imagetrans.main$ResumableSub_ExecuteWorkFlow.resume(main.java:8306)
	at org.xulihang.imagetrans.main._executeworkflow(main.java:8219)
	at org.xulihang.imagetrans.workflowconfig._okaybutton_mouseclicked(workflowconfig.java:306)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:110)
	at anywheresoftware.b4j.objects.NodeWrapper$1.handle(NodeWrapper.java:1)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@23-ea/javafx.event.Event.fireEvent(Event.java:199)
	at javafx.graphics@23-ea/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3691)
	at javafx.graphics@23-ea/javafx.scene.Scene$MouseHandler.process(Scene.java:3996)
	at javafx.graphics@23-ea/javafx.scene.Scene.processMouseEvent(Scene.java:1893)
	at javafx.graphics@23-ea/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

https://github.com/user-attachments/assets/fede927f-6452-4cd6-9779-f4b7bf79c414

就是这样点击排序之后 就报错了。。

**Comment by lhj5426** [comment]
我以为是勾选了 声音 导致的
结果不勾选声音 也会报错
![image](https://github.com/user-attachments/assets/aacfa090-f71d-4f29-9c60-d2ac178e284d)

**Comment by lhj5426** [comment]
然后 不勾选这里 也一样报错
![image](https://github.com/user-attachments/assets/ed270cd8-1913-475c-838a-6ac2292ad1a4)
 哈哈  老哥这是什么原因啊

**Comment by lhj5426** [comment]
[3.4项目模版.zip](https://github.com/user-attachments/files/16428695/3.4.zip)
这是我的项目文件 我欢乐3.3.0 3.1.1 也会报错

**Comment by lhj5426** [comment]
没事了 项目文件有BUG  43 和44页卡住了  过着还是自己的问题
