### ISSUE TITLE
韩漫用什么翻译器啊，

### ISSUE THREAD

**Issue by ka7474** [xulihang/ImageTrans-docs#755]
是百度还是有道。为什么我一个都翻译不出来。还有我翻译美漫的时候卡卡的，就闪退又卡。一次翻译到底能有多大

**Comment by xulihang** [comment]
文档博客和视频都有看吗？

可以发个图片过来

**Comment by ka7474** [comment]
> 文档博客和视频都有看吗？
> 
> 可以发个图片过来

视频我看你翻译韩漫用的是youdao.但我使用毫无反应。我看了一下韩漫好像推荐使用pororo。现在是一个新的问题，我使用pororo也毫无反应。图片一提示我所选OCR未安装。但我已经按照操作执行了，图片二三四五，pororo已解压放到文件夹了，pororomodels也放到c盘了，plugin的文件也放到了plugins了，rut.bat也一直打开着窗口执行。到底是哪里出了问题。
![Uploading IMG_6253.jpeg…]()

**Comment by ka7474** [comment]
![IMG_6253](https://github.com/user-attachments/assets/40eaf246-0581-4107-ade9-9b74c893c2b4)

**Comment by ka7474** [comment]
> 文档博客和视频都看了吗？
> 
> 可以发个图片过来
视频我看你翻译韩漫用的是youdao.但我使用毫无反应。我看了一下韩漫好像推荐使用pororo。现在是一个新的问题，我使用pororo也毫无反应。
提示我所选OCR未安装。但我已经按照操作执行了，图片二三四五，pororo已解压放到文件夹了，pororomodels也放到c盘了，plugin的文件也放到了plugins了，rut.bat也一直打开着窗口执行。到底是哪里出了问题。
![IMG_6253](https://github.com/user-attachments/assets/6277abc7-44e6-4ebe-ba78-07fa0d3fdc5c)

**Comment by xulihang** [comment]
模型放的位置不对，服务器运行结果显示还在下载模型。直接复制pororo目录过去，不是放在pororo-models目录中。

**Comment by ka7474** [comment]
[pororo能用了，但是为什么会出现这个错误😭是文件太大了吗，就要汉四五十个左右而已↓点击查看翻译的时候出现的](![IMG_6745](https://github.com/user-attachments/assets/439d6a57-ffa7-46e3-9552-8e00387fd5c9))
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:418)
	at java.base[表情]k.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:166)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:3483)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:3129)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:24996)
	at org.xulihang.imagetrans.main._removetext(main.java:24914)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:22444)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by ka7474** [comment]
pororo已经弄好了，但是为什么会出现这个错误，↓而且有时候闪退呀，是文件太大了吗😭（我不知道上限是多少），而且只有四五十个而已
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:418)
	at java.base[表情]k.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:166)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:3483)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:3129)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:24996)
	at org.xulihang.imagetrans.main._removetext(main.java:24914)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:22444)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by ka7474** [comment]
> pororo已经弄好了，但是为什么会出现这个错误，↓而且有时候闪退呀，是文件太大了吗😭（我不知道上限是多少），而且只有四五十个而已 error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError' ] StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError' ] at org.opencv.core.Core.copyMakeBorder_0(Native Method) at org.opencv.core.Core.copyMakeBorder(Core.java:418) at java.base[表情]k.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132) at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:166) at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:3483) at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:3129) at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:24996) at org.xulihang.imagetrans.main._removetext(main.java:24914) at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:22444) at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136) at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85) at anywheresoftware.b4a.BA.raiseEvent(BA.java:78) at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086) at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456) at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455) at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184) at java.base/java.lang.Thread.run(Thread.java:1575)

对了还有这个错误error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.9.0) C:\GHA-OCV-1\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 166379232 bytes in function 'cv::OutOfMemoryError'
]
	at org.opencv.core.Core.copyMakeBorder_0(Native Method)
	at org.opencv.core.Core.copyMakeBorder(Core.java:418)
	at java.base[表情]k.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._copymakeborder(cv2.java:166)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:3483)
	at org.xulihang.imagetrans.utils._inpaintbybox(utils.java:3129)
	at org.xulihang.imagetrans.main$ResumableSub_RemoveText.resume(main.java:24996)
	at org.xulihang.imagetrans.main._removetext(main.java:24914)
	at org.xulihang.imagetrans.main$ResumableSub_PreviewOneImage.resume(main.java:22444)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
有测试图片吗

把图片缩小再给imagetrans处理或者不要勾选精确文字抹除模式

**Comment by ka7474** [comment]
> 有测试图片吗
> 
> 把图片缩小再给imagetrans处理或者不要勾选精确文字抹除模式

好吧确实可以了。但我想知道文件大小限制多少啊，以及有没有宽高限制

**Comment by xulihang** [comment]
没有具体的限制。

但硬件好点肯定能处理更大的图。
