### ISSUE TITLE
Error message when detecting text

### ISSUE THREAD

**Issue by Saryon8** [xulihang/ImageTrans-docs#76]
Hi

I have this error message everytime i try detecting text area:

"error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.ocr$ResumableSub_ocrspace.resume(ocr.java:3434)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)"
	
Do you know where the problem is and how to solve it?

Thanks.

**Comment by xulihang** [comment]
The OCRSpace engine does not work well on large images. You may have to use another OCR engine.

If you runs windows 10, you can use the WinRT OCR engine. The OCESpace service uses it as its backend.

**Comment by Saryon8** [comment]
I was using the fonction to detect all text area in "project","batch", not manual OCR: it detects fairly right text areas of the first few pictures, then i got the message.

I just try to translate a standard format manga page, not something too big. I'm on windows 10.

**Comment by xulihang** [comment]
Can you detect text areas of that failed image by using Edit-Detect text areas and recognize text?

It may also be because the time interval of OCR requests is not long enough.

**Comment by Saryon8** [comment]
I use "detect text area and regognize text for all picture": that's when i do that that i have the error message.

I'm on a old computer with not too much RAM and internet is also quite slow here, maybe that's with it doesn't work.

**Comment by xulihang** [comment]
I mean using this function on only the failed image. The OCRSpace engine may have problems processing the image. Use another ocr engine if it does not work.

**Comment by Saryon8** [comment]
I didn't block on a particular image. It failed every time but at a different state of the manga, simingly at random. And i think the error message can be a clue of the reason.

**Comment by xulihang** [comment]
The OCRSpace API has a rate limit. Try to use your own API Key. This may solve the problem. Details: http://ocr.space/OCRAPI
