### ISSUE TITLE
点击自动翻译所有区域出现了这个错误

### ISSUE THREAD

**Issue by ka7474** [xulihang/ImageTrans-docs#765]
error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
StackTrace: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
    at java.base/java.util.Objects.checkIndex(Objects.java:365)
    at java.base/java.util.ArrayList.get(ArrayList.java:428)
    at anywheresoftware.b4a.objects.collections.List.Get(List.java:105)
    at org.xulihang.imagetrans.main$ResumableSub_batchTranslate.resume(main.java:3524)
    at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
    at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
    at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
    at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
    at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
默认提供的百度翻译API的月字数限制超了。换个机器翻译或者用自己的API Key。

![image](https://github.com/user-attachments/assets/7a59281f-1e32-4f91-a436-f1ccdb03e395)

**Comment by ka7474** [comment]
啊，这样的吗，下个月还可以使用吧

**Comment by xulihang** [comment]
下个月就又有100万字额度

**Comment by ka7474** [comment]
今天1号了，又出现了这个错误😭😭，所以什么时候可以用呀😭😭

**Comment by xulihang** [comment]
账号欠费了，需要我充点钱。你可以自己申请一个，比如按照这个教程：https://www.basiccat.org/zh/how-to-use-youdao-in-imagetrans/
