### ISSUE TITLE
Paddle OCR 报错

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#792]
我使用了https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR 的教程启动，但是是在官网上拉取的paddle OCR，当天完美运行，重启了一下就不行了，不知道咋回事，日志如下

serving on http://127.0.0.1:8080
japan
[2024/11/09 21:28:04] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='C:\\Users\\hujun/.paddleocr/whl\\det\\ml\\Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\hujun/.paddleocr/whl\\rec\\japan\\japan_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='S:\\anaconda3\\Lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\japan_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=False, cls_model_dir='C:\\Users\\hujun/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='japan', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2024/11/09 21:28:04] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/11/09 21:28:06] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
.jpg
[2024/11/09 21:28:08] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
[2024/11/09 21:28:09] ppocr DEBUG: dt_boxes num : 0, elapsed : 0.3973708152770996
[2024/11/09 21:28:09] ppocr DEBUG: rec_res num  : 0, elapsed : 0.0
None
Traceback (most recent call last):
  File "S:\anaconda3\Lib\site-packages\bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "S:\anaconda3\Lib\site-packages\bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hujun\Downloads\server_paddleocr.py", line 38, in ocr
    for line in result:
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [09/Nov/2024:21:28:04 +0800] "POST /ocr HTTP/1.1" 500 744 "-" "okhttp/3.12.12"

**Comment by xulihang** [comment]
应该是新版本返回的结果变了，要改下代码。

**Comment by xulihang** [comment]
rapidOCR用的也是paddleOCR的模型，你看下效果差不多的话，也可以用这个。

**Comment by hucurve** [comment]
> rapidOCR用的也是paddleOCR的模型，你看下效果差不多的话，也可以用这个。

我有用过，我在识别日语手写体（竖排文字）， rapidOCR的模型效果非常差，paddleOCR会好很多。或者有什么其他推荐吗？

**Comment by xulihang** [comment]
手写体我没测试过

**Comment by hucurve** [comment]
我重启了软件最后可用了
总体而言我认为Paddle OCR表现依旧不如manga OCR

**Comment by xulihang** [comment]
PaddleOCR需要自己训练，我自己是没这个能力，只能希望有人能训练并公开模型。有个相关的项目：https://github.com/gnurt2041/MangaOCR
