### ISSUE TITLE
Problem with Google Drive OCR

### ISSUE THREAD

**Issue by CapMan47** [xulihang/ImageTrans-docs#797]
Hello. I have a problem with Google Drive OCR. 
Recently, it has been very common to request confirmation of the request through the browser. Literally every second attempt to make an OCR, a request comes out to confirm the request. It's about the OAuth window for confirming the token. 
This used to happen very rarely, but now it is incredibly common. 
I understand that the problem is not on your side, but perhaps you can tell me something or know a solution? 
I would be grateful)

**Comment by xulihang** [comment]
I can reproduce this problem.

It failed to upload the image to google drive and throwed a timed out error.

Any error occurred will trigger the reauthentication.


```
java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.implRead(Socket.java:1116)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1103)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketIm
```

**Comment by CapMan47** [comment]
Okay, is it clear what exactly is causing this problem and can I fix it somehow? 
If you can reproduce the problem, then if there is an understanding of how to fix or avoid it?

**Comment by xulihang** [comment]
I've updated the jar: https://github.com/xulihang/Google-Drive-OCR-Java/releases/download/builds/google_drive_ocr_commandline.jar . If it failed to OCR, it will just return an empty string.

**Comment by CapMan47** [comment]
Thanks a lot, I'll give it a try)

**Comment by CapMan47** [comment]
Hello again) 
Once again a small question on Goggle Drive OCR. I usually use it with English text and I often face the problem that letters are recognized as Russian. For example Y as У. 
This is not a critical problem, but maybe you know a solution or workaround to the problem?

**Comment by xulihang** [comment]
You can use AutoCorrect to fix misrecognized characters.

![image](https://github.com/user-attachments/assets/647ac25b-abed-4c06-90dd-fa901baa9e98)

**Comment by CapMan47** [comment]
All right, I'll give it a shot, thy)
