### ISSUE TITLE
ocrspace issue

### ISSUE THREAD

**Issue by Terrorbyte23** [xulihang/ImageTrans-docs#81]
Hi, I'm not too sure why but I get the following error when trying to ocr a text

error: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
StackTrace: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2775)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

Is anyone able to help? Thanks!

**Comment by xulihang** [comment]
Duplicate issue of https://github.com/xulihang/ImageTrans-docs/issues/76
