### ISSUE TITLE
windows版本打不开软件

### ISSUE THREAD

**Issue by Sakana520** [xulihang/ImageTrans-docs#810]
有一段时间没用，以前都没有问题，最近打不开软件了，没有报错提示，点击软件无反应，无法启动
系统版本是windows10，卸载重新安装旧版本和新版本也是没反应，试着重新安装了微软运行库和java，关闭杀毒软件等方法也不行
不知道还有什么方法能判断问题出在哪里

**Comment by xulihang** [comment]
用ImageTrans完整版，直接解压运行的吗？

确保软件目录有jre文件夹，然后使用ImageTrans.bat去打开。

如果没反应，按住shift再右键，用powershell打开，执行`.\ImageTrans.bat`看输出结果

**Comment by Sakana520** [comment]
我确认是用ImageTrans完整版，直接解压运行，软件目录有jre文件夹

首先点击ImageTrans.bat ，出现以下画面一两秒后就自动消失
![Snipaste_2024-12-28_14-19-08](https://github.com/user-attachments/assets/757422b6-e234-4516-94df-17ec4a107924)

然后尝试用powershell打开，执行.\ImageTrans.bat输出结果如下：
PS F:\BaiduNetdisk\ImageTrans> .\ImageTrans.bat

F:\BaiduNetdisk\ImageTrans>jre\bin\java -jar -Xmx2048M ImageTrans.jar
Device locale: zh
Found 778 strings.
(ArrayList) []
Loading jar finished
Initializing plugin chatGPTMT
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
        at org.xulihang.imagetrans.main._loadopencv(main.java:10922)
        at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:1476)
        at org.xulihang.imagetrans.main._appstart(main.java:1422)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java455 in java.library.path: [F:\BaiduNetdisk\ImageTrans\jre\bin, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, C:\Program Files\Common Files\Oracle\Java\javapath, C:\windows\system32, C:\windows, C:\windows\System32\Wbem, C:\windows\System32\WindowsPowerShell\v1.0\, C:\windows\System32\OpenSSH\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR, C:\Users\kikon\AppData\Local\Microsoft\WindowsApps, D:\Bandizip;C:\Users\kikon\AppData\Local\Microsoft\WindowsApps;D:\Bandizip\;.]
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        ... 24 more

Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin deeplMT
Loading jar finished
Initializing plugin ExternalInpaint
Loading jar finished
Initializing plugin ExternalMaskGen
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin manga-ocrOCR
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin WinRTOCR
Loading jar finished
Initializing plugin yandexMT
plugins have changed!
(ArrayList) [chatGPTMT, cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, ExternalInpaint, ExternalMaskGen, google_driveOCR, googleMT, googleOCR, manga-ocrOCR, niutransMT, opusMT, paddleocrOCR, papagoMT, tencentOCR, webMT, WinRTOCR, yandexMT]
loading ocr plugins
run(Map) Not initialized
main.start (java line: 37)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
        at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
        at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
        ... 14 more
Caused by: java.lang.NullPointerException
        at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
        at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
        at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
        at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
        at org.xulihang.imagetrans.main._application_error(main.java:1212)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 15 more

**Comment by xulihang** [comment]
用的哪个版本，版本有点老了，目录下有opencv_java455.dll这个文件吗

**Comment by xulihang** [comment]
完整版里应该是有opencv的。没有的话，可以到这里下载：https://github.com/xulihang/ImageTrans-docs/releases/tag/opencv

**Comment by Sakana520** [comment]
是随便下的1.9版本，确认有opencv_java455.dll这个文件

现在用最新的3.14版本，目录里有opencv_java490.dll这个文件，执行同样操作后如下所示：

PS C:\Users\kikon\Desktop\Tool\ImageTrans> .\ImageTrans.bat

C:\Users\kikon\Desktop\Tool\ImageTrans>jre\bin\java -Xmx2048M --module-path jre\javafx\lib --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.web,javafx.swing --add-opens javafx.controls/com.sun.javafx.scene.control.skin=ALL-UNNAMED --add-exports javafx.base/com.sun.javafx.collections=ALL-UNNAMED -jar --add-exports java.desktop/sun.awt=ALL-UNNAMED .\ImageTrans.jar
Device locale: zh
Found 1042 strings.
(ArrayList) []
Loading jar finished
Initializing plugin chatGPTMT
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin deeplMT
Loading jar finished
Initializing plugin ExternalInpaint
Loading jar finished
Initializing plugin ExternalMaskGen
Loading jar finished
Initializing plugin geminiMT
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin imgbaiduOCR
Loading jar finished
Initializing plugin InsetRectMaskGen
Loading jar finished
Initializing plugin LamaInpaint
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:145)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
        at org.xulihang.imagetrans.main._loadopencv(main.java:15760)
        at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:2319)
        at org.xulihang.imagetrans.main._appstart(main.java:2252)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:44)
        at javafx.graphics@23-ea/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path: C:\Users\kikon\Desktop\Tool\ImageTrans\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Users\kikon\AppData\Local\Microsoft\WindowsApps;D:\Bandizip";C:\Users\kikon\AppData\Local\Microsoft\WindowsApps;D:\Bandizip\;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2442)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2066)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:130)
        ... 19 more

Loading jar finished
Initializing plugin manga-ocrOCR
Loading jar finished
Initializing plugin mangaTranslatorOCR
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papago_nvcloudMT
Loading jar finished
Initializing plugin pororoOCR
Loading jar finished
Initializing plugin RapidOCROCR
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin WinRTOCR
Loading jar finished
Initializing plugin yandexMT
plugins have changed!
(ArrayList) [chatGPTMT, cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, ExternalInpaint, ExternalMaskGen, geminiMT, google_driveOCR, googleMT, googleOCR, imgbaiduOCR, InsetRectMaskGen, LamaInpaint, manga-ocrOCR, mangaTranslatorOCR, niutransMT, opusMT, paddleocrOCR, papago_nvcloudMT, pororoOCR, RapidOCROCR, tencentOCR, webMT, WinRTOCR, yandexMT]
loading ocr plugins
run(Map) Not initialized
main.start (java line: 44)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getIcons()" because "this.stage" is null
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:44)
        at javafx.graphics@23-ea/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getIcons()" because "this.stage" is null
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
        at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
        at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getIcons()" because "this.stage" is null
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
        ... 14 more
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.getIcons()" because "this.stage" is null
        at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
        at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
        at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
        at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
        at org.xulihang.imagetrans.main._application_error(main.java:2011)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 15 more

**Comment by Sakana520** [comment]
![Snipaste_2024-12-28_14-52-46](https://github.com/user-attachments/assets/95aabbee-db32-4127-8285-e8d8f6f38809)

**Comment by xulihang** [comment]
不知道你改了什么设置，导致运行库的路径没有软件当前目录。

可以在软件目录新建一个`opencvlib_path`文件，内容是opencv dll的路径，比如：

```
C:\Users\HP\Documents\GitHub\ImageTrans\Objects\opencv_java490.dll
```

**Comment by Sakana520** [comment]
十分感谢，按照您的说明已经解决
