### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by wufengji22** [xulihang/ImageTrans-docs#88]
一翻译就报错，这是为什么？

**Comment by xulihang** [comment]
怎么操作的，报了什么错，麻烦具体讲一下

**Comment by wufengji22** [comment]
就一键翻译的时候
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.3) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\caffe\caffe_io.cpp:1133: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "E:\BaiduNetdiskDownload\翻译\ImageTrans\frozen_graph.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.3) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\caffe\caffe_io.cpp:1133: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "E:\BaiduNetdiskDownload\����\ImageTrans\frozen_graph.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
]
	at org.opencv.dnn.Dnn.readNet_2(Native Method)
	at org.opencv.dnn.Dnn.readNet(Dnn.java:388)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.imageclassifier._initialize(imageclassifier.java:238)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:6737)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:6625)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:2687)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2021年10月5日(星期二) 晚上11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] 报错问题 (#88)






怎么操作的，报了什么错，麻烦具体讲一下

—
您正在接收此消息，因为您修改了打开/关闭状态。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by xulihang** [comment]
软件的路径不要有中文

**Comment by wufengji22** [comment]
好的，我试一下





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lihang ***@***.***&gt;; 
发送时间: 2021年10月5日(星期二) 晚上11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [xulihang/ImageTrans-docs] 报错问题 (#88)





 
软件的路径不要有中文
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wufengji22** [comment]
这个是要给什么权限吗？
error: java.io.FileNotFoundException: C:\Users\wufengji\AppData\Local\Temp\10 (拒绝访问。)
StackTrace: java.io.FileNotFoundException: C:\Users\wufengji\AppData\Local\Temp\10 (�ܾ����ʡ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init&gt;(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月5日(星期二) 晚上11:57
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] 报错问题 (#88)





 
软件的路径不要有中文
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wufengji22** [comment]
翻译的时候，选择后，点识别就会弹出来这个。给管理员权限都没用。



---原始邮件---
发件人: "Lihang ***@***.***&gt;
发送时间: 2021年10月6日(周三) 上午10:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [xulihang/ImageTrans-docs] 报错问题 (#88)




 
这是执行什么操作时出现的，我看看我这里能不能复现。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulihang** [comment]
C盘空间是不是不够了

**Comment by xulihang** [comment]
看不出是什么原因，换个本地OCR引擎试试吧，tesseract或者WinRT

**Comment by wufengji22** [comment]
冒昧的问一下，在哪里换？。。。



---原始邮件---
发件人: "Lihang ***@***.***&gt;
发送时间: 2021年10月6日(周三) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [xulihang/ImageTrans-docs] 报错问题 (#88)




 
看不出是什么原因，换个本地OCR引擎试试吧，tesseract或者WinRT
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulihang** [comment]
左上角选择语言和OCR引擎：
![image](https://user-images.githubusercontent.com/5462205/136168900-a834c7ed-e1af-4941-9ea1-de804d86e074.png)

你文档没看吗，建议先看一遍：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html

**Comment by wufengji22** [comment]
哦，你说的是这个呀，我看过了，和那个ocr引擎没关系的，不是那个的问题&nbsp; &nbsp; 还是这样，我也一头雾水
error: java.io.FileNotFoundException: C:\Users\wufengji\AppData\Local\Temp\11 (拒绝访问。)
StackTrace: java.io.FileNotFoundException: C:\Users\wufengji\AppData\Local\Temp\11 (�ܾ����ʡ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init&gt;(Unknown Source)
	at anywheresoftware.b4a.objects.streams.File.OpenOutput(File.java:439)
	at org.xulihang.imagetrans.httputils2service._hc_responsesuccess(httputils2service.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月6日(星期三) 下午4:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] 报错问题 (#88)





 
左上角选择语言和OCR引擎：
 
 
你文档没看吗，建议先看一遍：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulihang** [comment]
这个问题之前有用户报过：https://github.com/xulihang/ImageTrans-docs/issues/66

不知道他后来怎么解决的

**Comment by xulihang** [comment]
项目文件和具体操作步骤发我下吧，我看看能不能重现这个问题。我这边不能重现，没办法找原因。
