### ISSUE TITLE
google ocr problem

### ISSUE THREAD

**Issue by yureuori** [xulihang/ImageTrans-docs#95]
hello i'm having problem i don't know why it's telling me when i start translete

error: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
StackTrace: java.lang.ClassCastException: java.lang.String cannot be cast to anywheresoftware.b4a.objects.collections.List
	at org.xulihang.imagetrans.googleocrplugin$ResumableSub_GetTextWithLocation.resume(googleocrplugin.java:427)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
You need to apply your own API key to use Google OCR. I have written about this in the FAQ: https://www.basiccat.org/imagetrans/faq/

**Comment by ngawangtrinley** [comment]
Could the app show user a useful error message for that? I also got stuck there too and started to shout things I'm not proud of...
