### ISSUE TITLE
no opencv_java453 in java.library.path

### ISSUE THREAD

**Issue by TimeNajaXD** [xulihang/ImageTrans-docs#96]
I've already set up jre 1.8 but there is nothing coming up when I click the exe file and I got this error

java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
        at org.xulihang.imagetrans.main._loadopencv(main.java:8787)
        at org.xulihang.imagetrans.main$ResumableSub_AppStart.resume(main.java:1151)
        at org.xulihang.imagetrans.main._appstart(main.java:1099)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java453 in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        ... 24 more

Loading jar finished
Initializing plugin abbyycloudOCR
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin easyocrOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin googlewithoutapikeyMT
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin sogouOCR
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
plugins have changed!
(ArrayList) [abbyycloudOCR, cloudtranslationMT, clovaOCR, colorfulcloudsMT, easyocrOCR, googleMT, googleOCR, googlewithoutapikeyMT, niutransMT, paddleocrOCR, papagoMT, sogouOCR, tencentOCR, webMT]
loading ocr plugins
main.start (java line: 37)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:111)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at org.xulihang.imagetrans.main.start(main.java:37)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:496)
        at anywheresoftware.b4a.keywords.Common.CallSubNew3(Common.java:450)
        at anywheresoftware.b4a.BA.handleUncaughtException(BA.java:164)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:108)
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
        ... 14 more
Caused by: java.lang.NullPointerException
        at anywheresoftware.b4j.objects.Form.getIcon(Form.java:292)
        at anywheresoftware.b4j.objects.JFX.setOwnerAndIcon(JFX.java:178)
        at anywheresoftware.b4j.objects.JFX.Msgbox2(JFX.java:222)
        at anywheresoftware.b4j.objects.JFX.Msgbox(JFX.java:202)
        at org.xulihang.imagetrans.main._application_error(main.java:1083)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 15 more

**Comment by xulihang** [comment]
OpenCV is needed as well. You can use the full version from OneDrive which already has it included.

**Comment by TimeNajaXD** [comment]
I've openCV now but it still not working
![opencv](https://user-images.githubusercontent.com/93826307/140611345-8d4ac127-a268-4193-abfc-477c03d247e1.png)

**Comment by xulihang** [comment]
OpenCV 4.5.3 is needed. You can rename it to 453 as the two have few differences for ImageTrans.

**Comment by xulihang** [comment]
Simply renaming the file is not the way to go. I've uploaded the dll file here: https://github.com/xulihang/ImageTrans-docs/releases/download/opencv/windows_x64_opencv_java453.dll.zip
