### ISSUE TITLE
Error when click get text area confidence

### ISSUE THREAD

**Issue by TimeNajaXD** [xulihang/ImageTrans-docs#98]
error: java.lang.reflect.InvocationTargetException
StackTrace: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.imageclassifier._initialize(imageclassifier.java:238)
	at org.xulihang.imagetrans.main$ResumableSub_GetTextBoxesProbability.resume(main.java:6764)
	at org.xulihang.imagetrans.main._gettextboxesprobability(main.java:6652)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:11074)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:9749)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: unknown exception
	at org.opencv.dnn.Dnn.readNet_2(Native Method)
	at org.opencv.dnn.Dnn.readNet(Dnn.java:388)
	... 23 more

**Comment by xulihang** [comment]
What is the full path of the program? It should only contain English characters.

**Comment by TimeNajaXD** [comment]
I try to translate the Japanese manga.

**Comment by xulihang** [comment]
I mean path like this: D:\imagetrans.

**Comment by TimeNajaXD** [comment]
C:\Users\Admin\Desktop\ImageTrans

**Comment by TimeNajaXD** [comment]
I put it on Desktop

**Comment by xulihang** [comment]
What is the error after readNet? Usually, it is related to the path not being ascii characters.

**Comment by xulihang** [comment]
If the problem still exists, try to use opencv 4.5.3

**Comment by TimeNajaXD** [comment]
Can I have the download link please

**Comment by xulihang** [comment]
Download the full version from the onedrive which includes the dll file. Or you can get it by downloading the opencv build: https://sourceforge.net/projects/opencvlibrary/files/4.5.3/opencv-4.5.3-vc14_vc15.exe/download

**Comment by TimeNajaXD** [comment]
there's no dll file in the extracted folder from the link.
